### ISSUE TITLE
Panic with Multiple Icon Options

### ISSUE THREAD

**Issue by mitnk** [Peltoche/lsd#103]
The following command panic:
```
$ lsd --icon=never --icon=always
```
Because of a index overflow to [icon_theme_inputs](https://github.com/Peltoche/lsd/blob/70af39ed0a812e6d041e341a9aee7a3be44fd9bb/src/flags.rs#L75)

**Comment by Peltoche** [comment]
Hi @mitnk ,

Thanks for the report! I just found the reason, it's a dumb typo. I write the fix now.
