### ISSUE TITLE
tree display result not correct

### ISSUE THREAD

**Issue by mitnk** [Peltoche/lsd#104]
```
$ cd lsd/src
$ lsd --tree
```

## Expected behavior
```
...
├── icon.rs
├── main.rs
└── meta
    ├── date.rs
    ├── filetype.rs
    ├── indicator.rs
    ├── mod.rs
    ├── name.rs
    ├── owner.rs
    ├── permissions.rs
    ├── size.rs
    └── symlink.rs
```

## Actual behavior

`meta` does not show as the parent of its children.

```
│  ├── date.rs
│  ├── filetype.rs
│  ├── indicator.rs
│  ├── mod.rs
│  ├── name.rs
│  ├── owner.rs
│  ├── permissions.rs
│  ├── size.rs
│  └── symlink.rs
├── meta
├── app.rs
├── batch.rs
...
```

**Comment by iwestlin** [comment]
![image](https://user-images.githubusercontent.com/6235509/51520093-c6f13880-1e5d-11e9-8188-3a4fa14fddd1.png)
seems ok with me.

**Comment by Peltoche** [comment]
Hello @mitnk,

Can you give your version please? (`lsd --version`)

**Comment by mitnk** [comment]
lastest master - `70af39e`: `0.11.2-pre` on macos

**Comment by Peltoche** [comment]
There is indeed some regressions due to a big refactoring. I will try to fix this asap.
