### ISSUE TITLE
user permission result is wrong

### ISSUE THREAD

**Issue by VitalyAnkh** [Peltoche/lsd#107]
## Expected behavior
To show the permission for file `test`, execute `ls -l test` (I have aliased  `ls` to `lsd`), and the result should be `.rwxrw----`. 

## Actual behavior
The result of `ls -l test` is `.rwxrwx---`.
![_ _20190123060333](https://user-images.githubusercontent.com/24508452/51568553-f1320d00-1ed4-11e9-9260-6702b9b850c6.png)

I think it's a bug. I use the latest `lsd` on manjaro linux, and `lsd` is built with nightly rust, installed with `cargo install lsd`. How to fix this problem?

**Comment by Peltoche** [comment]
Hi @VitalyAnkh ,

Thanks for the report. There is indeed an issue. I create the fix now.
