### ISSUE TITLE
Add to AUR repository?

### ISSUE THREAD

**Issue by Skarlett** [Peltoche/lsd#110]
This is a really cool project, I think it would be nice to have it in the arch repository for easily installation. Including nerd fonts.

**Comment by Peltoche** [comment]
Hi @Skarlett ,

You can do: `pacman -S lsd`

Someone just have integrated lsd into the official repositories. :heart:

**Comment by Skarlett** [comment]
I didn't find it in the official repositories, but under the AUR repo it's listed under `lsd-git`. So I would consider this solved.
