### ISSUE TITLE
Icons not showing on Mac OS' Terminal.app

### ISSUE THREAD

**Issue by IngwiePhoenix** [Peltoche/lsd#111]
## Expected behavior
I expected to see my files listed, with pretty icons.

## Actual behavior
I did get my files listed...but no icons.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2893716/51765553-5e61c000-20d8-11e9-9c73-31e95b934f9f.png">

I am using `Fira Coda` as my font. Should I use a different one?

**Comment by Peltoche** [comment]
Hi @IngwiePhoenix ,

Like says @meain, it seems you doesn't use a valid font. If you think you have already downloaded a valid font, check that you terminal use it.

**Comment by IngwiePhoenix** [comment]
Which font do you recommend to be used with this tool?

**Comment by Peltoche** [comment]
I use FiraCode (sometimes also called FuraCode) from NerdFont. You can download the fonts [here](https://nerdfonts.com/)

**Comment by hwennnn** [comment]
s

**Comment by hwennnn** [comment]
@Peltoche Sorry for bothering. Seems like I am having a same issue with you. How do you solve this at the end?

**Comment by rahulkashyap-phy** [comment]
same problem here... installed nerd-font; tried changing the font in terminal profile but, icons do not appear.

**Comment by KulbhushanBhalerao** [comment]
Worked: Installed nerd fonts. Used font "Firacode Nerd Font"
