### ISSUE TITLE
Missing documentation/explanation about colors?

### ISSUE THREAD

**Issue by Termuellinator** [Peltoche/lsd#113]
While lsd seems to be a really nifty addon i can't seem to find an explanation on what which color indicates?
Some references that it is planed to use LS_COLORS, but even there i can't find a "standard" config.

**Comment by Skarlett** [comment]
> While lsd seems to be a really nifty addon i can't seem to find an explanation on what which color indicates?
> Some references that it is planed to use LS_COLORS, but even there i can't find a "standard" config.

Related to  #84

**Comment by Peltoche** [comment]
Hi @Termuellinator ,

It's true that the project is light on documentation. The issue #120 is a more general effort to improve it. You can contribute on it if you think some other documentation is missing.
