### ISSUE TITLE
use Vue icon

### ISSUE THREAD

**Issue by cat12079801** [Peltoche/lsd#117]
Now, `*.vue` file is not showing icon. But Nerd Fonts has Vue icon(nf-mdi-vuejs).
I want show vue icon.

![file vue](https://user-images.githubusercontent.com/4659010/52394511-e17a1180-2aed-11e9-972f-aa3911de6852.png)

If everyone does not create a PR I will create it. (Within a few days)

**Comment by Peltoche** [comment]
Hi @cat12079801 ,

It seems that your terminal doesn't use the correct font. The vue icon already exist [check here](https://github.com/Peltoche/lsd/blob/master/src/icon.rs#L286). The `?` icon indicate that your font is not able to load the given icon.

**Comment by cat12079801** [comment]
Oops, sorry. It's my mistake, and thank you!
