### ISSUE TITLE
Cargo.lock always out of sync in release tags

### ISSUE THREAD

**Issue by anthraxx** [Peltoche/lsd#119]
The Cargo.lock file is always out of sync in the release tags.
Its important that this file is perfectly in sync with the toml when tagging.
This lock file is used by distros to build with --locked to gain reproducible builds.

cheers

**Comment by Peltoche** [comment]
Hi @anthraxx,

Thanks for the report. It seems that the issue is due to the fact I use [cargo release](https://github.com/sunng87/cargo-release) for the publication. 

I will make the release manually now.
