### ISSUE TITLE
show current and parent directory with --all option

### ISSUE THREAD

**Issue by kaefert** [Peltoche/lsd#122]
the default `ls` command shows . & .. directories when the -a option is given.
I think this is very helpful together with the -l option to see the properties like permissions & owners of the current directory.

**Comment by Peltoche** [comment]
Hi @kaefert 

It's true that we don't have put those lines yet and we should probably do it. At the moment I don't have much time to implement it and I think it would make a good first issue for a newcomer.

If someone want to propose a PR, he is welcome!

**Comment by meain** [comment]
Closed  with #165
