### ISSUE TITLE
lsd crashes when output is not the tty

### ISSUE THREAD

**Issue by eli-schwartz** [Peltoche/lsd#123]
e.g. when it is a pipe:

```
$ lsd | less
thread 'main' panicked at 'failed to retrieve terminal size', src/display.rs:29:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Similarly when its output is captured in a variable (it is true that one should not parse ls output, but this is a harsh lesson for such an edge case):

```
$ foo=$(lsd)
thread 'main' panicked at 'failed to retrieve terminal size', src/display.rs:29:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
GNU ls would simply activate --oneline mode rather than try to calculate the size of a nonexistent tty.

**Comment by Peltoche** [comment]
Hi @eli-schwartz ,

Thanks for the report. It seems there was some regression in one of the last versions. @meain have just made a PR to fix it.
