### ISSUE TITLE
Icons are broken on sakura

### ISSUE THREAD

**Issue by hasufell** [Peltoche/lsd#124]
![lsd_broken_icons](https://user-images.githubusercontent.com/1241845/52610222-4604ea00-2ebb-11e9-966e-26223509ae8b.png)

Sakura 3.3.4
vte 0.54.2
config https://gist.github.com/hasufell/73f18273d87e0a7cb3ced4da79e1012c

**Comment by hasufell** [comment]
It seems I did not set up fonts correctly. I still wonder whether the default should be smart and detect that fonts cannot be displayed correctly and then default to none.

**Comment by Frixoe** [comment]
How did you fix this? I'm new to linux and am having the same problem.

**Comment by hasufell** [comment]
see https://github.com/Peltoche/lsd#prerequisites

**Comment by Frixoe** [comment]
Thank you
