### ISSUE TITLE
OSX displays all question marks instead of any icons from icons.rs

### ISSUE THREAD

**Issue by notactuallypagemcconnell** [Peltoche/lsd#129]
First off, thanks for making this! Its very neat. :) 

## Expected behavior
Show folder icons for folders, etc.

## Actual behavior
Icons seem to be loaded in with the package with a special font, but for some reason after a `cargo install lsd` on osx I get:

```
  bundle     deploy        migrate                          production_ironboard_enable_systemd.sh    production_ironworker_build.sh    rails    reset_sequence.sql    setup      webpack-dev-server
  db_dump    initialize    production_ironboard_build.sh    production_ironboard_start.sh             production_ironworker_start.sh    rake     rollout.delete        webpack
```

I would be happy to dive into this if you think its something someone beginner-ish with Rust could take on. I was browsing projects I might like to contribute to as I learn more and found this.

**Comment by notactuallypagemcconnell** [comment]
This seems related to #118 - going to close

**Comment by teras** [comment]
I have this issue as well, there is no documentation, is it something that I can do?

**Comment by arashout** [comment]
Also have this issue on Mac:
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

![Screen Shot 2019-09-20 at 6 13 09 PM](https://user-images.githubusercontent.com/10860860/65365894-755aa280-dbd2-11e9-872b-da0968764af4.png)
