### ISSUE TITLE
--tree is crashing

### ISSUE THREAD

**Issue by munim** [Peltoche/lsd#133]
`lsd --tree` is failing on my linux.
```
Linux my-pc 4.20.10-1-MANJARO #1 SMP PREEMPT Fri Feb 15 21:46:13 UTC 2019 x86_64 GNU/Linux
```
## LSD version
```
[101] % lsd --version
lsd 0.12.0
```

## Actual behavior
```
% RUST_BACKTRACE=1 lsd --tree
thread 'main' panicked at 'failed to convert modified time to timestamp: SystemTimeError(21600s)', src/libcore/result.rs:1009:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: __libc_start_main
  21: <unknown>
```

**Comment by Peltoche** [comment]
Hi @munim ,

Thanks for the report. It seems there is an issue with one of you file creation time and we probably handle it quite abruptly. We can probably replace the imparsable date field by some `????????`.

**Comment by munim** [comment]
Hi @Peltoche,

Thanks for the response. Is there any debug log I can look into that for which file it is failing?

**Comment by guihkx** [comment]
I was experiencing the same issue running `lsd` (no extra args) on my home directory:

```
$ RUST_BACKTRACE=1 lsd ~
thread 'main' panicked at 'failed to convert modified time to timestamp: SystemTimeError(1977666108s)', src/libcore/result.rs:1009:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: __libc_start_main
  20: <unknown>
```

Worked fine with `ls` and `exa` though. Then I searched for a file with an odd timestamp:

```
$ for f in *; do echo $f; lsd $f 1>/dev/null; done
Desktop
Documents
Downloads
[ ... some other files ... ]
logoint.jpg
thread 'main' panicked at 'failed to convert modified time to timestamp: SystemTimeError(1977666108s)', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Music
[... some other files ... ]
```

Yep, `~/logoint.jpg` is the one:

```
$ /bin/ls -la ~/logoint.jpg
-rw-r--r-- 1 me me 8016 May  2  1907 logoint.jpg
```

This is a file I extracted a while ago from a ISO of an old game, but I hadn't realized the timestamp until now... But then again, KDE's file manager (Dolphin), `ls` and `exa` are all able to display the date.

**Comment by Peltoche** [comment]
> Thanks for the response. Is there any debug log I can look into that for which file it is failing?

Nop, there is nothing at the moment...

**Comment by Peltoche** [comment]
> This is a file I extracted a while ago from an ISO of an old game (no, it's not from 1907), but I hadn't realized the timestamp until now... But then again, KDE's file manager (Dolphin), `ls` and `exa` are all able to display the date.

I guess the file is a little fucked up and the other tools have a better error handling with some kind of fallback. 

By curiousity, would it be possible to have the output of `exa` for this file?

**Comment by guihkx** [comment]
```
$ exa -la ~/logoint.jpg
.rw-r--r-- 8.0k me  2 May  1907 /home/me/logoint.jpg
```

**Comment by guihkx** [comment]
With lsd 0.14.0 the crash is gone, but the file date differs from exa/ls/dolphin:

```
$ lsd -l ~/logoint.jpg
.rw-r--r--  me  me  7.8 KB  Wed Dec 31 21:00:00 1969    logoint.jpg
```

Please ignore if this is intentional though...

**Comment by Peltoche** [comment]
> With lsd 0.14.0 the crash is gone, but the file date differs from exa/ls/dolphin:

I just fallback to a timestamp 0 for now but there is probably a better solution. I you think of something please, make an issue to propose an improvement.
