### ISSUE TITLE
Glyph "nf-fa-music" \uF001 not displayed correctly on iTerm.

### ISSUE THREAD

**Issue by nicu-chiciuc** [Peltoche/lsd#134]
## Expected behavior
I'm using "font-firacode-nerd-font" (installed using brew).
I expect all the glyphs to be displayed correctly.

## Actual behavior
All the other glyphs are displayed correctly except the "nf-fa-music" for .wav and .mp3 files:
![screenshot 2019-02-25 at 11 27 29 am](https://user-images.githubusercontent.com/4076804/53330852-398b8300-38f8-11e9-9045-7704fd477f68.png)

In Terminal, using the same font I get the following result:
![screenshot 2019-02-25 at 11 27 39 am](https://user-images.githubusercontent.com/4076804/53330907-5a53d880-38f8-11e9-9462-991e7efdaa61.png)

I realise that this might be a problem with iTerm and not LSD and I've opened an issue there [iterm2/issues/7570](https://gitlab.com/gnachman/iterm2/issues/7570).

Also, "nf-mdi-itunes" \uFB75 is displayed correctly in iTerm.
![screenshot 2019-02-25 at 12 27 01 pm](https://user-images.githubusercontent.com/4076804/53331052-ad2d9000-38f8-11e9-8ab2-869b0607f586.png)

**Comment by Peltoche** [comment]
Hi @nicu-chiciuc ,

Thanks for the report! It seems to be an issue with ITerm indeed. We keep this issue open in order to follow the bug resolution but I don't think we can do anything about it.

**Comment by nicu-chiciuc** [comment]
If someone else encounters this problem, George Nachman responded: https://gitlab.com/gnachman/iterm2/issues/7570#note_147643096
