### ISSUE TITLE
Would it make sense to add a -h flag for compatibility with ls?

### ISSUE THREAD

**Issue by dangom** [Peltoche/lsd#136]
## Expected behavior
```sh
alias ls='lsd'
ls -halt
```
Works.

## Actual behavior
```sh
alias ls='lsd'
ls -halt
```

Does not work. Prints usage.

**Comment by Peltoche** [comment]
Hi @dangom ,

The `-h` option doesn't exists because all the sizes are human readable by default.

**Comment by dangom** [comment]
Yes, I noticed that. The point is to keep compatibility with ls, so previous aliases don't break. The -h flag doesn't have to do anything.

**Comment by Peltoche** [comment]
Yep, it could be useful indeed. The flag description will must to be explicit on the fact that the flag does nothing and is for compatibility purpose.

Do you want to implement it?

**Comment by meain** [comment]
I guess the same should go for `-A` as well. As of right now `-a` is actually doing the job of `-A`. Maybe we should just have `-A` as a alias for `-a` for now until we get a fix for #122

**Comment by khross** [comment]
I would be happy to implement this and possibly the `-A` alias as well if nobody else has picked it up yet.

**Comment by Peltoche** [comment]
As the `-h` flag have been merged into master I close this issue. I will create an another issue for the `-A` flag.
