### ISSUE TITLE
lsd snap install fails on libgtk3-nocsd.so.0 and gets a permission denied

### ISSUE THREAD

**Issue by arthurlogilab** [Peltoche/lsd#148]
## Actual behavior
```
 lsd                                                                  (1s 77ms)  
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
cannot access '.': Permission denied (os error 13)
```

Works with debian package

**Comment by Peltoche** [comment]
HI @arthurlogilab ,

Thanks for the report! 

It's curious because I never heard about `libgtk3`. I'm not sure this error is related to `lsd`. 

In order to debug it can you give us the result of `lsd --version` and `echo $LD_PRELOAD`?

For the `Permission denied` I guess that you install `lsd` with `snap`? We have some issues about the permission with snap (#79), we working on it.

**Comment by arthurlogilab** [comment]
```
#  lsd --version
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
lsd 0.13.0
# echo $LD_PRELOAD
libgtk3-nocsd.so.0:libgtk3-nocsd.so.0
```

Thanks  for pointing me to #79

**Comment by Peltoche** [comment]
I think you issue is that you defines a LD_PRELOAD en variable which try to preload a library before executing the binary but as you installed `lsd` with snap and so the filesystem is "failed" it can't found the libgtk3 lib. I guess you have this error message with all the softwares you installed with snap.

To fix that you have two solutions:
- You install `lsd` with something else than snap and you fix the two issues at once.
- You remove the env variable `LD_PRELOAD` but it can break another binary which need it.

**Comment by arthurlogilab** [comment]
Thanks for taking a look at this. `sudo apt-get install libgtk3-nocsd0:i386` fixed it. For the snap problem I'm following the other issue, currently using the debian package.
