### ISSUE TITLE
1.13.0 Extra Spacing in output

### ISSUE THREAD

**Issue by Skarlett** [Peltoche/lsd#149]
from commit [#deea0df / 1.13.0](https://github.com/Peltoche/lsd/commit/deea0df83d74170a4263ea1f8162173e972da412) to [#0fa68098 / 1.12.1-pre](https://github.com/Peltoche/lsd/commit/0fa68098e2af46420a549f4a5d092dc882d1ecc3) a bug was introduced that screwed up some spacing on the terminal. I have repeated the same result using different shells (bash & zsh) ruling out the possible for some quirk or shell specific behavior.

**Workaround**: This bug stems from something inside of **color** you can fix the problem by removing the color with `--color never` [as shown here](https://i.imgur.com/0hqNmgy.png)

## Expected behavior
We expect the text margins to be aligned.  as shown from this picture from [zsh 0.12.1-pre](https://i.imgur.com/E3ysXZa.png)

## Actual behavior
We result in this currently.

[Bash 0.13.0](https://i.imgur.com/eMIY1Dc.png)
[Zsh 0.13.0](https://i.imgur.com/vPQEHjv.png)

## Related
#145 

## Exclusions
This doesn't seem to effect listings  `-l` `--tree`

**Comment by Peltoche** [comment]
Hi @Skarlett ,

Thanks for this great report, this help us a lot! I start working on it.

**Comment by Peltoche** [comment]
We just found the bug and the patch will be deployed soon with the `1.13.1`. For more information you can check #145.

I close the subject but don't hesitate to reopen it if needed.
