### ISSUE TITLE
Display tree in alphabetical order

### ISSUE THREAD

**Issue by petobens** [Peltoche/lsd#158]
Is it possible to add a flag to sort alphabetically when using the tree feature? Currently files are first shown and only then inner directories. I would like to replicate `tree` default behaviour:

![Screenshot_2019-03-12_14:37:13](https://user-images.githubusercontent.com/2583971/54222711-b9a71080-44d4-11e9-82f3-e762f2d05967.png)

I thought that maybe `lsd --tree --group-dirs=none` would achieve such behaviour but it didn't.

**Comment by Peltoche** [comment]
Hi @petobens,

Thanks for the report. It seems that the `--group-dirs=none` doesn't have the correct behavior indeed.
