### ISSUE TITLE
`lsd` output not aligned.

### ISSUE THREAD

**Issue by usmcamp0811** [Peltoche/lsd#160]
## Expected behavior

When I run the basic `lsd` command my files and folders are not properly aligned in my terminal. I am using terminator on Manjaro as my default terminal, though I have tested it to do the same on Gnome-Terminal, Xterm, terminal, and maybe a few others. 

I was able to get things to align as expected using Kitty terminal. 

`lsd -la` aligns with no problems. 

## Actual behavior

![image](https://user-images.githubusercontent.com/17965629/54478273-4eb04f00-47de-11e9-9282-fd8e90e413a5.png)

**Comment by Peltoche** [comment]
Hi @usmcamp0811,

Thanks for the report. This issue have been already reported (#145) and should be fixed with the version 1.14.0. Can you verify with `lsd --version` that you are up to date (>= 0.14.0)?

**Comment by usmcamp0811** [comment]
cool thanks.. yea I've got `lsd 0.13.0`
