### ISSUE TITLE
crates.io is not up to date

### ISSUE THREAD

**Issue by iicurtis** [Peltoche/lsd#167]
Currently [the crates.io package](https://crates.io/crates/lsd) is stuck at `0.13.0` while the latest release is `0.14.0`. This makes it difficult for users that make use of `cargo` (such as myself) to catch updates. The release has been out for about 11 days I think at this point, and I think its pretty stable.

Any reason this isn't up-to-date? If not, can we go ahead and push the latest release to `crates.io`?

**Comment by Peltoche** [comment]
Hi @iicurtis ,

Thanks for the report. I think its an error from my part. I fix this asap.

**Comment by Peltoche** [comment]
I should be ok now.
