### ISSUE TITLE
Icons are mismatched

### ISSUE THREAD

**Issue by sarpik** [Peltoche/lsd#168]
Hello,

I've noticed that the icons displayed for certain file extensions aren't correct.

Here's an example:
![](https://i.imgur.com/1WQPvOQ.png)

(If it's not obvious enough) then what's wrong is:
* `.c` has an `npm` icon
* `.js` doesn't have any icons
*  `.cpp` has a `django` icon

> Note - these are just a few extensions I could think of, but it looks like almost every icon is mismatched.

My OS:
`Linux arch-usb 5.0.3-arch1-1-ARCH #1 SMP PREEMPT Tue Mar 19 13:09:13 UTC 2019 x86_64 GNU/Linux`

**Comment by Peltoche** [comment]
Hi @sarpik ,

Thanks for the report. Can you give us the font you use? I think you should try another one, it should solve your issue.

**Comment by sarpik** [comment]
Hi @Peltoche,

No problem. I'm using `Liberation Mono` (set in my `$HOME/.Xdefaults`). I'm a little confused with fonts currently because emojis don't work properly atm, so I'll report back after I change that. Any font suggestions for arch linux?

**Comment by Peltoche** [comment]
> Any font suggestions for arch linux?

My urxvt config is `URxvt.font: xft:FuraCode Nerd Font Mono:style=Retina,Regular`. I found this font really good for reading code.

For you font configuration, verify that you use a `Nerd Font` font because those are the only font with the icons. To install those fonts you can check the [readme Prerequisites](https://github.com/Peltoche/lsd#prerequisites)

**Comment by sarpik** [comment]
Woah - that fixed it! Thanks @Peltoche! I installed https://aur.archlinux.org/packages/nerd-fonts-complete/, did `fc-list | grep -i fura` and selected the one I wanted.

My current `$HOME/.Xdefaults` look like this:

```
*.font: FuraCode Nerd Font Mono:pixelsize=22,style=Retina,Regular;
```

This is unrelated, but now the only thing that's missing from my terminal layout is **colorful** emoji support (I'm using [`st` / `simple terminal`](https://st.suckless.org/) and not urxvt), and my emojis aren't showing (st just closes, urxvt doesn't display them). I was wondering if you possibly had figured out a way to have **colorful** emoji support in the terminal? Thanks!

**Comment by Peltoche** [comment]
> This is unrelated, but now the only thing that's missing from my terminal layout is **colorful** emoji support (I'm using [`st` / `simple terminal`](https://st.suckless.org/) and not urxvt), and my emojis aren't showing (st just closes, urxvt doesn't display them). I was wondering if you possibly had figured out a way to have **colorful** emoji support in the terminal? Thanks!

No idea... Sorry.

**Comment by sarpik** [comment]
No problem, thanks anyway - you helped a lot already:) Have a nice day:)

**Comment by Waces** [comment]
Sorry if I'm being an idiot by trying to revive this (tell me if it's better to create a new issue) or simply doing something wrong

I'm using Monoid/Monoisome (which appears on the nerd-fonts list and is said to have font-awesome support) on Kitty terminal, I have font-awesome installed, and am having the same issue
