### ISSUE TITLE
lsd_0.14.0_amd64.deb no icons with Powerline Nerd Font

### ISSUE THREAD

**Issue by asteriosos** [Peltoche/lsd#177]
Hi there,

just want to let you know.

with the lsd_0.14.0_amd64.deb on debian 9.8(64bit) after i download the Powerline Nerd Font they don't work, still get no correct icon.

with the lsd_0.14.0_i386.deb and the Powerline Nerd Font on my 64bit System the icons show up. :-)

curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf

to /usr/share/fonts/opentype/

**Comment by J-Z-K** [comment]
With my Tamzen for powerline also it does not show icons.

**Comment by Peltoche** [comment]
Hi @asteriosos ,

Thanks for the report. Are you sure that you configured your terminal with the valid font? This is a very common mistake.

**Comment by asteriosos** [comment]
Hi, i think so. Today i installed the powerline, lsd on my i386 debian 9.8 after that on my xeon 64bit desktop same os, same procedere. I use konsole for terminal.

**Comment by asteriosos** [comment]
i removed the i386 version again an installed the amd64, now it works fine with:
Droid Sans Mono for Powerline Nerd Font Complete.otf.

you are right, maybe i missed to reload the font-cache ... thank you.

**Comment by asteriosos** [comment]
error sitting in front of the display
