### ISSUE TITLE
don't include icons when running on TTY

### ISSUE THREAD

**Issue by kaefert** [Peltoche/lsd#179]
As far as I understand it, the icons won't work on any non-GUI TTY.
(see also https://forum.manjaro.org/t/replacement-for-ls-lsd-ls-deluxe-icons-problems/74887 )

My suggestion would be to try to detect when `lsd` is not running in an graphical terminal emulator and the printing of the icons could be suppressed in such a case?

**Comment by Peltoche** [comment]
Hi @kaefert ,

It's been a while that I search how to do this and I recently found [this tiny piece of code](https://docs.rs/termion/1.5.1/src/termion/sys/unix/tty.rs.html#8-10) which should do the job. Sadly, at the moment I don't have much time for new features. If you want to make a PR it would be welcomed :)

**Comment by Sag0Sag0** [comment]
Issue is fixed.

**Comment by RyRch** [comment]
Hi ! i've also have the same issue icons don't show up in tyy where is the file to put your piece of code pls @Peltoche

**Comment by RyRch** [comment]
Ok i found this cmd : lsd --icon never
so in my .zshrc i put this code :

 if [  "$TERM"  =  "linux"  ]; then
alias ls="lsd --icon never"
fi
