### ISSUE TITLE
Support multiple sorting options (e.g. size)

### ISSUE THREAD

**Issue by Philipp-M** [Peltoche/lsd#180]
It would be nice to have support for something like exas `--sort` feature, which I often use.
exa supports the following:
`name, Name, size, extension, Extension, modified, accessed, created, inode, type, none`
I most often use size.
A killer feature would be to also include a sort size option that recursively includes the size of directories, like `du`, though this should probably be additional, as it could be quite slow (like --tree)

**Comment by Peltoche** [comment]
Hi @Philipp-M,

Thanks for the report! It seems to be a good feature indeed and it shouldn't be too hard to implement it. Sadly at the moment I don't have much time for writing new features. 

If you want to make a PR it would be very welcomed :)

**Comment by jhaungs** [comment]
There seems to be code in here to handle sorting by size, but for some reason the -S option is disallowed. I'm just learning rust, so I can sort of read it, but I had no luck understanding how the flag parsing works.

**Comment by meain** [comment]
We have most of these now ;) Anyone landing here, feel free to open and issue for any specific sort method.
