### ISSUE TITLE
grey color for temporary files ("file~" buffer files from vim or emacs for example)

### ISSUE THREAD

**Issue by arthurlogilab** [Peltoche/lsd#181]
## Expected behavior

It would be nice for temporary files like the buffer copies for emacs or vim to be greyed out (or have a lighter color that the "normal" version). 

I don't have the list of all namespaces used but here is a list off the top of my head : 

* ~FILENAME
* .#FILENAME#
* FILENAME.swap

Maybe https://www.gitignore.io/api/vim,emacs can be used as inspiration ?

**Comment by arthurlogilab** [comment]
example : 

![Screenshot from 2019-04-05 11-05-17](https://user-images.githubusercontent.com/445200/55616708-b846cc00-5792-11e9-91f2-c016c79e2b45.png)

**Comment by Peltoche** [comment]
Hi @arthurlogilab ,

This seems to be a good idea indeed. Do you want to propose an implementation? Sadly, at the moment I don't have much time for new feature...

**Comment by meain** [comment]
@arthurlogilab You should now be able to specify colors by setting LS_COLORS.
Feel free to reopen the issue if this does not solve your problem.

https://github.com/Peltoche/lsd/pull/84
