### ISSUE TITLE
Show symlink target with --tree option

### ISSUE THREAD

**Issue by sandorex** [Peltoche/lsd#185]
Add flag to show symlink target with tree option

**Comment by sandorex** [comment]
Im such a noob, if somebody could remove the bug label its not a bug...

**Comment by Peltoche** [comment]
Hi @sandorex ,

Thanks for the issue. This would be a great idea indeed.

**Comment by meain** [comment]
Hey @sandorex . PR #178  and PR #226 combined will help you to help you get what you need.

You can use something like `lsd --tree --depth 1 -l --blocks name` to get the desired output.

I don't think we have a release yet which has both the PR's but we should soon have one.
@Peltoche
