### ISSUE TITLE
No way to list directory itself rather than its contents

### ISSUE THREAD

**Issue by allenap** [Peltoche/lsd#190]
## Expected behavior

In "regular" `ls`, there is a `-d` flag:

```
       -d, --directory
              list directories themselves, not their contents
```

I often find this useful when checking ownership and permissions. I suspect it might be impossible to show file metadata for the root directory with `lsd` without this flag, i.e. `lsd -l /` shows the contents of `/` not the directory itself.

Here's the behaviour I would expect:

```
$ lsd -ld src
drwxr-xr-x  gavin  staff       -   Tue Apr 23 16:17:38 2019    src
```

Here's the behaviour of `/bin/ls` on Ubuntu 18.04:

```
$ /bin/ls -ld /
drwxr-xr-x 24 root root 4096 Apr  3 17:53 /
```

## Actual behavior

```
$ lsd -ld src
error: Found argument '-d' which wasn't expected, or isn't valid in this context

USAGE:
    lsd --long

For more information try --help
```

**Comment by allenap** [comment]
I am new to this codebase, but I have some, er, rusty experience with Rust. If someone has ~1h to spare, I'm interested in pairing to add this flag.

**Comment by allenap** [comment]
20c83e14e031328a3ca31b389cc3606a0e90a087 has argument parsing. A slightly tricky question is how does `-d` behave in relation to `--tree`, `--recursive`, etc. My approach is to say it conflicts and sidestep the question. The data model in `Flags` does not prevent such impossible states, however.

**Comment by meain** [comment]
Hey @allenap , you can ping me if you need help with the codebase.

What I am thinking is we could probably just add another value for `Display` flag here https://github.com/Peltoche/lsd/blob/c4505e61f8626e1b5b2aab88b923f8e0381b2a05/src/flags.rs#L133.
Something like `DirOnly` maybe.

And we could check for the flag and get only the directory inside this function https://github.com/Peltoche/lsd/blob/c4505e61f8626e1b5b2aab88b923f8e0381b2a05/src/meta/mod.rs#L43.
