### ISSUE TITLE
Support hyperlink rendering

### ISSUE THREAD

**Issue by pothos** [Peltoche/lsd#192]
The `--hyperlink` option for `ls`¹ is allows to open a document/folder with the default (GUI) application by using Ctrl+click in various terminals.
It would be nice to have this in lsd.
See here for more info: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

¹ http://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=799bac0d06cfabe9491498727308df8d1aca6d98

exa issue: https://github.com/ogham/exa/issues/396

**Comment by Peltoche** [comment]
Hi @pothos

Thanks for the proposition. Personally I don't see the when this feature could be used (a filename with a link ??) but if someone needs it let's go for it. At the moment I don't have the time to write new features but I would review a PR with pleasure it you want to make one.

**Comment by xenopeek** [comment]
Running `ls --hyperlink` in any VTI based terminal lets you ctrl+click any file in the `ls` output to open it with its default filetype handler (or open the link through context menu). i.e., ctrl+click a text file opens the file in your text editor, ctrl+click a directory opens the directory in your file manager and so on. Quite handy, try it out.

**Comment by KSXGitHub** [comment]
I have made [a pull request](https://github.com/Peltoche/lsd/pull/354) for initial support. But I am way too tired to fix any remaining issue. <sub>Seriously, reading this codebase is like traversing a labyrinth</sub>

**Comment by ppwwyyxx** [comment]
The implementation of hyperlink support in #642 does not match the recommendation in the OSC8 spec here https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#file-uris-and-the-hostname that suggests hostname to be included in the hyperlink. This is what `ls --hyperlink` does as well.
