### ISSUE TITLE
Option to hide realpath of a symlink

### ISSUE THREAD

**Issue by runeimp** [Peltoche/lsd#193]
Firstly, love this update to `ls`. Thank you for creating it!

Now the one issue I have is that my output is wrapping a lot when I do a long list of a directory with many symlinks. This is primarily due to the automatic display of where the symlink points to. The mode column and color coding are more than enough information regarding symlinks 99.9% of the time for me. And when it's not I have `realpath`, `readlink`, etc. It's often fine when i've got the full terminal width but that is not often the case for me when using KiTTY or tmux, etc. Any chance we could get an option to disable the symlink point to info? 👼

**Comment by Peltoche** [comment]
Hi @runeimp ,

It could be an interesting feature indeed. It would be useful for some future features too. At the moment I don't have time to spend on lsd but it's an easy feature to do so you can make a pull request with this feature, i would review it with pleasure.

**Comment by meain** [comment]
@runeimp @Peltoche 

This PR could probably solve this issue.
https://github.com/Peltoche/lsd/pull/178

You could say something like

```
lsd -l --blocks permission,user,group,size,date,namewithoutsymlink
```

> I am still deciding on the value `namewithoutsymlink`

**Comment by meain** [comment]
Oh, wait. I think there is a way to solve the  issue with name `namewithoutsymlink`.

We could have a flag like `--no-symlink` which can be then used by PR https://github.com/Peltoche/lsd/pull/178 to decide between the both.

@runeimp Feel free to take a shot, otherwise I think I could add that in along with my PR.

**Comment by runeimp** [comment]
@meain Go for it. I was going to take it on thinking this was in Python for some reason. I'm pretty good with Python. But realized it's Rust which I'm barely just getting into.  👼

**Comment by meain** [comment]
@runeimp You can now use `--no-symlink`
