### ISSUE TITLE
Icons render as  on MacOS

### ISSUE THREAD

**Issue by bennytheshap** [Peltoche/lsd#199]
## Expected behavior
According to the documentation, filenames should be preceded by icons indicating whether the directory entry is a file, folder, etc. 

## Actual behavior
On my Mac (running latest Mojave), in both Terminal and iTerm, and regardless of terminal font selected, all icons render as a box with a square inside: . Here is a screenshot. 

<img width="930" alt="Screen Shot 2019-05-20 at 6 14 56 PM" src="https://user-images.githubusercontent.com/122056/58059702-4c92a580-7b2b-11e9-80d5-d2ca7f0ce18f.png">

**Comment by wawrencelu** [comment]
Same here. Running 10.13.6 on iTerm.

**Comment by schu34** [comment]
same on 10.14.4 and iterm

**Comment by crystalneth** [comment]
Instructions say:

> Install the patched fonts of powerline nerd-font and/or font-awesome. Have a look at the Nerd Font README for more installation instructions. Don't forget to setup your terminal in order to use the correct font.

After installing nerd-font with brew, I'm not sure what the "correct font" is.

**Comment by schu34** [comment]
Totally missed that part of the instructions. I got it working by installing nerd-font with brew and then using Hack Nerd Font in iTerm

**Comment by bennytheshap** [comment]
Thank you!

**Comment by furey** [comment]
For iTerm2 on macOS, my full install process was as follows…

### 1. Install LSD

```bash
brew install lsd
```

### 2. Install Homebrew Cask Fonts

```bash
brew tap homebrew/cask-fonts
```

### 3. Install Hack Nerd Font

```bash
brew cask install font-hack-nerd-font
```

### 4. Configure iTerm2 Profile Text Font

`iTerm2 > Preferences > Profiles > Text > Non-ASCII-Font > Change Font`

<img width="1286" alt="Screen Shot 2019-05-21 at 12 36 00 pm" src="https://user-images.githubusercontent.com/1914481/58064366-186bc300-7bc5-11e9-8d55-f21815c6c61d.png">

Once setup correctly, you'll see your file/directory icons like so:

<img width="641" alt="Screen Shot 2019-05-21 at 12 40 30 pm" src="https://user-images.githubusercontent.com/1914481/58064496-b2cc0680-7bc5-11e9-8aa8-0e091ad8adc5.png">

Hope this helps if anyone else gets stuck.

Cheers!

🤓👍

**Comment by Peltoche** [comment]
Hi @furey ,

Big thanks for your steps and screens :heart: . This will go directly into the documentation!

**Comment by taylorjason** [comment]
Very helpful, thanks!  Has anyone been able to make this work in Hyper?

**Comment by sfdye** [comment]
Please, this needs to go into the documentation for MacOS setup.

**Comment by benjefferies** [comment]
@taylorjason I've just been playing around in hyper and have just resolved it. 

You'll need to follow steps 1, 2, 3 in https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334 and then for step 4 edit .hyper.js and update the fontFamily to look like

```
fontFamily: 'Menlo, "Hack Nerd Font", "DejaVu Sans Mono", "Lucida Console", monospace',
```

**Comment by taylorjason** [comment]
@benjefferies Thanks for the info. I tried that same thing but no luck. I verified I have the latest stable release of Hyper.

**Comment by benjefferies** [comment]
Do you have the font installed? You can find out by running `system_profiler SPFontsDataType|grep "Hack Nerd Font"` and you should see a similar output

```
system_profiler SPFontsDataType|grep "Hack Nerd Font"
Family: Hack Nerd Font
Family: Hack Nerd Font
Family: Hack Nerd Font
Family: Hack Nerd Font
```

**Comment by taylorjason** [comment]
I do have it installed. I installed with Homebrew and confirmed with font book.

**Comment by tnorthcutt** [comment]
I just [submitted a PR](https://github.com/Peltoche/lsd/pull/234) to link to @furey's super helpful comment in the readme 👍

**Comment by rainoxu** [comment]
I met the same problem with it , thanks!

**Comment by breezedancer** [comment]
thanks!

**Comment by kyrelldixon** [comment]
> ```shell
> brew cask install font-hack-nerd-font
> ```

The `brew cask install` step resulted in the error `Error: Unknown command: cask` because the `brew cask` syntax has been deprecated. I used `brew install --cask font-hack-nerd-font` instead.

**Comment by msr8** [comment]
@kyrelldixon How did you set the text though? I cannot find an option to select separate text for non-ascii characters

**Comment by zwpaper** [comment]
Hi @msr8 , looks like you are using the apple terminal, I also did not find the option for `non-asicii` characters, so maybe you can change the font directly, `Nerd font` works perfectly for both `ascii` and `non-ascii` characters.

or, If you would like to keep the font for `ascii`, maybe you can try `iTerm2`

**Comment by MRX-IOS** [comment]
hi @msr8 you have to change your font from "Lucida Console 13 pt" to "Hack Regular Nerd Font Complete 11"

**Comment by LaBiXiaoChen** [comment]
Thanks
