### ISSUE TITLE
ENABLE_VIRTUAL_TERMINAL_PROCESSING not set on Windows

### ISSUE THREAD

**Issue by lzybkr** [Peltoche/lsd#201]
## Expected behavior
When running `lsd.exe` on Win10 from `cmd.exe` - I shouldn't see any VT escape sequences.

## Actual behavior
The listing looks a lot of random garbage because VT escape sequences are not being processed.

`lsd` should set the flag ENABLE_VIRTUAL_TERMINAL_PROCESSING via [SetConsoleMode](https://docs.microsoft.com/en-us/windows/console/setconsolemode) (or'ing in the current mode).

**Comment by lzybkr** [comment]
Maybe this is fixed in https://github.com/Peltoche/lsd/pull/195.

**Comment by rivy** [comment]
Yes, I believe so; with that PR, color works for my Windows 10 machines.

There is a still a small bug that I hope ansi-term will fix if STDOUT is redirected but STDERR is not (see <https://github.com/ogham/rust-ansi-term/pull/50>).

**Comment by Peltoche** [comment]
Hi!

I merge #195 ASAP.

**Comment by rivy** [comment]
@lzybkr , is this fixed for you with the #195 merge ?

**Comment by lzybkr** [comment]
Confirmed fixed.
