### ISSUE TITLE
No colors and no icons :(

### ISSUE THREAD

**Issue by benlieb** [Peltoche/lsd#202]
![image](https://user-images.githubusercontent.com/634562/58071442-8d051a00-7b51-11e9-8369-b7287363b9db.png)

What am I missing. These instructions could be much clearer. I followed the "don't forget" advice and attempted to install the Nerd Fonts, but it's a similarly opaque installation process. So frustrating the number of projects out there without clear documentation. Jumping ship.

**Comment by MultifokalHirn** [comment]
<img width="302" alt="Screenshot 2019-05-21 at 12 22 14" src="https://user-images.githubusercontent.com/7870758/58088505-1d2f7780-7bc3-11e9-938c-22c5aa8f1949.png">
In case only some fonts work, documentation on that would be great as well!

**Comment by kelvinji2009** [comment]
+1

**Comment by maximevince** [comment]
try 
$ which lsd
to see if the actual binary lsd is called

**Comment by Peltoche** [comment]
Hi!

The documentation needs some improvements indeed, but saying "the documentation is not clear" doesn't help much to improve it. 

Can you specify a little what kind of steps you think is missing? Where are your pain points?

**Comment by Peltoche** [comment]
By curiosity, do you have zsh as shell? #213 could explain your issue. You can check this by running `lsd --version`

**Comment by ilaskaev** [comment]
Using Hyperterm, running `zsh` on `wsl`, running into a similar issue but with colors only.

![ColorIssue](https://user-images.githubusercontent.com/16270230/58100924-9e2f4480-7bac-11e9-8871-573658507671.PNG)

**Comment by MultifokalHirn** [comment]
iterm, both zsh and bash, font: Fira Code, lsd --version: lsd 0.14.0

<img width="408" alt="Screenshot 2019-05-21 at 15 48 47" src="https://user-images.githubusercontent.com/7870758/58101491-0c412f00-7be0-11e9-9c71-528cd394e93a.png">

**Comment by Peltoche** [comment]
Hi @MultifokalHirn ,

Can you follow the steps from https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334 and give us the output please?

I will soon add it to the documentation.

**Comment by benlieb** [comment]
I found the first issue was that somehow long ago lsd was already an alias I might have used for something 10 years ago. Sorry I was so grumpy. Some days I feel like I spend the majority of my time forced to use libraries with little to no documentation. Yesterday was an extreme case. (Before I got to lsd...)

Now working on those fonts...

**Comment by MultifokalHirn** [comment]
@Peltoche 
Using this font fixed it. Maybe add to the readme that this font is required. Some people really like their font and might then already know that this package is not for them.
Thank you for your fast support! Have a great day! :)

**Comment by Peltoche** [comment]
If everybody is ok I close this issue. Feel free to reopen it if needed.
