### ISSUE TITLE
--group-dirs first is ignored on --tree

### ISSUE THREAD

**Issue by windware-ono** [Peltoche/lsd#205]
version 0.14.0

## Expected behavior
Directories should come first with `--group-dirs first` under `--tree`.

## Actual behavior
Behaves as if `--group-dirs first` is ignored.

**Comment by Peltoche** [comment]
Hi!

After some tests I'm not able to reproduce the bug. It seems that the two flags works well together. Do you have some examples or better, a simple way to reproduce?

**Comment by windware-ono** [comment]
I installed it via homebrew and did a simple test as follows.
```
brew install lsd
mkdir test
cd test
mkdir a
touch b
lsd --group-dirs first --tree
```

This gives me a result in the order of `b` and then `a`.
I'm assuming `--group-dirs first` would bring the directories above files.

**Comment by Peltoche** [comment]
Arf! I was testing from master....

After checking it seems that it's already solved by https://github.com/Peltoche/lsd/commit/0dbc3b3a6286a8310bf78f35b0f6170b8507eabe. It will be available into the next release which should be soon.

**Comment by windware-ono** [comment]
Nice!
