### ISSUE TITLE
no manpage

### ISSUE THREAD

**Issue by maximevince** [Peltoche/lsd#210]
## Expected behavior
man lsd shows a manpage

## Actual behavior
no manpage available

**Comment by Peltoche** [comment]
Hi @maximevince,

This seems an important feature indeed and it should be easily implemented with `clap`. I can handle the snap package but I don't have the ownership for the other distributions system like pacman and co.

**Comment by meain** [comment]
We have a manpage now. It does not have a lot of content as of now, but is at lest available in the build artifacts.
