### ISSUE TITLE
Feature Request: --exclude option for directories like node_modules or vendor ?

### ISSUE THREAD

**Issue by acidjazz** [Peltoche/lsd#215]
This would be sweet in combination with `--tree`

**Comment by Peltoche** [comment]
Hi @acidjazz ,

This seems to be a duplicate of #218 . I close this issue in order to keep the discussions in one topic

**Comment by AndydeCleyre** [comment]
@Peltoche I think this should be reopened, as exclude options (especially for `--tree`) are just as useful outside the scope of VCS-tracked folders, and different exclusions on the same root path may be useful for different purposes.

If wildcard patterns are accepted, using the flag `-I` would be a nice gift for those of use who

```bash
[[ "$(command -v lsd)" ]] && alias tree="lsd --tree" || alias tree="tree -C"
```
