### ISSUE TITLE
No colors in tmux

### ISSUE THREAD

**Issue by mashehu** [Peltoche/lsd#216]
## Expected behavior
`lsd` should give me a colorized output, the same way `colorls` and `ls --color` does.
## Actual behavior
![Screenshot 2019-05-22 10 34 12](https://user-images.githubusercontent.com/6169021/58159612-2bda6500-7c7d-11e9-8087-d2487fa09a7f.png)

My setup is iTerm2 and xterm colors enabled in the tmux.conf

**Comment by AndydeCleyre** [comment]
FWIW colors are working fine on my konsole+tmux setup, and this is the only color-related thing I've got in `.tmux.conf`:

```bash
set -ga terminal-overrides ',xterm-256color:Tc'
```

**Comment by mashehu** [comment]
Thanks @AndydeCleyre, that resolved it for me.
