### ISSUE TITLE
directory listing behavior

### ISSUE THREAD

**Issue by kascote** [Peltoche/lsd#219]
I had a couple issues, not sure if break it on different tickets or only one.

using --directory-only shows other files too: 

```
touch testfile
mkdir directory
mkdir .directory2

```
![Screenshot from 2019-05-23 12-43-36](https://user-images.githubusercontent.com/9757/58266699-96140800-7d58-11e9-9d00-78b7fa375b42.png)

why show regular files and add a ```~``` after the timestamp ?

![Screenshot from 2019-05-23 13-09-36](https://user-images.githubusercontent.com/9757/58268597-1425de00-7d5c-11e9-8e01-c7e5024236e5.png)

show the dot-directory under the current directory and the directories under this path (I think this is related to . and .. )

![Screenshot from 2019-05-23 13-08-50](https://user-images.githubusercontent.com/9757/58268608-1720ce80-7d5c-11e9-80c2-5190a03fe667.png)

shows only the parent directory, I think this is related to .

on ls there isn't a way to list dot files/directories or only directories (without using some hacky alias or something). for that reason I don't show how this work on ls

-----

I can't use ```--all``` with ```--directory-only```, there is a way to list only directories that start with a dot ?

-----

on version 0.14.0 I had this alias that showed only the dot files (is a bit hacky but worked)

```alias ld="ls .* --recursive --depth 0"```

on version 0.15.0 stop working, don't show anything

-----

if lsd add helpers like ```--directory-only``` could be cool to support dotfiles, I know that dotfiles are complex by definition (I mean . and .. )

**Comment by Peltoche** [comment]
Hi @kascote , thanks for the reports

For the `--all` this is clearly a bug inside the flag rules. I will fix that asap.

For the `.` and it seems that the dot is translated into the current folder name. This is not the expected behavior indeed. I will look into it too.
