### ISSUE TITLE
lsd *.gz different to ls *.gz

### ISSUE THREAD

**Issue by mkevac** [Peltoche/lsd#220]
```
marko@marko:~/tmp $ /usr/bin/ls *.gz
boost_1_59_0.tar.gz  deleted.txt.gz  LuaJIT-2.0.4.tar.gz  mysql-5.6.34.tar.gz  nginx-1.9.11.tar.gz  rsync-3.1.2.tar.gz	syncthing-linux-amd64-v0.14.52.tar.gz
marko@marko:~/tmp $ lsd *.gz
marko@marko:~/tmp $ lsd *gz
```

lsd behaviour is different from ls behaviour when using globs

**Comment by meain** [comment]
I am not able to reproduce the issue on my end.

Could you tell me what is the result of 

```
lsd --version
```

**Comment by asbjorn** [comment]
Hi.

I also experience the same issue.
```
$ lsd --version
lsd 0.15.0
```

**Comment by martinlindhe** [comment]
Seeing same issue with lsd 0.15.0 here on both macOS and Fedora.

lsd 0.14.0 worked correct on macOS and Fedora.

Reprod:
```
mkdir x && cd x
touch file.toml
lsd *.toml
```
0 results, expected 1 result

**Comment by themilkman** [comment]
Same here

```
$ uname -a
Linux tux01 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:  Ubuntu 18.04.2 LTS
Release:  18.04
Codename: bionic

$ ls *deb
-rw-rw-r-- 1 ee ee 32M Jul  7  2016 wkhtmltox_0.12.3_amd64.deb

$ lsd *deb

$ lsd --version
lsd 0.15.0

$ 
```

**Comment by allenap** [comment]
If a non-directory is given as a command-line argument, lsd is not listing it.

**Comment by meain** [comment]
Hmm, I was able find out the issue. It is a regression from commit 75648b79b08bd52b9ef70fffdd914c9fcac8b75a from PR https://github.com/Peltoche/lsd/pull/196. I will take a look into it pretty soon.

**Comment by allenap** [comment]
@meain I've had a go at fixing it in #224.

**Comment by Peltoche** [comment]
This is a big issue, I release the 0.15.1 asap.

**Comment by Peltoche** [comment]
The 0.15.1 have been releases. Can you confirm that everything works well now?

**Comment by martinlindhe** [comment]
I can confirm 0.15.1 works correctly on Fedora and macOS, thanks for quick resolution!
