### ISSUE TITLE
Files and directories all show up using same color

### ISSUE THREAD

**Issue by khughitt** [Peltoche/lsd#225]
## Expected behavior

Files and directories to be colored according to type.

## Actual behavior

Files and folders are all displayed using the same color (foreground / white).

![lsd_color_bug_example](https://user-images.githubusercontent.com/125001/58337973-f8cad980-7e14-11e9-8d04-0203e6096477.png)

## System info

- Arch Linux
- lsd 0.14.0 (installed via pacman)

**Comment by Peltoche** [comment]
Hi @khughitt , thanks for the report.

First, can you update to the 0.15.1 in order to see if the bug is still here?

**Comment by khughitt** [comment]
I checked and the issue appears the same with 0.15.1.

Upon further inspect, it seems the issue might be specific to [termite](https://github.com/thestinger/termite) -- the output for lsd appears fine in xterm, but is lacking color as above when I use it in termite, even with the default configuration.

**Comment by JPUnD** [comment]
I'm having the same issue, after adding `export TERM="termite"` to my .zshrc file in order to fix an unrelated bug, i lost the folder/file colors too. Previously it worked out fine even in termite.

**Comment by Peltoche** [comment]
Curious... I haved tried on termite v15 and it works well for me.

That said my `TERM` env variable value is `xterm-termite`. You should try with this value.

**Comment by khughitt** [comment]
My term is set to `xterm-termite` and issue still appears in v15.

Can you think of any other factors that might be influencing the output?

I doubt this is helpful because of differing implementations, but just as a note, [colorls](https://github.com/athityakumar/colorls) does handle colors correctly in my case.

**Comment by Peltoche** [comment]
Do you have an env variable `LS_COLORS` or `LSCOLORS`? This override the default colors

**Comment by khughitt** [comment]
I do! And indeed, unsetting them fixed the issue. Going to close the issue. Good catch!

**Comment by khughitt** [comment]
FYI - in case anyone else runs into this issue, oh-my-zsh sets `LS_COLORS` and `LSCOLORS` by default. There appears to be a configuration option to control this behavior, although it didn't work for me.

Instead, simply add something like this near the bottom of your `~/.zshrc`:

```
unset LSCOLORS
unset LS_COLORS
```

**Comment by guidiamond** [comment]
> FYI - in case anyone else runs into this issue, oh-my-zsh sets `LS_COLORS` and `LSCOLORS` by default. There appears to be a configuration option to control this behavior, although it didn't work for me.
> 
> Instead, simply add something like this near the bottom of your `~/.zshrc`:
> 
> ```
> unset LSCOLORS
> unset LS_COLORS
> ```

Worked for alacritty term (i was using urxvt before and didn't come across this problem)
