### ISSUE TITLE
--tree depth option

### ISSUE THREAD

**Issue by curliq** [Peltoche/lsd#240]
When doing `ls --tree` it might print to an unnecessary depth that I'm not interested in seeing, adding a lot of clutter.

Would be cool to have something like `ls --tree 3` to print only 3 directories deep, if there were more directories it wouldn't expand them.

Example:

What happens:
```
ls --tree
├──   project-android.iml
├──   fastlane
│  ├──   Appfile
│  ├──   Fastfile
│  ├──   metadata
│  │  └──   android
│  │     └──   en-US
│  │        ├──   changelogs
│  │        │  ├──   175.txt
│  │        │  ├──   181.txt
```
What would be cool:
```
ls --tree 3
├──   project-android.iml
├──   fastlane
│  ├──   Appfile
│  ├──   Fastfile
│  ├──   metadata
│  │  └──   android
│  │     └──   en-US     
```

**Comment by meain** [comment]
@curliq 
You can pass in a depth parameter which will limit it to 3 levels deep.

`ls --tree --depth 3` should work.

**Comment by meain** [comment]
I hope that fixed your issue. Closing the issue for now.
Feel free to reopen the issue if that did not help.

**Comment by curliq** [comment]
Yep that was exactly what I wanted, thanks.
