### ISSUE TITLE
Explicitly listing a symlink shows only the target, without the link name

### ISSUE THREAD

**Issue by elpres** [Peltoche/lsd#241]
When you call `lsd` on a directory without specifying any patterns, symlinks are shown as expected, with an arrow pointing from the link name to the target:

```
% lsd -l
.rw-r--r-- user users 0 B Wed Jun 26 11:17:09 2019 file       
lrwxrwxrwx user users 4 B Wed Jun 26 11:17:17 2019 link ⇒ file
```

But if you use any kind of patterns to narrow down the list, the command only shows the target of symlinks:

```
% lsd -l *        
.rw-r--r-- user users 0 B Wed Jun 26 11:17:09 2019 file
.rw-r--r-- user users 0 B Wed Jun 26 11:17:09 2019 file
```

It would be useful to see the name of the link in the second case as well.

**Comment by runeimp** [comment]
I just noticed this behavior as well on my two main systems. An 2012 iMac and 2018 MacBook Pro. Both running Mojave. OS may not matter for this bug but @elpres system(s) are you seeing this on?

**Comment by elpres** [comment]
@runeimp Linux
