### ISSUE TITLE
Feature request: date time format option

### ISSUE THREAD

**Issue by Phuker** [Peltoche/lsd#242]
It would be better if we can set an option like `--date-format='%Y-%m-%d %a %H:%M:%S'`
Thank you!

**Comment by Seirdy** [comment]
Seconding this; [ogham/exa](https://github.com/ogham/exa) supports `--time-style=<iso, long-iso, full-iso>` which I find extremely useful. Example with `--time-style=iso`:

    Permissions Size User     Date Modified Name
    .rw-r--r--  4.1k username 07-12 10:52   .zshrc

**Comment by bknowles** [comment]
There is apparently no `--time-style=ciso` option that I can find for `exa`, and to my eyes they get the actual formatting wrong in each of the styles they offer.  I understand using spaces to provide easy column definitions that can be parsed, but separating the timezone from the time by a space character really isn't a good idea.

I would definitely like to see some configurability here.  Allowing `strformat()` options would seem to be the easy solution, and you could provide some good defaults.

**Comment by dvvvvvv** [comment]
#302 
The full request that contains the feature.

**Comment by dvvvvvv** [comment]
@Peltoche feature merged in #302. please close this issue

**Comment by meain** [comment]
You can now pass datetime format to `--date` as of #302, thanks to @dvvvvvv .
