### ISSUE TITLE
Wrong output when using custom folder icon

### ISSUE THREAD

**Issue by EppO** [Peltoche/lsd#243]
## Expected behavior
lsd should display correctly `Icon\r` file along with other files in the same folder.

## Actual behavior
When using a custom folder icon (presence of `Icon\r` in the directory), any folder which name is sorted alphabetically _AFTER_ `Icon\r` will mess up the output of `lsd` command (`lsd -la` still works correctly though).
<img width="698" alt="Screen Shot 2019-07-02 at 22 06 37" src="https://user-images.githubusercontent.com/6111/60613183-5baa7b80-9d98-11e9-9d59-8b67f13ed63a.png">

**Comment by thammin** [comment]
`Icon\r` contains a CR character `r` which make it displays improperly.
I'm not sure about the correct behavior but `ls` is displaying something like this `Icon\n` -> `Icon??`

**Comment by EppO** [comment]
Good old `ls` displays `Icon?`

<img width="650" alt="lsd-ls-diff" src="https://user-images.githubusercontent.com/6111/60674047-388ad500-9e47-11e9-89dc-fb2f2323ef5b.png">

**Comment by EppO** [comment]
looks like it's fixed in 0.16.0, I don't get this issue anymore, thanks!
