### ISSUE TITLE
Gradle files have the Android icon

### ISSUE THREAD

**Issue by curliq** [Peltoche/lsd#247]
`.gradle` files are displayed with Android's logo instead of Gradle's logo.

<img width="140" alt="image" src="https://user-images.githubusercontent.com/15181917/60682601-cb4d6300-9e8b-11e9-9f94-f210d9ccb1b7.png">

**Comment by Peltoche** [comment]
Hi @curliq ,

The gradle icon doesn't seems to be available inside the nerd-font icons
