### ISSUE TITLE
Support for non-bold bright colours

### ISSUE THREAD

**Issue by s-hamann** [Peltoche/lsd#248]
lsd supports lots of ANSI codes, but apparently not non-bold bright colours (`90`-`97`).

My `$LS_COLORS` contains `*.tar=91`, which is the ANSI code for bright red from the terminal's 16 colour palette. This works fine with GNU ls, i.e. `.tar` files are displayed in bright red but not bold text. lsd does not emit any ANSI colour sequence and my `.tar` files are displayed in regular foreground colour.

**Comment by eliminmax** [comment]
I ran into this issue on version 0.20.1, as installed from both the .deb package and cargo

**Comment by meain** [comment]
Ah, my bad. This actually still seems to be an issue.

**Comment by meain** [comment]
ref: https://github.com/sharkdp/lscolors/issues/39
