### ISSUE TITLE
Problem with SUID/SGID file

### ISSUE THREAD

**Issue by garyparrot** [Peltoche/lsd#251]
I set SUID(set-user-id) for a file, the result of `lsd` is not correct.

![image](https://user-images.githubusercontent.com/39105714/61645545-6aba8480-acd9-11e9-903a-8cb43d8206ef.png)
`lsd` says SGID flag is on, but `stat` and `ls` don't agree with that.

![image](https://user-images.githubusercontent.com/39105714/61645717-d7ce1a00-acd9-11e9-8368-8be154d866ed.png)
Now if I set only SGID on, the result is unexpected too.

**Comment by meain** [comment]
Should be fixed with https://github.com/Peltoche/lsd/pull/301.
