### ISSUE TITLE
Broken icons for most file types

### ISSUE THREAD

**Issue by Mitsunee** [Peltoche/lsd#253]
Here's an example image with (most) filenames blanked out:
![image](https://user-images.githubusercontent.com/19474909/61850455-ad848400-aeb4-11e9-856e-6ff26c5107a6.png)

I have tried:
- updating ls deluxe
- updating fonts-powerline by uninstalling the package and reinstalling from the github repo
- changing to different fonts (with powerline suffix)

I'm on Kubuntu 19.04 using bash in Terminator and the Monospace Regular font, tho other fonts showed the same result. In the profile settings Terminator is set to use UTF-8 encoding.

For reference the following icons not seen above do show up correctly: JPG (same as PNG), MOV/MP4/MKV, ZIP/RAR, TXT, INI/BAT. Some filetypes produce a superscript-looking tilde `~` symbol. MP3 gets a symbol that looks like `fi`.

Here are my locale settings as well:

```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by Peltoche** [comment]
Hello @Mitsunee ,

You need to install and setup your terminal with [nerd-font](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md). Regular font doesn't contains the required icons. You can find more informations into the readme
