### ISSUE TITLE
Better performance documentation?

### ISSUE THREAD

**Issue by bknowles** [Peltoche/lsd#257]
## Expected behavior
The documentation provides details of running the command to get performance comparison against other tools, but also provides information regarding the platform those tests were run on, and collects information for a variety of platforms and systems.

## Actual behavior
The documentation shows using the command `hyperfine --warmup 10 'lsd -la /etc/*' 'colorls -la /etc/*' 'exa -la /etc/*'` to provide some performance numbers, but it doesn't give us any idea of what kind of platform this ran on, or any other details.

For example, I found quite different results on my Macbook Pro laptop (model="MacBookPro13,3", Processor="Intel Core i7", Processor speed="2.6 GHz", Total number of cores=4, Total RAM=16GB, macOS version=10.14.6):

```
Benchmark #1: lsd -la /etc/*
  Time (mean ± σ):      41.2 ms ±   3.4 ms    [User: 24.4 ms, System: 13.5 ms]
  Range (min … max):    37.7 ms …  50.7 ms    65 runs
 
Benchmark #2: ls -laG /etc/*
  Time (mean ± σ):      27.0 ms ±   2.6 ms    [User: 9.5 ms, System: 15.3 ms]
  Range (min … max):    22.6 ms …  33.9 ms    105 runs
 
Benchmark #3: exa -la /etc/*
  Time (mean ± σ):      25.7 ms ±   2.5 ms    [User: 19.5 ms, System: 25.3 ms]
  Range (min … max):    21.8 ms …  34.3 ms    112 runs
 
Summary
  'exa -la /etc/*' ran
    1.05 ± 0.14 times faster than 'ls -laG /etc/*'
    1.60 ± 0.20 times faster than 'lsd -la /etc/*'
```
And the contents of `out.md` are:

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `lsd -la /etc/*` | 41.2 ± 3.4 | 37.7 | 50.7 | 1.6 |
| `ls -laG /etc/*` | 27.0 ± 2.6 | 22.6 | 33.9 | 1.1 |
| `exa -la /etc/*` | 25.7 ± 2.5 | 21.8 | 34.3 | 1.0 |

**Comment by bknowles** [comment]
So, while I actually prefer the output that is provided by `lsd`, both with regards to color and overall formatting of information, the tests above show that the macOS-provided version of `ls` and the version of `exa` that is installed both perform better than `lsd`.

IMO, if you're going to offer performance information, you should offer as much as you reasonably can, and you should be open about your own weaknesses in this area.

OTOH, I believe that you can make a strong case for increased value provided to the end user, without necessarily making a big deal about performance.

**Comment by Peltoche** [comment]
Hi @bknowles ,

Totally agree with all you points. At the beginning it was kind of interesting because lsd was a rewrite of colorls and so a comparison was interesting even if it was not precise. Today, I don't think there is any needs to keep the benchmarks because there is no more comparison with colorls.

If no one is opposed to it I will remove them.
