### ISSUE TITLE
How do I install the binaries?

### ISSUE THREAD

**Issue by timothy3001** [Peltoche/lsd#260]
## Expected behavior
Using `lsd` file as binary via `./lsd` 

## Actual behavior
I can't run LSD via `./lsd`

Or install it? I don't know.

Would love to use it but the description of the installation is pretty much useless, at least for newbies. I thought `lsd` was a binary file, which can be just executed, but it is not recognized as file even. I get the error `-bash: ./lsd: No such file or directory`.

**Comment by Peltoche** [comment]
Hi @timothy3001,

Sorry for the delay. If you have installed lsd with you package manager the `lsd` (without `./`) command should work.
