### ISSUE TITLE
v0.16.0 is adding extra lines in long listing mode

### ISSUE THREAD

**Issue by daiyam** [Peltoche/lsd#264]
Hi,

Since v0.16.0, when long listing, lsd is adding extra lines when a single line is wider that the console's width.

## behavior of lsd v0.15.1
![Screenshot](https://user-images.githubusercontent.com/587742/62723027-02291280-ba10-11e9-894d-14870339dad3.png)

## behavior of lsd v0.16.0
![Screenshot](https://user-images.githubusercontent.com/587742/62723059-13721f00-ba10-11e9-932b-954ea387e3a3.png)

**Comment by meain** [comment]
This has been fixed by https://github.com/Peltoche/lsd/pull/289
Will be available in the next release.
