### ISSUE TITLE
Feature: only display icons when using --long format

### ISSUE THREAD

**Issue by JrCs** [Peltoche/lsd#267]
Hi,
it will be great to add a new optional value for the --icon option to only display icon if the --long format is used.
It will allow not to clutter the display when not using the --long format.

A new value (like **long**) for the --icon flag will only display icons if --long format is used.

**Comment by Peltoche** [comment]
Hi @JrCs ,

I don't think that a flag for the specific case is a good idea. An another alternative would be to separate the icons from the name and make a new `icon` block. This would let you compose you `-l` option like you want.

**Comment by Peltoche** [comment]
Another solution, you create an alias `lsd -l='lsd -l --icon=never`.

I close this issue but don't hesitate to reopen it if needed
