### ISSUE TITLE
unexpected line breaks

### ISSUE THREAD

**Issue by sdicke** [Peltoche/lsd#269]
## Expected behavior
The complete available emulated TTY width should be used, maybe a line break should be inserted at the position of a white space character for better readability.

## Actual behavior
The line breaks before the maximal line length. For example: With a emulated TTY with a line length of 265 characters, the output breaks sometimes after lesser than 100 characters.

![abc](https://user-images.githubusercontent.com/23293203/63975408-452a5300-caaf-11e9-9315-cc3e115bea34.png)

**Comment by meain** [comment]
Related PR: https://github.com/Peltoche/lsd/pull/265.
