### ISSUE TITLE
Request: Implement -i (--inode) to include inode numbers

### ISSUE THREAD

**Issue by AndydeCleyre** [Peltoche/lsd#276]
## Expected behavior
```bash
touch README.rst
ls -i README.rst
```
`53850413 README.rst`
```bash
busybox ls -i README.rst
```
`53850413 README.rst`
```bash
lsd -i README.rst
```
`53850413  README.rst`
```bash
ls -li README.rst
```
`53850413 -rw-r--r-- 1 andy andy 0 Sep  4 15:56 README.rst`
```bash
busybox ls -li README.rst
```
`53850413 -rw-r--r--    1 andy     andy             0 Sep  4 15:56 README.rst`
```bash
lsd -li README.rst
```
`53850413 .rw-r--r-- andy andy 0 B Wed Sep  4 15:56:36 2019   README.rst`

## Actual behavior
`-i` not implemented.

Both GNU Coreutils and BusyBox support `-i` to show inode numbers, and Coreutils additionally supports the equivalent `--inode`. `-i` should be sufficient, and handy for identifying hard links.

**Comment by Peltoche** [comment]
Hi @AndydeCleyre,

This look a great feature indeed. I guess it can be integrated as a block. I don't have time to work on this feature but if you want to make a PR we would be happy to review it.

**Comment by AndydeCleyre** [comment]
If it were implemented as a block, would that preclude the following behavior?

```bash
lsd -i
```
```
57011337   app.rs    57011339   core.rs     57011341   flags.rs  57011343   main.rs  57011354   sort.rs
57011338   color.rs  57011340   display.rs  57011342   icon.rs   57094940   meta
```

In other words, would we have to use the `--long`/table view to access it? In this case and in general I prefer keeping behavior close to other `ls`(-like) implementations.

**Comment by Peltoche** [comment]
I don't think it would preclude anything. It would just facilitate the `-i` integration as is only require to run an ls with the blocks `name` and `inode`.  

So `lsd -i` == `lsd --blocks inode,name`

**Comment by meain** [comment]
This is now possible with https://github.com/Peltoche/lsd/pull/296
