### ISSUE TITLE
Spacing between all lines is the same as the largest spacing

### ISSUE THREAD

**Issue by pteroctopus** [Peltoche/lsd#279]
lsd -al /usr/bin | head

Spacing between all lines is the same as the largest spacing.
Screenshot is attached.

I'm using:
Linux arch 5.2.11-arch1-1-ARCH
zsh 5.7.1 (x86_64-pc-linux-gnu)
lsd 0.16.0

![spacing](https://user-images.githubusercontent.com/16186848/64601165-bece1500-d3bc-11e9-8a2e-626d46a1424b.png)

**Comment by meain** [comment]
Same issue as #269 , closing. Will be fixed with merge of #265.
