### ISSUE TITLE
Honor $LSCOLORS environment variable

### ISSUE THREAD

**Issue by hawkw** [Peltoche/lsd#28]
Most shells have an [`LSCOLORS` or `LS_COLORS` environment variable](https://gist.github.com/thomd/7667642#file-lc_colors-md) which allows users to modify which colors are used by LS for different types and states of filesystem objects. It would be excellent if `lsd` supported this.

**Comment by hawkw** [comment]
@Peltoche I don't have a whole lot of spare time right now, but if I have a chance in the near future and nobody else has already done it, I'd be happy to. Just figured it was worth getting it on the to-do list now. :)

**Comment by sharkdp** [comment]
I have written some Rust code which parses the `LS_COLORS` environment variable for [`fd`](https://github.com/sharkdp/fd/). There is an open ticket to extract that into a separate library/crate here: https://github.com/sharkdp/fd/issues/363. Maybe this could be of use for `lsd`, too?
