### ISSUE TITLE
Folder icon size

### ISSUE THREAD

**Issue by WyRe** [Peltoche/lsd#292]
I would like to know if could be possible set a particular icon in lsd config, I'm getting tinny icons for folders as you can see

![Captura de pantalla_2019-10-29_09-34-32](https://user-images.githubusercontent.com/4059108/67750503-9ca55a80-fa2f-11e9-87ab-c1207ed47065.png)

**Comment by Peltoche** [comment]
Hi @WyRe , 

This is most probably due to a font issue. I guess you can try a different font

**Comment by WyRe** [comment]
@Peltoche

But how can I setup a different font for `lsd`?

**Comment by Peltoche** [comment]
You can change the font set by your shell or your terminal. The way to do it vary a lot depending your setup so I let you find a way to do it alone.

I

**Comment by WyRe** [comment]
Apparently the problem is that I have [nerd-font-complete](https://aur.archlinux.org/packages/nerd-fonts-complete/) installed (for polybar and powerlevel10k) but your package does require [awesone-terminal-fonts](https://www.archlinux.org/packages/community/any/awesome-terminal-fonts/) as dep. The folder icon from nerd-complete fonts is smaller, and it is interfering with present in awesome fonts. 

I don't know if I can specify in termite multiple fonts and if this could help, because terminal font has nothing to do with this glyph rendering. I've switched already the font and it keeps rendering the same glyphs.

**Comment by Peltoche** [comment]
I think that you package `nerd-font-complete` is correct and contains all the correct libraries but that's your terminal or shell setting the issue.

For example in my case I use Xterm and my corresponding configuration inside the `.Xresoources` file is: 
```
XTerm.vt100.faceName: xft:FuraCode Nerd Font:style=Retina:size=10
```

**Comment by WyRe** [comment]
I've solved using 

`DejaVuSansMono Nerd Font`

In `termite`, you were right. (I didn't know `nerd-font-complete` had a DejaVu font also)
