### ISSUE TITLE
install from latest source

### ISSUE THREAD

**Issue by breuerfelix** [Peltoche/lsd#299]
i used cargo to install lsd because i needed the -I flag and i read that this is only in the master branch and not yet released

i thought if i install it via cargo i will get the latest version but it also installs v 16

so... how to i install it from git ? there is nothing mentioned about that in the readme and i am not experienced in rust :)

btw thanks for this awesome project !

**Comment by Peltoche** [comment]
Hi @breuerfelix, 

For what I know, if you run `cargo install` it will install you the latest *tagged* version and not the latest commit. I think you can use the `--rev` option in order to fetch a specific commit. 

In you case it should give something like: 
```
cargo install --rev c4d5f5ea0b1ee9ae549438b58df79f00fa209023
```

**Comment by breuerfelix** [comment]
thanks for mentioning this !

i googled into this direction and got it working with:

```
cargo install --git https://github.com/Peltoche/lsd.git --branch master
```

i can create a PR today and add that to the readme if you like to :)
