### ISSUE TITLE
some symlinks in /usr/bin not seen

### ISSUE THREAD

**Issue by cconverse711** [Peltoche/lsd#306]
## Expected behavior
cconverse@converse:~$ ls -l /usr/bin/cc
lrwxrwxrwx 1 root root 20 May 20  2019 /usr/bin/cc -> /etc/alternatives/cc

## Actual behavior
cconverse@converse:~$ lsd -l /usr/bin/cc
cannot access '/usr/bin/cc': No such file or directory (os error 2)

**Comment by Peltoche** [comment]
Duplicate of #72
