### ISSUE TITLE
Create a Layout enum

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#31]
(This issue was originally created to respond to a display order issue but it seems it was useless. @loewenheim have proposed a great idea about a Layout enum which is not implemented yet and so the subject have changed from the original purpose.)

This option would allow to change de display direction (left-right or top-down)

**Comment by loewenheim** [comment]
I read through the linked #29, but in my tests, `lsd` currently behaves exactly like `ls` and `exa`. Am I missing something?

**Comment by Peltoche** [comment]
Hi @loewenheim ,

Nop, you'r missing nothing but the idea was to let the user the possibility to choose the display direction and so propose the same behavior than `colorls` which go sidewise.

That said I'm not sure that this feature is really necessary...

**Comment by loewenheim** [comment]
I see. In preparation for this issue, I’ve implemented an enum `Layout` that controls how the output is displayed:
```rust
enum Layout {
    Grid,
    Line,
    Long,
    Tree,
}
```
Is this of interest indepently of this issue?

**Comment by Peltoche** [comment]
What do you call `Line`?

**Comment by loewenheim** [comment]
`Line` is what the `-1` option produces.

**Comment by Peltoche** [comment]
It seems a good idea. What do you think of `OneLine` instead of `Line`? Like log format (`--oneline`).

**Comment by Peltoche** [comment]
After some reflexions I think that the `Long`  value should not be inside the layout enum. For me it is more a rule used to define which meta we should display about a file than a layout. For now the Long rule is only displayed with the `Line` (or `OneLine`) Layout but it will not be necessary the case later. For example the `exa` command is able to print the Long output with a Grid Layout: `exa -lG`.
