### ISSUE TITLE
Feature request: smaller space for mono icons

### ISSUE THREAD

**Issue by jcassee** [Peltoche/lsd#316]
When using the monospaced nerd fonts, the whitespace between icons and names is very wide. An option to reduce this space would be nice.

![Schermafdruk van 2020-01-04 02-50-31](https://user-images.githubusercontent.com/20749/71758194-019c8700-2e9d-11ea-9982-8b88680ab270.png)

**Comment by AndydeCleyre** [comment]
Is it like that for all the nerd-patched fonts? 

FWIW I use the nerd symbols, but no patching, and I don't get gaps like that:

![image](https://user-images.githubusercontent.com/1787385/73198803-b2dfb700-4101-11ea-8ed4-f1b3ad15c3ea.png)

I have font fallbacks configured via [`fontconfig/fonts.conf`](https://github.com/AndydeCleyre/dotfiles/blob/master/.config/fontconfig/fonts.conf), with a build of [Iosevka](https://github.com/be5invis/Iosevka) falling back to nerd's [Symbols](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf).

I don't know why I never see this kind of configuration recommended, but it works great for me, and makes more sense to me than splicing fonts together.

**Comment by jcassee** [comment]
@AndydeCleyre those are double-width icons. [See the wiki](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#tldr) for the difference between those and monospaced versions.

Your suggestion of using the fallback mechanism is pretty interesting!

**Comment by AlecsFerra** [comment]
Same issue using jetbrains nerd font

**Comment by meain** [comment]
We should have a fix for this in https://github.com/Peltoche/lsd/pull/469 which should land pretty soon. Closing this for now, keeping #363 as the tracking issue for this.

**Comment by jcassee** [comment]
Thanks, @meain and @OrangeFran!
