### ISSUE TITLE
[Feature Request] Any chance of adding the Windows binary to Scoop?

### ISSUE THREAD

**Issue by spencerwooo** [Peltoche/lsd#318]
Loving `lsd`, and based on what I gathered from browsing through the issues, `lsd` is indeed usable on Windows. So is there any chance adding `lsd` onto the Windows Package Manager -- [Scoop](https://scoop.sh/)?

Scoop is my personal favorite package manager on Windows. It can install command-line tools in a Unix-style manner with a simple `scoop install xxx` based on the tool's dedicated 'App Manifest' (basically a JSON file describing what to do when installing the tool). More information here: [Scoop - So What?](https://github.com/lukesampson/scoop/wiki/So-What)

The current way to install `lsd` for me is to install Rust then use Cargo to install `lsd`, which is a bit of an overkill. It would be nice to use Scoop for the installation. 🍻

**Comment by martinlindhe** [comment]
Hi, just ended up here while looking into adding lsd to scoop.

The issue preventing me from doing this today is that there is no windows release binaries here. I opened issue #330 about that. When it's resolved, I will go ahead and add lsd to scoop.

**Comment by h404bi** [comment]
The issue can be closed now.

**Comment by spencerwooo** [comment]
Thank you! @h404bi 

![image](https://user-images.githubusercontent.com/32114380/82122166-83de7580-97c4-11ea-9351-2e89177896e9.png)
