### ISSUE TITLE
Colors seems to look washed out

### ISSUE THREAD

**Issue by AkechiShiro** [Peltoche/lsd#322]
## Expected behavior

I've been using colorls but I wanted to move onto lsd as it is much faster, there is only a really minor problem that the colors are a little different (the contrast of the blue isn't the same and as certain filetype I know it is different by choice), is this intended (and also normal, the colors look a bit different than what's is shown as the default color on the github webpage of the repo) or a bug?

I doubt it is a bug, maybe it is an intended behavior, if so tell me I'll close the issue.

## Actual behavior

The `ls` command here is an alias to the `colorls` command
![lsVSlsd](https://user-images.githubusercontent.com/14914796/72852143-055a4700-3cae-11ea-8024-26617eb65d0e.png)

**Comment by meain** [comment]
The colors are default colors. You can actually change the colors which `lsd` use to display folders by setting an `LS_COLORS` variable.
