### ISSUE TITLE
"Icon?" file on MacOS hides some files

### ISSUE THREAD

**Issue by ho-oto** [Peltoche/lsd#325]
On MacOS, some applications (e.g., Dropbox, GoogleDrive) make hidden "Icon?" file to change the folder icon seen from Finder.app. These hidden files hides some files from the result of `lsd`.

I show the result on Catalina 10.15.3.

```
% lsd -V
lsd 0.16.0
% ls
Icon?   aaa     zzz
% ls -l
total 808
-rw-r--r--@ 1 hootooo  staff  0  2  4 17:42 Icon?
-rw-r--r--  1 hootooo  staff  0  2  4 17:22 aaa
-rw-r--r--  1 hootooo  staff  0  2  4 17:22 zzz
% lsd
    zzz  Icon
% lsd -l
.rw-r--r-- hootooo staff 0 B Tue Feb  4 17:22:10 2020   aaa
.rw-r--r-- hootooo staff 0 B Tue Feb  4 17:42:36 2020   Icon
.rw-r--r-- hootooo staff 0 B Tue Feb  4 17:22:12 2020   zzz
```

**Comment by meain** [comment]
This should be fixed now.
Feel free to reopen if this issue still persists.

See https://github.com/Peltoche/lsd/issues/335 for any further improvement on how it is handled.
