### ISSUE TITLE
FAQ / Configuration suggestion regarding zsh + lsd

### ISSUE THREAD

**Issue by Sherulez** [Peltoche/lsd#329]
It is not an issue just something interesting that could be indicated in the FAQ section (**?**)

I spent a good half hour trying to understand why I did not have the same colors as on the screenshots, especially the files, which appeared white and not yellow. 
Between zsh dotfiles, terminal and zsh themes etc ... it can quickly be difficult to detect where the color problem comes from.

To someone who is a dotfile veteran it may sound silly but if you use `zsh` remember to **uncomment** `DISABLE_LS_COLORS = "true"` in `~/.zshrc`

**Comment by Peltoche** [comment]
Hi @Sherulez ,

This is a good sugestion! At the moment I sadly don't have much time for open-source so I will not be able to write it but if you make a PR I will gladly review it!

I hope to see a PR from you soon :)

**Comment by Sherulez** [comment]
Sorry for the late reply.

To clarify my first message, it was not `zsh` but `oh-my-zsh` which took over your default colors.
And it was with **lsd 0.16.0**

Before making any PR I tested with the master branch, and now I have a different "issue"

I saw that you are now using sharkdp's lscolors library, this is a great improvement and it adds customization possibilities.

If I customize my `$LS_COLORS` lsd finds the values ​​well and displays the right colors.
99% of people will prefer this solution. And me too. 

But what I don't understand is if my `$LS_COLORS` is empty where `lsd` will look for the colors ? Apparently not in `color.rs`, since the color doesn't match.

![Capture](https://user-images.githubusercontent.com/25638207/75070832-5c914880-54f4-11ea-81d5-5719e0994c22.PNG)

**Comment by meain** [comment]
@Sherulez 

We pretty much let lscolors handle everything related to colors for file and folder names. So in this case, if no `LS_COLORS` is specified lscolors has a default fallback which gets use.

`README` needs a fix as the colors mentioned there for file types are not the ones you will end up getting.
