### ISSUE TITLE
Provide 32 and 64-bit windows binaries

### ISSUE THREAD

**Issue by martinlindhe** [Peltoche/lsd#330]
I would like to package lsd for scoop.sh (windows package manager) for easy installation by end users, but in order to do that I would like to request that you start providing 32-bit and 64-bit windows binaries with future releases.

**Comment by Peltoche** [comment]
Hello @martinlindhe ,

We already provide some 64bits windows packages inside the [release page](https://github.com/Peltoche/lsd/releases). I will look to add the 32bits if it's possible

**Comment by martinlindhe** [comment]
@Peltoche That is good news. It was not the case when I reported this.
