### ISSUE TITLE
Icons Missing using PuTTY

### ISSUE THREAD

**Issue by Koovu** [Peltoche/lsd#331]
Hi all,

Sorry I know this isn't really an issue with the package itself, but has anyone managed to get the icons working correctly using PuTTY on Windows?

**Comment by BasixKOR** [comment]
>Install the patched fonts of powerline nerd-font and/or font-awesome. Have a look at the [Nerd Font README](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md) for more installation instructions. Don't forget to setup your terminal in order to use the correct font.

Maybe this could help?

**Comment by RomelSan** [comment]
It works in SSH under Windows Terminal - it is a modern terminal for Windows 10.
Putty and Kitty uses old Windows stuff so it will not work 100%.

**Comment by maxsatula** [comment]
@Koovu
I contacted PuTTY developer Simon, and he kindly fixed that.
Try using PuTTY development snapshot. Of course, don't forget to use Nerd Font.

**Comment by RomelSan** [comment]
**@maxsatula**
Tested on my PC.
 The same font **Caskaydia Cove Nerd Font** will work 100% on **Windows Terminal**.
 On **Putty Development Snapshot** will show only 50% of the icon.
 For Example:
 **Clip Ico** will show OK on both, type: `echo -e "\uf64e"`.
 **Folder Ico** will show 50% in Putty, type: `echo -e "\uf115"`

You can download the Nerd Font i am using here:
 https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip

![snapshot](https://user-images.githubusercontent.com/11341002/108004337-955ae500-6fc3-11eb-9bbf-6f2cdfa21b41.png)

**Comment by maxsatula** [comment]
@RomelSan hmm... can it be font-specific? I just tried `echo -e "\uf115"` and it worked for me well, but I use **Hack** font (installed only `*Windows Compatible.ttf` files), not **Cascadia Code**

Keep in mind I was just a messenger here, I'm not part of either Nerd Font or PuTTY development teams.

**Comment by maxsatula** [comment]
Maybe because **Cascadia Code** is variable width, looking how your folder icon on the "correct" screenshot covers two letters above it. **Hack**, on the contrary, displays a folder glyph which is 1 character wide as other characters.

And that seems you have to switch to monospace font, here is what stackoverflow says: https://stackoverflow.com/questions/5776219/using-variable-width-font-in-putty

**Comment by RomelSan** [comment]
@maxsatula 
Yes, you are right.
Putty only works with fonts (1 character wide).
Now i am installing monospace font version too.
Tested with **hack nf mono windows compatible**
![fixed](https://user-images.githubusercontent.com/11341002/108006213-db667780-6fc8-11eb-8001-0aec3b2536c5.png)

Thanks for your help, now i can use putty again.
