### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by sumitsahrawat** [Peltoche/lsd#332]
Master is 90 commits ahead of the last release, which was more than six months ago. This might be a good time to make a new release.

The primary reason I'm asking for this is to be able to use the `-I`/`--ignore-glob` flag that was added but is not available in the latest release without having to build the package myself.

**Comment by meain** [comment]
@Peltoche I think we are due for another release.
I know you are a bit busy. Let me know if I can help you with anything.

**Comment by chunliu** [comment]
any update on this request?

**Comment by Peltoche** [comment]
Hello everyone! 

Sorry for the long delay, I had a lot of other priorities in the last few months. I have just released the 0.17.0 with all the changes.
