### ISSUE TITLE
output of filenames with special characters (\n, \t ...) is not escaped

### ISSUE THREAD

**Issue by ChristianS99** [Peltoche/lsd#335]
## Pre
touch tab$'\t'tab
touch newline$'\n'newline

## Expected behavior
not sure, ls displays this like `'newline'$'\n''newline'  'tab'$'\t''tab'`, but that's not very nice, too.

## Actual behavior
🗋  newline
newline  🗋  tab tab
displaying the tab/newline character as actuall tab/nl is not nice. it should be somehow escaped, maybe take ls as example, but something nicer is also nice :)

**Comment by meain** [comment]
The simplest option would be to have something like

```diff
diff --git a/src/meta/name.rs b/src/meta/name.rs
index f734e6b..58b2a5f 100644
--- a/src/meta/name.rs
+++ b/src/meta/name.rs
@@ -43,7 +43,7 @@ impl Name {
         let mut content = String::with_capacity(icon.len() + self.name.len() + 3 /* spaces */);
 
         content += icon.as_str();
-        content += &self.name;
+        content += &self.name.escape_default().collect::<String>();
         content
     }
 ```

This will just print out:

```
newline\nnewline tab\ttab
```

One possible solution would be to color `\n` but doing that with the current code is not that simple but maybe we can go with this for now?

**Comment by ChristianS99** [comment]
would be a start, definitely better than current.

**Comment by meain** [comment]
I would agree.

**Comment by meain** [comment]
Closing this as the primary issue is now fixed.
