### ISSUE TITLE
Implement "natural sort" (a la `ls -v`)

### ISSUE THREAD

**Issue by HarrisonMc555** [Peltoche/lsd#337]
The default `ls` implementation has a `-v` flag. This implements a "natural sort". This example shows the difference:

```text
$ ls
1.txt  10.txt  11.txt  12.txt  2.txt
$ ls -v
1.txt  2.txt  10.txt  11.txt  12.txt
```

This also works with "version" numbers, like so (mostly the same idea):

```text
$ ls
10.10  10.11  10.9  11.10  11.11  11.9	9.10  9.11  9.9
$ ls -v
9.9  9.10  9.11  10.9  10.10  10.11  11.9  11.10  11.11
```

Would we be interested in implementing this? I could look into implementing it if you think it would be a valuable feature.

**Comment by ngirard** [comment]
I'd also appreciate it very much !
FWIW `Exa` has natural sort implemented.

**Comment by ngirard** [comment]
A bit more information about Exa's implementation.

It [uses the natord crate](https://github.com/ogham/exa/blob/master/Cargo.toml).

The implementation is [here](https://github.com/ogham/exa/blob/4dab6237f1e1dffb1d20fad42ef8b13226f12e7c/src/fs/filter.rs#L242) ; and there's a discussion on which sorting to choose by default [there](https://github.com/ogham/exa/blob/db8c6e4627070b0b4f4c021a63d1cb41f3649cba/src/options/filter.rs#L75).

Exa's author chose to enable natural sort by default, and in practice I've found it to be *very* pleasant. I'd highly suggest making it the default for Lsd too.

**Comment by data-man** [comment]
Note: natord supports ANSI digits only.
[humanesort](https://lib.rs/crates/humanesort) uses unicode-segmentation crate.

**Comment by zwpaper** [comment]
fixed by https://github.com/Peltoche/lsd/commit/16f1b1ce7c45e98b505c2e7d57e0d46c88d882d3

**Comment by ngirard** [comment]
@zwpaper : thanks for your work !
Just out of curiosity, what made you choose [human-sort](https://lib.rs/crates/human-sort) over [humanesort](https://lib.rs/crates/humanesort) ?

**Comment by zwpaper** [comment]
hi @ngirard 
Actually there is not a special reason for choosing human-sort, 
Maybe the main reason for me when researching is `human-sort` looks simpler and cleaner.

After reading this thread, I found what `data-man` mentioned, maybe unicode would be hidden trouble, I will work on it when necessary.
