### ISSUE TITLE
line gap problem when terminal screen is not wide enough

### ISSUE THREAD

**Issue by ywpkwon** [Peltoche/lsd#338]
When a line exceeds screen width, `lsd` puts line gap so every line (even for shorter lines) has the same gap.
![image](https://user-images.githubusercontent.com/18429284/77804758-8848a680-703d-11ea-8736-626559b4c464.png)

Otherwise, `colorls` doesn't put any gap, and I think this looks more natural. 
![image](https://user-images.githubusercontent.com/18429284/77804699-694a1480-703d-11ea-8b77-cac3371bcbd9.png)

Does `lsd` intend this? Is there option to turn this off?

**Comment by meain** [comment]
Hai, it is a known issue. Fix available in master. Will be available in a new release.

Related: https://github.com/Peltoche/lsd/issues/264
