### ISSUE TITLE
Should use symlink target to colour and find icon when the symlink itself isn't enough

### ISSUE THREAD

**Issue by zerodogg** [Peltoche/lsd#339]
GNU `ls` colours a symlink that points to a directory as if it's a directory. lsd colours it like an "unknown file". lsd should use the symlink target to determine the colour and icon when the symlink itself doesn't provide enough information to do it.

A quick way to reproduce is: `cd /tmp;mkdir test-lsd; cd test-lsd;mkdir directory; ln -s directory symlink; \ls --color=auto --file-type;lsd`

Here's what that produces on my system:

![bilde](https://user-images.githubusercontent.com/60426/78292189-f0f4bf00-7526-11ea-8cf0-89b07a9bcdeb.png)

**Comment by meain** [comment]
Symlinks are actually given a specific color. This is also extended towards a broken symlink getting a red color.

Do you happen to be having a `$LS_COLORS` entry overriding it?

**Comment by meain** [comment]
Symlink colors/icons are based on the fact that they are symlinks and not weather they are linked to a file or a folder. Closing this issue.
