### ISSUE TITLE
MacOS not showing icons correctly

### ISSUE THREAD

**Issue by PeterZerg** [Peltoche/lsd#344]
## Expected behavior
The icons should show file [types.]

## Actual behavior
After set up, the ls command displays everything correctly except the icons. All icons are the same: a ? in a box
<img width="318" alt="Screen Shot 2020-04-09 at 13 48 29" src="https://user-images.githubusercontent.com/28642514/78939343-ce076500-7a68-11ea-91a1-1894d5fc979d.png">

**Comment by meain** [comment]
Hey, you need to have fonts that support the glyphs. Check https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334 for instructions.

**Comment by meain** [comment]
Closing this as the solution is already available. Feel free to reopen the issue in case that does not fix the issue.
