### ISSUE TITLE
OS 1332 Error under Windows

### ISSUE THREAD

**Issue by graphixillusion** [Peltoche/lsd#356]
Hi there. I'm getting this error when i run **lsd** command. It occurrs when i switch to another drive: on the main **C:** drive, it works; if i run the command on **D:** i get the OS 1332 error with this complete error message: **No mapping between account names and security IDs (SID)**.

**Comment by 72siddharth** [comment]
I get the same error on windows when calling lsd in any drive other than 'C:'. 

`lsd: .: No mapping between account names and security IDs was done. (os error 1332)`

Tested it in both powershell and cmd, same error.
What exactly is the problem here? And is there any workaround?

**Comment by isavegas** [comment]
I'm getting it in C: as well. `lsd` just straight up doesn't work on my Windows install. It appears to be related to having SMB shares mounted as drive letters. I'll do some research into the error and see if there's anything I can figure out on that front. 👍

**Comment by Skips75** [comment]
I get the same error with lsd version 0.19.0 executing it on a removeable D: drive on Windows 10 Pro 20H2.
I installed lsd via scoop utility and I'm using it on a Powershell 5.1.19041.610.
