### ISSUE TITLE
Missing space between icon and folder name

### ISSUE THREAD

**Issue by andys8** [Peltoche/lsd#363]
## Expected behavior

Space between icon and folder name

![image](https://user-images.githubusercontent.com/13085980/80864342-4c2ee400-8c82-11ea-8cd8-353479f31799.png)

## Actual behavior

There is no space between icon and folder name. Both overlap a bit.

![image](https://user-images.githubusercontent.com/13085980/80864347-5650e280-8c82-11ea-91d9-e2eb18a35872.png)

Is this an expected change?

## Info

Terminal: st (https://github.com/andys8/st)
Font: Iosevka Nerd Font-14

**Comment by nik312123** [comment]
I can confirm that this has come up between versions 16.0 and 17.0 for me as well.

**Comment by andys8** [comment]
I suspect the change from 2 spaces to 1 for one line is causing this behavior.

https://github.com/Peltoche/lsd/commit/200c5d2c68c7f0519d1eddfef2e30fe7dd8d11e5

**Comment by andys8** [comment]
Over the past history this has changed some times. But with a single space there will be a problem with double width fonts. Will a change to 2 spaces be accepted and merged?

**Comment by carlocaione** [comment]
+1 for this issue

**Comment by meain** [comment]
Related: https://github.com/Peltoche/lsd/issues/316#issuecomment-641407582

**Comment by kakulukia** [comment]
+1 for more spacing

This looks odd compared to colorls (coloring aside)

![Bildschirmfoto 2020-10-20 um 08 55 57](https://user-images.githubusercontent.com/96352/96551095-1920f100-12b2-11eb-8131-de7d00195410.png)

**Comment by andys8** [comment]
Over at `exa` they introduced `EXA_ICON_SPACING`

https://github.com/ogham/exa/commit/51be9f4c43e61bbea61e70e1459e494207d1d979#diff-48b676e2b107da679512b793d5fd4cc4329f0c7c17a97cf6e0e3d1005b600b03

**Comment by meain** [comment]
Now that we have support for config file, I guess we could add this as a config option `icon_spacing`.

**Comment by meain** [comment]
This should now be available via https://github.com/Peltoche/lsd/pull/469 once `0.20.0` lands.
