### ISSUE TITLE
Difference in colors between lsd 16.0 and lsd 17.0

### ISSUE THREAD

**Issue by nik312123** [Peltoche/lsd#364]
## Expected behavior
There exists some way to apply the original 16.0 colorscheme to `lsd` using `LSD_COLORS`

## Actual behavior
This is not possible with `LSD_COLORS` on macOS

Original 16.0
<img width="541" alt="Screen Shot 2020-05-03 at 4 44 29 AM" src="https://user-images.githubusercontent.com/24688726/80910959-d3b73a00-8cf8-11ea-8a0b-b9309533bbb4.png">

(Oddly enough, the fakelink.sh symlink, which is broken, does not turn out to be red as per the README, but that isn't really relevant to this issue.)

Current 17.0 with attempted replication via LS_COLORS:
<img width="229" alt="Screen Shot 2020-05-03 at 4 30 31 AM" src="https://user-images.githubusercontent.com/24688726/80910826-d9605000-8cf7-11ea-81fb-e1112946a0f3.png">

I do not believe there is a way to adjust LS_COLORS such that the output is the same as 16.0. As such, could there be an option passed to `lsd` to ignore LS_COLORS and just use the defaults from 16.0?

Directory used:
[test.zip](https://github.com/Peltoche/lsd/files/4569920/test.zip)

**Comment by andys8** [comment]
I suspect the change from 2 spaces to 1 for one line is causing this behavior.

https://github.com/Peltoche/lsd/commit/200c5d2c68c7f0519d1eddfef2e30fe7dd8d11e5

**Comment by meain** [comment]
https://github.com/Peltoche/lsd/issues/404
