### ISSUE TITLE
Include directory symlinks in group-dirs

### ISSUE THREAD

**Issue by pandiloko** [Peltoche/lsd#368]
When listing with e.g. `lsd -l --group-dirs=first` , the symbolic links pointing to a directory are listed as files. I understand this is technically right but I think it would be nice to have them listed "as directories" and group them accordingly (maybe a new group-dirs value, a new flag?). 

## Expected behavior
Symlinks pointing to directories groupped together with directories when using group-dirs option
## Actual behavior
Symlinks pointing to directories are listed as normal files and ignored by group-dirs option

lsd is a great project and this is just a very tiny annoyance for me. I hope it could be included but I'm using the hell out of this anyway. Thanks for lsd!!!

**Comment by Qwerty-Space** [comment]
any update to this please?

**Comment by meain** [comment]
Closed with https://github.com/Peltoche/lsd/pull/369
