### ISSUE TITLE
Audio icons appear as an ? in iTerm2 not in Terminal (macOS)

### ISSUE THREAD

**Issue by tarasis** [Peltoche/lsd#372]
## Expected behavior

Icons are musical notes rather than a ?. All other icons are recognisable things.

## Actual behavior

On macOS Catalina, Icon for mp3, m4a appears as a ? inside a oval.

![Screenshot 2020-05-12 at 23 27 37](https://user-images.githubusercontent.com/3006/81751881-41592800-94a8-11ea-9f3c-486b8a4f3b6c.png)

## Using

Iterm 2, most recent lsd via homebrew, with the MensloLGS NF. Shell is ZSH, with the following theme

```
  ZSH_THEME="powerlevel10k/powerlevel10k"
  POWERLEVEL9K_MODE="awesome-patched"
```

Also happens in Fish.

iTerm is configured to only use the MensloLGS NF font

![Screenshot 2020-05-12 at 23 37 46](https://user-images.githubusercontent.com/3006/81752609-ac572e80-94a9-11ea-8d3d-5894aa79fbf1.png)

It DOES work in Terminal with the MensloLGS NF font and the same ZSH theme.

![Screenshot 2020-05-12 at 23 35 25](https://user-images.githubusercontent.com/3006/81752498-74e88200-94a9-11ea-8803-0b55d8de5f59.png)

Final aside, musical note icon should probably be used for m4r too (Apple Ringtone)

**Comment by meain** [comment]
I am not sure what the exact problem is, but this is most probably not an issue with lsd itself.
Could you try with a different font?

Related: https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334

**Comment by tbrodbeck** [comment]
Hi. I would like to reopen the issue even though I use Hack Nerd Font (as described in the comment by @meain).
Examples:
<img width="225" alt="Screen Shot 2021-12-18 at 14 52 17" src="https://user-images.githubusercontent.com/24418160/146643460-30beb7b7-96bf-4828-a257-e9cd9d1336c5.png">

<img width="265" alt="Screen Shot 2021-12-18 at 14 52 30" src="https://user-images.githubusercontent.com/24418160/146643467-5f235049-b52a-44ab-a9e8-9fdc2a8aabc7.png">

I am using iTerm, zsh and `ZSH_THEME="robbyrussell"`
_lsd 0.20.1_
_iTerm2 Build 3.4.8_
_macOS 12.0.1_
_zsh 5.8_

**Comment by meain** [comment]
Hey @tbrodbeck , the icon issue is almost never really because of `lsd`. Could you post a screenshot of the fonts you have set in iTerm? Also, try setting both the "Font" and the "Ascii font" to be the font with icons and see if that helps.

**Comment by tbrodbeck** [comment]
There are my settings:
<img width="1055" alt="Screen Shot 2021-12-22 at 09 28 30" src="https://user-images.githubusercontent.com/24418160/147060914-35dbe738-6656-40f3-a9ca-c72903166921.png">
<img width="1055" alt="Screen Shot 2021-12-22 at 09 29 20" src="https://user-images.githubusercontent.com/24418160/147061020-876cbe32-4e75-4446-9e8d-43d31c893e4f.png">
I tried both without success.

I forgot to mention: I have downloaded font-hack-nerd-font: 2.1.0 from https://github.com/ryanoasis/nerd-fonts.

But you are right. It seems. to be an issue of Hack Nerd Font on iTerm specifically. If I copy `echo ` into terminal I will get a represenation of a music node, but not in iTerm.
<img width="189" alt="Screen Shot 2021-12-22 at 09 33 13" src="https://user-images.githubusercontent.com/24418160/147061617-e7ba7cdc-54fb-41d2-a44d-aa701db43f85.png">

Can you try to test this snippet, in case you have a working iTerm configuration?

I am not sure if I should open an issue now on the iTerm GitLab or the nerd-fonts Github. What would you suggest?

**Comment by meain** [comment]
I unfortunately don't use a mac anymore and won't be able to test it out. But if I remember correctly iTerm never used to have any issues with fonts.

```
echo $'\uf115'
```
Is the issue just with the audio icon? Does the above one give you a folder icon?
![Screenshot from 2021-12-23 09-29-22](https://user-images.githubusercontent.com/14259816/147186033-c9b1db58-9152-4288-8cf3-896165d6dc49.png)

**Comment by tbrodbeck** [comment]
<img width="269" alt="Screen Shot 2021-12-23 at 08 50 08" src="https://user-images.githubusercontent.com/24418160/147206860-a397ea53-b34b-4806-9693-6efb10dfb4bb.png">
The folder icon works fine. 

I think I will open an issue in the iTerm bug tracker for now.

**Comment by tbrodbeck** [comment]
https://gitlab.com/gnachman/iterm2/-/issues/10133

**Comment by tbrodbeck** [comment]
https://gitlab.com/gnachman/iterm2/-/issues/10133
