### ISSUE TITLE
`ls` prints incorrect file names

### ISSUE THREAD

**Issue by rhys-vdw** [Peltoche/lsd#373]
## Expected behavior
`ls` prints all file names individually.

## Actual behavior
Only the final character of `foo.gif` is rendered, `movs` appears instead of `foo.gi`.

```
Rhyss-MacBook-Pro-6:Gifs rhysvanderwaerden$ ls
   movsf   gifenc.sh   gifs   Icon
Rhyss-MacBook-Pro-6:Gifs rhysvanderwaerden$ ls -la
drwxr-xr-x rhysvanderwaerden staff 256 B  Mon May 18 13:25:41 2020  .
drwxr-xr-x rhysvanderwaerden staff 224 B  Fri May 15 15:30:32 2020  ..
.rw-r--r-- rhysvanderwaerden staff   8 KB Mon May 18 13:24:28 2020  .DS_Store
.rw-r--r-- rhysvanderwaerden staff 5.1 MB Mon May 18 13:25:45 2020  foo.gif
.rwxrwxrwx rhysvanderwaerden staff 385 B  Mon May 18 13:25:27 2020  gifenc.sh
drwxr-xr-x rhysvanderwaerden staff 224 B  Fri May 15 16:19:55 2020  gifs
.rw-r--r-- rhysvanderwaerden staff   0 B  Fri May 15 15:17:49 2020  Icon
drwxr-xr-x rhysvanderwaerden staff 256 B  Fri May 15 16:20:06 2020  movs
```
![image](https://user-images.githubusercontent.com/822105/82172135-ae3b4a80-990c-11ea-92cd-fa4ab54e4010.png)

**Comment by meain** [comment]
Probably related https://github.com/Peltoche/lsd/issues/325

**Comment by meain** [comment]
This should be fixed now.
Feel free to reopen if this issue still persists.

See https://github.com/Peltoche/lsd/issues/335 for any further improvement on how it is handled.
