### ISSUE TITLE
Ubuntu WSL not showing icons

### ISSUE THREAD

**Issue by fontes99** [Peltoche/lsd#382]
I've downloaded and intalled both lsd and nerd-fonts but the icons are failing to display
![image](https://user-images.githubusercontent.com/38656207/84038163-f383f280-a975-11ea-8128-3d5908eec494.png)

**Comment by buschtoens** [comment]
What environment are you using? I assume Windows? PowerShell?

You need to configure your Terminal to actually use the respective Nerd Font.

**Comment by fontes99** [comment]
> What environment are you using? I assume Windows? PowerShell?
> 
> You need to configure your Terminal to actually use the respective Nerd Font.

yes im using windows and ubuntu WSL.. how do I do this?

**Comment by buschtoens** [comment]
I'm not a Windows user, so I don't know, sorry. What's the terminal emulator that you user? What does it say in the title bar?

I'd assume it's PowerShell. Try googling `PowerShell change font` or something along these lines.

**Comment by fontes99** [comment]
Fixed it.

needed to download de nerdfont directly on windows and not on the Ubuntu WSL 

thanks for the help anyways!

**Comment by buschtoens** [comment]
Great to hear that and thanks for following up with the solution.

Can you close the issue then? :)

**Comment by Paulario** [comment]
> I've downloaded and intalled both lsd and nerd-fonts but the icons are failing to display
> ![image](https://user-images.githubusercontent.com/38656207/84038163-f383f280-a975-11ea-8128-3d5908eec494.png

> I've downloaded and intalled both lsd and nerd-fonts but the icons are failing to display
> ![image](https://user-images.githubusercontent.com/38656207/84038163-f383f280-a975-11ea-8128-3d5908eec494.png)

hi, could you please give me hint on what exactly font did you installed in order for lsd to work properly, i.e. show icons?
I happed to download the whole repository of nerd-fonts from GitHub and installed them in one take, that is 387 fonts. 
But none of them helped. And they are actually installed, 'cause I can use them in, say, MS Word and else. And I can even change the value of "fontFace" in settings.json file for my terminal. It also seems to work, except it doesn't help see the incons. Sooo ... I don't know =-(

**Comment by fontes99** [comment]
I fixed by downloading nerfont's Ubuntu and changed my terminal font to that

**Comment by SreehariTS03** [comment]
@fontes99 how to download nerdfont diractly in windows ?

**Comment by fablexis** [comment]
@SreehariTS03 as @fontes99 mentioned, you just have to download the font you want directly on windows, not using WSL, after that you can change the font of the WSL terminal on the settings option (I assume you're using WSL2).

You can find all the nerd fonts on: 
- [nerdfonts.com/font-downloads](nerdfonts.com/font-downloads) or 
- [https://github.com/ryanoasis/nerd-fonts#patched-fonts](https://github.com/ryanoasis/nerd-fonts#patched-fonts) (try to download the ones that are optimized for windows).

After that, you should be able to see all the icon references on the terminal. Hope this works for you.
