### ISSUE TITLE
Is it possible to configure which columns show?

### ISSUE THREAD

**Issue by ShawnMcCool** [Peltoche/lsd#390]
"ls -l" shows many columns, I'd like to remove some or reformat them into a compact format.

I don't see any information about a configuration file etc. Could you direct me to the right documentation?

**Comment by meain** [comment]
Yeah, check out `--blocks` in the help. It lets you define, which columns you need.

For example, if you need just name and size. You can do `lsd --blocks name,size`. Possible options in the help. You should also be able able to change how date, size, symlink etc look a bit.

**Comment by meain** [comment]
A config file is in the works https://github.com/Peltoche/lsd/pull/317. Still not complete. But till then, you can drop this in an alias.

**Comment by ShawnMcCool** [comment]
Hey this is perfect. Thanks. I was trying to find the help but without a man page etc I was confused. I see now it's just --help.
