### ISSUE TITLE
Permissions Error with opt folder

### ISSUE THREAD

**Issue by joesan** [Peltoche/lsd#392]
## Expected behavior
Doing a ls -la should list me all the files in the directory, in this case the /opt directory

## Actual behavior
```
joesan@joesan-InfinityBook-S-14-v5:/opt/softwares$ ls -l
cannot access '.': Permission denied (os error 13)
```

I guess there is an issue already relating to this. I could not infer the proposed solution to that issue.

https://github.com/Peltoche/lsdcannot%20access%20'.':%20Permission%20denied%20(os%20error%2013)/issues/79

Should I uninstall and install a newer version to fix this? If so which package is that for Ubuntu 20.04?

**Comment by zwpaper** [comment]
Hi @joesan 

May I ask how do u install `lsd`, if snap, maybe u should uninstall it and try a deb from
https://github.com/Peltoche/lsd#on-ubuntu
or a binary from
https://github.com/Peltoche/lsd#from-binaries

the problem may be caused by `snap` and it's not easy to fix

**Comment by Peltoche** [comment]
hello @joesan,

The `snap` packages are not more maintained due to too much issues with the jail system. I try without success to delete the available binaries since quite some time. As proposed by @zwpaper you should install it for the .deb.

**Comment by joesan** [comment]
How do I uninstall from the snap package and reinstall it from debian? Any guide or Wiki on how to do this would be helpful!
