### ISSUE TITLE
⚠ OS ERROR 1332 - Windows PowershellCore Installation

### ISSUE THREAD

**Issue by ABSphreak** [Peltoche/lsd#393]
I have installed LSD using release tag → [0.17.0](https://github.com/Peltoche/lsd/releases/tag/0.17.0) → ([lsd-0.17.0-x86_64-pc-windows-msvc.zip](https://github.com/Peltoche/lsd/releases/download/0.17.0/lsd-0.17.0-x86_64-pc-windows-msvc.zip))
and using scoop later as mentioned in #389.

## Expected behavior
I have installed the latest release on Ubuntu WSL, output looks:
(`ls` and `l` are aliases as they are mentioned in the docs)

![image](https://user-images.githubusercontent.com/9509127/88267058-e2a4fb80-cced-11ea-8b30-3f3fdbf55c14.png)

## Actual behavior
But on Windows, this happens as mentioned in #356
- I tried including `lsd.exe` path in Environment Variables
- Second time I installed using `scoop`

![image](https://user-images.githubusercontent.com/9509127/88267148-0a945f00-ccee-11ea-81a4-bbeaa1aefb67.png)

Please tell me what do I do to make it work on Powershell Core 7.0.3

**Comment by rediffusion** [comment]
@ABSphreak 

 Hey bro, how you install it on «Windows» tried 100 times but nothing? **ʅ_(ツ)_ʃ** 

I have WSL > Ubuntu 20.04

**Comment by ABSphreak** [comment]
@rediffusion You want to install it on Windows (Powershell) or WSL?

**Comment by rediffusion** [comment]
@ABSphreak

 WSL 2 > Windows Terminal > Ubuntu-20.04

**Comment by ABSphreak** [comment]
@rediffusion I just downloaded `lsd-musl_0.17.0_amd64.deb` from [Releases - 0.17.0](https://github.com/Peltoche/lsd/releases/tag/0.17.0) Page using `wget` and installed using `dpkg`.

```bash
# Downloads the release as .deb package
wget https://github.com/Peltoche/lsd/releases/download/0.17.0/lsd-musl_0.17.0_amd64.deb

# Installs it using dpkg
sudo dpkg -i lsd-musl_0.17.0_amd64.deb
```

**Comment by rediffusion** [comment]
@ABSphreak

OMG so easy. Bro, you are **RAMBO**! 😵

📍 Find another way too, check it:

> export RUSTUP_IO_THREADS=1
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> cargo install lsd

 _Have a good day!_ 👍

**Comment by ABSphreak** [comment]
_Awesome!_ 🦄

**Comment by ABSphreak** [comment]
@Peltoche can you point me to the solution of this issue?

**Comment by rediffusion** [comment]
@ABSphreak 

 If you want links here:
[1](https://github.com/rust-lang/rustup/issues/2450), [2](https://github.com/rust-lang/rustup/issues/2245).
