### ISSUE TITLE
dpkg: error on «Windows 10».

### ISSUE THREAD

**Issue by rediffusion** [Peltoche/lsd#396]
Aloha! 🙂

I have 💻 «**Windows 10** 2004» + _WSL_ + Windows Terminal + Ubuntu-20.04

running this but see the `error`:
sudo dpkg -i lsd_0.17.0_amd64.deb

`dpkg: error: cannot access archive 'lsd_0.17.0_amd64.deb': No such file or directory`

..._surfing_ in google this behavior but find nothing!

🆘 Can you HELP? Cheers!

**Comment by meain** [comment]
We don't have a direct ubuntu package yet. You could try installing using `snap`.
```
snap install lsd
```

Or if that does not work out, you have to first download the actual file from releases page and call dpkg on that.
```
wget https://github.com/Peltoche/lsd/releases/download/0.17.0/lsd_0.17.0_amd64.deb -O /tmp/lsd.deb
dpkg -i /tmp/lsd.deb
```

**Comment by rediffusion** [comment]
@meain

 Thanks a lot! What means parameter -O ?

Do I need to install [Rust](https://www.rust-lang.org/)?

**Comment by meain** [comment]
`-O` specifies output filename. In this case we download to `/tmp/lsd.deb` and uses that file to install.

You need to install rust only if you are building from source.
In the case of dpkg, you are downloading and installing a prebuilt binary.

**Comment by rediffusion** [comment]
@meain 

 I find also this [manual](https://github.com/Peltoche/lsd#from-sources) which possible to downloading with **cargo**. Do you recommend this manual?

`cargo install lsd`

**Comment by meain** [comment]
`cargo` is the rust package manager you are technically building from "source" in the `manual` method.

It is up to you too choose which method you go, both works.  But if you don't intent on messing around with the code, I would suggest going with `dpkg`.
