### ISSUE TITLE
Implement customize color feature

### ISSUE THREAD

**Issue by touhidulShawan** [Peltoche/lsd#402]
Please Implement able to color customization. Directory Blue color is not suitable for my terminal color. I really love lsd.

**Comment by meain** [comment]
You can use `LS_COLORS` for customizing the colors of the folders and files. Simple write up on what they are. http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors

You can use a tool like [sharkdp/vivid](https://github.com/sharkdp/vivid) to generate `LS_COLORS` if you don't find any that you like. Also maybe checkout https://github.com/trapd00r/LS_COLORS .

**Comment by touhidulShawan** [comment]
Thank you
