### ISSUE TITLE
Feature request: allow symlink arrow to be "->" instead of "⇒"

### ISSUE THREAD

**Issue by planet36** [Peltoche/lsd#409]
On my system, the rightwards double arrow character is not visually distinctive from a bold hyphen.

Please allow (maybe with an option or env var) the symlink arrow to be "->" instead of "⇒".

**Comment by zwpaper** [comment]
Add a option for rendering this would be an easy solution, what do u think? @meain

**Comment by meain** [comment]
Yeah, I have a few concerns though:

- does the flag only affect `⇒` or all future non ascii chars if any
- what should the flag be (--only-ascii ?)
- should the flag be `=>` or `->` as some fonts have `-` rendered below middle

**Comment by zwpaper** [comment]
@meain actually, there is a more complicated solution in my mind, as u mentioned maybe the flag may effect all chars.

How about we add themes for all those customized requests, like this issue, https://github.com/Peltoche/lsd/pull/333, and the description in README.

we can use a theme file to describe the `=>`, icons, also colors.

**Comment by meain** [comment]
Yeah, that sounds good. Config would be a better place for this.

**Comment by planet36** [comment]
It works great.  Thanks!
