### ISSUE TITLE
Can't show file or dir icon (v 0.18.0)

### ISSUE THREAD

**Issue by 357711589** [Peltoche/lsd#410]
![image](https://user-images.githubusercontent.com/34570968/92687120-89f8f300-f36d-11ea-9d82-eb3998516a8e.png)

**Comment by sklages** [comment]
Incompatible font? Have you installed any Nerd font? See [Nerd Fonts README](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md)

**Comment by meain** [comment]
https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334
