### ISSUE TITLE
Arch Linux has empty lines (if terminal width is not enough)

### ISSUE THREAD

**Issue by horseinthesky** [Peltoche/lsd#419]
- os: Arch Linux
- `lsd --version`: lsd 0.16.0
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 
rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:

## Expected behavior
Not having empty lines if not necessary (Ubuntu behavior)
![image](https://user-images.githubusercontent.com/19948672/94426059-ab434700-0195-11eb-9cca-e2f4325fb7d6.png)

## Actual behavior
Arch Linux has these unnecessary empty lines after each file if at least one line is longer than the terminal width
```
tput cols
98
```
![image](https://user-images.githubusercontent.com/19948672/94426155-d037ba00-0195-11eb-9eb9-e3e4078667f5.png)

If there is enough space, everything fits in one line
```
tput cols
133
```
![image](https://user-images.githubusercontent.com/19948672/94426856-e1cd9180-0196-11eb-8766-cdbb559b03ba.png)

Install method:
Ubuntu: deb package from the releases page
Arch: pacman

**Comment by meain** [comment]
This is a known issue and has been fixed in the latest version.

**Comment by horseinthesky** [comment]
Noticed that `pacman` has 0.16.0 (dated 2 Aug 2019).
Installed 0.18.0 via `yay`. Everything works great.
Thank you.
