### ISSUE TITLE
Highlight files that are executable or have suid

### ISSUE THREAD

**Issue by LippyBoy** [Peltoche/lsd#42]
The default gnu ls adds a * at the end of executable files to mark them.
It also colors them differently, and it highlights in red files that have a setuid bit on.

It would be really useful if lsd did that too to mark them easily.
They could also have an icon (assuming the file doesn't have one already) - I'm thinking the dollar icon for an executable, and a # for a suid, but I don't have strong opinions on this.

**Comment by Peltoche** [comment]
Hi @LippyBoy,

Thanks for the issue, it seems to be a good idea indeed. I see that with `ls --color=always` the files are colored in green if the user have the executable permission but I don't see any `*`. 

For the specific icon I'm not sure it will make it more readable. For example if we `lsd` an executable bash script and we replace the bash icon by generic executable icon we duplicate the "this file is an executable" info (color green + icon) and we loose the "this file is a bash script" info with the bash icon. There is currently the same issue with one of the latest change with the symbolic link.

**Comment by Peltoche** [comment]
#44 created

**Comment by Peltoche** [comment]
#45 created

**Comment by Peltoche** [comment]
I learned something new today, thanks to you.

The `/` is already done for the directories. 

The question is: Should it be set as default or do we need a flag for it? Personally I vote to put them by default without any flag, I think it would simplify the options.

**Comment by alaymari** [comment]
As it is, `lsd` displays icons for directories and files. I feel adding `/` to the end of the filename is not a good idea for `lsd`. I feel icons should indicate the type of the file (link, shell script, etc) and the colors should be as per LS_COLORS.

**Comment by Peltoche** [comment]
You copy-paste issue is interesting and it's true that moving the information into the icons solve the problem in most cases (as explained in my previous message the symbolic link bother me a little).

In any case an option allowing to setup the icons set (current icons / unicode only / no icons) should appear soon. This means that some user would have to possibility to print the result without icons and so I think that the `-F` flag would be useful for them.

If I resume the discussion:

We add custom icons for all the custom files (pipe / symlink / executable / etc) and we create a `-F` flag like the classic ls which can be used by the user who doesn't want to use the icons.

Seems good to you?

**Comment by alaymari** [comment]
As you suggest, a `-F` *may* be useful for printing purposes. But, would not the vanilla `ls` already do that job? :-) 

Regarding the icons, I noticed that the TeX file has an icon which is so thin, it is nearly invisible. Can a different icon be set for that; maybe the `txt` file icon itself would be better than the existing one.

**Comment by Peltoche** [comment]
Yep, finally it's probably the best idea to follow the classic ls `-F` option and add the filetype specific icons. If we do that it means that we should to remove the '/' at the end of the directories when the `-F` option is not set.
