### ISSUE TITLE
Do not print folders size

### ISSUE THREAD

**Issue by k03mad** [Peltoche/lsd#421]
- os: macOS 10 / Android 9 (Termux) / Raspbian Buster
- `lsd --version`: lsd 0.18.0
- `echo $TERM`: xterm-256color

## Expected behavior
`lsd -al` prints `-` at dirs size

```
$ lsd -al
drwxr-xr-x qq LD\Domain Users   - Wed Sep 30 01:33:32 2020  .
drwxr-xr-x qq LD\Domain Users   - Wed Sep 30 01:33:15 2020  ..
drwxr-xr-x qq LD\Domain Users   - Wed Sep 30 01:33:25 2020  empty-dir
.rw-r--r-- qq LD\Domain Users 0 B Wed Sep 30 01:33:32 2020  empty-file.txt
```

## Actual behavior
`lsd -al` prints dirs size (even for `.` and `..`)

```
$ lsd -al
drwxr-xr-x qq LD\Domain Users 128 B Wed Sep 30 01:33:32 2020  .
drwxr-xr-x qq LD\Domain Users 768 B Wed Sep 30 01:33:15 2020  ..
drwxr-xr-x qq LD\Domain Users  64 B Wed Sep 30 01:33:25 2020  empty-dir
.rw-r--r-- qq LD\Domain Users   0 B Wed Sep 30 01:33:32 2020  empty-file.txt
```

Looks like it's broken again:
https://github.com/Peltoche/lsd/issues/23
https://github.com/Peltoche/lsd/pull/35

**Comment by zwpaper** [comment]
maybe we need to discuss the dir size output, I have checked the `Ubuntu` and `macOS` ls, it acts differently.

we currently act align to macOS

`Ubuntu`:
```shell
ubuntu@localhost:/tmp$ ls -al /tmp/
total xx
drwxrwxrwt 25 root    root        4096 Sep 30 14:51 .
drwxr-xr-x 24 root    root        4096 Sep 30 14:51 ..
drwxrwxr-x  2 ubuntu  ubuntu      4096 Sep 30 14:34 dir
```

`macOS`:

```shell
λ ls -al /tmp/                                                                     
total xx
drwxrwxrwt  50 root      wheel    1600 Sep 30 14:48 .
drwxr-xr-x   6 root      wheel     192 Jan  1  2020 ..
drwxr-xr-x   5 user      wheel     160 Sep 30 14:52 lsd-0.18.0-x86_64-apple-darwin
```

`lsd 0.18.0`:

```shell
λ lsd -al /tmp/                                                                               [14:52:36]
drwxrwxrwt root     wheel   1.6 KB Wed Sep 30 14:48:48 2020  .
drwxr-xr-x root     wheel   192 B  Wed Jan  1 16:00:00 2020  ..
drwxr-xr-x user     wheel   160 B  Wed Sep 30 14:52:31 2020  lsd-0.18.0-x86_64-apple-darwin
```

**Comment by k03mad** [comment]
It would be nice to have an option for this.
Something like:
`--dir-size <value>`

default: current behavior
total: eq to `--total-size`
none: `-` for dirs size

**Comment by zwpaper** [comment]
lsd already show the dir size by default, a flag seems not that necessary?

may I know what's the main point for adding this flag?

**Comment by k03mad** [comment]
I thought it's the right way to do it.

Similary to `--size`:
```
        --size <size>...
            How to display size [default: default]  [possible values: default, short, bytes]
```

Which prints the same output with default arg:
```
lsd -l 
lsd -l --size default
```

**Comment by zwpaper** [comment]
just like [people in Stackoverflow](https://stackoverflow.com/a/1019124/4242336) said, dir size should be the duty of `du`.

maybe I got the idea mistakenly, @meain could u help to look into this feature request? as I found u have discussed the dir size before in that PR.

**Comment by meain** [comment]
From what I could find, the size for dir was explicitly brought back in https://github.com/Peltoche/lsd/pull/166. Also seems to be what classic ls is doing anyways.
Any specific workflow of yours that relied on size of folders being `-`?

**Comment by k03mad** [comment]
I thought this was broken behavior.

Folders size (not total) seems a little useless.
Additionally, folders are better recognized with `-`, especially if `--color never --icon never` flags are passed (if anyone uses this combination...).

Maybe I'm just used to the output of the exa and this feature is not really needed by anyone in lsd.

**Comment by meain** [comment]
@k03mad I think we will keep it as is for now.
Btw, in case you don't have colors or icons, you could always fall back to `-F` to distinguish between files, folders or symlinks.

Related: https://unix.stackexchange.com/questions/55/what-does-size-of-a-directory-mean-in-output-of-ls-l-command
