### ISSUE TITLE
[Info] How to setup nerd font in order to work lsd properly in Termux(Android).

### ISSUE THREAD

**Issue by kcubeterm** [Peltoche/lsd#423]
You can install `lsd` in termux via. `pkg install lsd`

1. Visit [nerdfonts.com](https://nerdfonts.com) and download  your favourite font.
2. Unzip it `unzip my-favorite-font.zip`

3. Now you will see lots of .ttf and .otf file, rename any .ttf file into font.ttf and move it into `~/.termux` directory.
```
mv my-favorite-font.ttf ~/termux/font.ttf
```

4. Reload settings, `termux-reload-settings` or just open new session.

![IMG_20201001_132856](https://user-images.githubusercontent.com/50498359/94786428-94e3f800-03ee-11eb-9438-07aef7a6ee65.jpg)

**Comment by meain** [comment]
Thanks a lot! :)

**Comment by widhisec** [comment]
Thanks

**Comment by TheWolframDev** [comment]
Я за тебя молюсь.

**Comment by Dlazder** [comment]
> Я за тебя молюсь.

Там куча начертаний, жирные, курсив и т.д. это ведь никак нельзя заставить работать вместе? Только один из шрифтов только можно использовать?

**Comment by Inu-Yasha** [comment]
But, please - Some applications (like some SSH clients), allow choosing a non-default font. There's just no choices between monospace fonts by default, not on devices I've used and tried...

So pretty please, how does one actually install their own custom fonts on an Android device? Not just to one app... There must be a way! It has fonts! <3

**Comment by lpanebr** [comment]
Thanks!
