### ISSUE TITLE
[Docs] What color theme is used in the Screenshot?

### ISSUE THREAD

**Issue by coolaj86** [Peltoche/lsd#430]
Kind of related to https://github.com/Peltoche/lsd/issues/208, I'm looking for a theme that works well with my tools `fish`, `lsd`, `bat`.

The one in the screenshot in the README looks really well balanced. What is it?

**Comment by zwpaper** [comment]
just like https://github.com/Peltoche/lsd/issues/90, lsd use `LS_COLORS` to create theme currently, and there is a light theme coded inside lsd.

theme configuration file support should be on the way https://github.com/Peltoche/lsd/issues/92

the screenshot in README should be a dark theme based on `LS_COLORS`

**Comment by meain** [comment]
To add to what @zwpaper mentioned. Not sure of the exact colorscheme name of the one in the readme, but default pastel dark colorscheme in iTerm2 looks kinda similar. Most dark themes in my experience looks good.
<img width="489" alt="Screenshot 2020-10-09 at 10 07 29 AM" src="https://user-images.githubusercontent.com/14259816/95544002-a002dd80-0a17-11eb-9b5e-9a07152c3272.png">

Also as @zwpaper mentioned, you can control the colors of all file and folder by setting `LS_COLORS` variable in your shell. As for the colors of other elements, we are planning to add support to configure them via a config file in the future.
