### ISSUE TITLE
Please change icon for .ttc file

### ISSUE THREAD

**Issue by nix6839** [Peltoche/lsd#435]
- os: Arch Linux
- `lsd --version`: lsd 0.18.0
- `echo $TERM`: alacritty
- `echo $LS_COLORS`: 

## Expected behavior
The `.ttc` file is a font file. However, in `lsd`, displayed by the file icon. Please fix this to be displayed as a font file.

**Comment by zwpaper** [comment]
@nix6839 I created a PR for this, adding icon is really a easy work, maybe next time you could also have a try

everyone is welcome for PRs!
