### ISSUE TITLE
doesn't read config file in 

### ISSUE THREAD

**Issue by ExpandingMan** [Peltoche/lsd#439]
- os: 
- `lsd --version`: `0.18.0` 
- `echo $TERM`: `xterm-256color` (in `alacritty`)

## Expected behavior
`lsd` behavior corresponds to config file.  For example, setting color to `never` turns off colors.

## Actual behavior
`lsd` seems to ignore config file, changes in file are not reflected in the command.  I put the file at `$HOME/.config/lsd/config.yaml`.  This is on Ubuntu 20.04.  I tried adding `$HOME/.config` to `XDG_CONFIG_DIRS` but this did not seem to do anything.

**Comment by zwpaper** [comment]
Hi @ExpandingMan , sorry for the misleading, config file support is currently on the master branch and not yet released!

the newest released is `0.18.0`, which is you can see on `https://github.com/Peltoche/lsd/tree/0.18.0e`

**Comment by meain** [comment]
Will try to cut out a release with config file support soon.

**Comment by ExpandingMan** [comment]
Ah, sorry, I should have checked the tagged commit.  Thanks.
