### ISSUE TITLE
can't show icon ?

### ISSUE THREAD

**Issue by j-w-huang** [Peltoche/lsd#440]
- os: 
- `lsd --version`: lsd 0.18.0
- `echo $TERM`: xterm-256color
xterm-256color
- `echo $LS_COLORS`: NULL

![Uploading image.png…]()

**Comment by meain** [comment]
Hey, the screenshot you took never got uploaded to Github. The OS also does not seem to be specifid.
Icon issue is almost always an issue with the font installation.
To check if your terminal has proper font setup try pasting this into the terminal and see if you can see a rust icon beside the filename.
```sh
echo " build.rs"
```

If you can't see a proper icon, check out the [Nerd Fonts](https://www.nerdfonts.com) guide on how to install a [font](https://www.nerdfonts.com/font-downloads) with proper icon support.
You can always check if the font installation was successful by running the above script in the shell.

I am closing the issue as this has been discuss a lot before here. If the echo command shows icons but lsd does not feel free to reopen the issue.
