### ISSUE TITLE
In alacritty terminal the folder icon is missing

### ISSUE THREAD

**Issue by jamischarles** [Peltoche/lsd#449]
- os: Mac OS 10.15.7 Catalina
- `lsd --version`: 0.18.0
- `echo $TERM`: alacritty
- `echo $LS_COLORS`: 

## Expected behavior
In `iterm2` I see all icons properly with `FiraCode Nerd Font Mono` font.
In  `alacritty` (same font) the folder icon is missing. I expect it to show up.

## Actual behavior
In `iterm2` I see all icons properly with `FiraCode Nerd Font Mono` font.
In  `alacritty` (same font) the folder icon is missing. 

<img width="1536" alt="Screen Shot 2020-11-30 at 4 19 42 PM" src="https://user-images.githubusercontent.com/606014/100677236-dd089380-3327-11eb-8030-51b8f2abde06.png">

**LOVE lsd!** 
Any ideas at all for how I could troubleshoot this?

**Comment by zwpaper** [comment]
![image](https://user-images.githubusercontent.com/3764335/100689327-396ac200-33bf-11eb-8e5a-870859b896b0.png)

I try `Hack Nerd Font` in `alacritty`, it works as expected.

could you make sure the font is configured correctly, or try another one?

PS: you could try with this command to print the folder icon in shell.

```shell
echo '\uf115'
```

**Comment by jamischarles** [comment]
@zwpaper Thank you for confirming. Doh. Figured out that I had a patched font for regular, but not for bold (which is what the folders are). Thank you!
