### ISSUE TITLE
Latest AUR version of lsd is outdated

### ISSUE THREAD

**Issue by federicotorrielli** [Peltoche/lsd#453]
The community package of LSD on [AUR](https://www.archlinux.org/packages/community/x86_64/lsd/) is the 0.16.0 which I think it's far than outdated, I think the last packager was @felixonmars so maybe he can lend us a hand on having the latest version.

**Comment by zwpaper** [comment]
https://aur.archlinux.org/packages/lsd-bin/ updated

**Comment by federicotorrielli** [comment]
Thanks, appreciated.
