### ISSUE TITLE
Don't relying on set XDG variables

### ISSUE THREAD

**Issue by MichaelSasser** [Peltoche/lsd#455]
- os: 
- `lsd --version`: `lsd 0.18.0`
- `echo $TERM`: `alacritty`
- `echo $LS_COLORS`: not set
- build with cargo
- `Linux MyHostName 5.9.13-arch1-1 #1 SMP PREEMPT Tue, 08 Dec 2020 12:09:55 +0000 x86_64 GNU/Linux`

## Expected behavior
`lsd` uses the configuration set in `~/.config/lsd/config.yaml` by getting the path on linux based operating systems from (in this order):
- `XDG` variables
- `$HOME/.config/lsd/config.y(a)ml`
- `$HOME/.lsd/config.y(a)ml` or `$HOME/.lsd.y(a)ml`

and merge them with:
- `/etc/lsd/config.yaml`

## Actual behavior
Configuration has not been applied.

## Issue
I think the problem is relying on `XDG` variables. On Arch only `XDG_RUNTIME_DIR` is set by default.

```console
$ export -p | grep XDG
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_SEAT=seat0
export XDG_SESSION_CLASS=user
export XDG_SESSION_ID=2
export XDG_SESSION_TYPE=wayland
export XDG_VTNR=1
```

In my case `wayland` did set the others.

## Workaround (untested)

Set the needed XDG variables in `/etc/profile.d/SomeName.sh`

**Comment by meain** [comment]
@MichaelSasser  I believe if `$XDG_CONFIG_HOME` is not set it defaults to `$HOME/.config`.
That said, the config option is not available in 0.18.0. I was just waiting for https://github.com/Peltoche/lsd/pull/443 to land to publish the next release.
That said, if you wanna give it a shot now master should have config parsing.
