### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by sklages** [Peltoche/lsd#460]
Is there a way to install `lsd` with `cargo install` without the need of using a nightly build of `rustc`?
It would makes things easier ..

**Comment by meain** [comment]
`lsd` should work on stable rust. Our CI runs on [1.43.1](https://github.com/Peltoche/lsd/blob/e3649fede8f7fc64041b709c56a3438ddbf813f0/.github/workflows/CICD.yml#L9).

**Comment by sklages** [comment]
hmm, okay, Distro: `Linux Mint 20 Ulyana`:

```
cargo --version
cargo 1.43.0
```

**Comment by sklages** [comment]
I'll take the binary release meanwhile ...

**Comment by meain** [comment]
@sklages Do you have any error logs? I tried  doing `cargo install lsd` in `rust:1.43.0` container image and that seemed to work.

**Comment by sklages** [comment]
thanks @meain ... honestly, no idea, but it works now with `1.43.0`, 

```
  cargo install --debug --verbose lsd
  [...]
    Finished dev [unoptimized + debuginfo] target(s) in 22.31s
   Replacing /home/XXX/.cargo/bin/lsd
    Replaced package `lsd v0.18.0 (https://github.com/Peltoche/lsd.git#b6bd1d3b)` with `lsd v0.19.0` (executable `lsd`)
```
.. and a regular install works just as fine (without debug).

Sorry for the noise :-)
