### ISSUE TITLE
ignore option like tree has

### ISSUE THREAD

**Issue by Anu2001dev** [Peltoche/lsd#462]
## Feature 
similar option to `-I` option that `tree` command has.

## Expected behaviour
`lsd --tree -I Downloads`: should Ignore `Downloads` folder

**Comment by meain** [comment]
Latest `lsd` has support for `-I`.

**Comment by Anu2001dev** [comment]
you mean `lsd --tree -I node_modules` would work

**Comment by meain** [comment]
Yup, that should work.

**Comment by Anu2001dev** [comment]
oh. I am using arch linux and I was using `lsd: 0.16.0` . after that I uninstalled it and installed the aur `lsd-git: 0.19.0` now it works. thanks for your help.
