### ISSUE TITLE
Change the display of --tree when used alongside --long

### ISSUE THREAD

**Issue by jlagneau** [Peltoche/lsd#468]
Currently, the tree is displayed on the leftmost side and it shift all the columns around depending on the depth of the tree, making the output sort of hard to read.

![image](https://user-images.githubusercontent.com/7811277/103192593-8451f980-48d9-11eb-841a-940986fb33a5.png)

Wouldn't it make sense to display the tree depth character alongside the file/directory names or at least on its own column to allow configuration to change that.

**Comment by BinaryBen** [comment]
I've changed the config to:

```yaml
blocks:
  - name
  - size
  - date
```

This gives the effect you are after when using `lsd -l --tree` and you can add the permission to the end. It will change it for `lsd -l`  as well though

**Comment by jlagneau** [comment]
That's pretty clever and simple.

Your config does fix the issue for file/folders names readability in the tree, and I didn't think of that, thanks a lot. I'll be using that in the mean time until there's something a bit better. But it's not really fixing the issue of columns shifting around depending on the depth of the tree though and that's part of my issue with the current implementation of tree with lsd and how hard to read some info end up. It does a fine job at aligning all the info in the long view usually, it makes searching for specific info a breeze and I wish it was the case with the tree view.

If you want a comparison with exa for example, here what it looks like (sorry for the icons missing, didn't install nerd fonts on that windows machine for them to work with wsl / ssh, pay no mind to them):

![image](https://user-images.githubusercontent.com/7811277/104879418-1f307780-595e-11eb-86a4-871b7f65bf9d.png)

I do very much prefer lsd for many things on my different machines (configurations, icons and all that) but I believe exa got the tree view mixed with long view right at the very least.
