### ISSUE TITLE
Carriage return "\r" in filename breaks output

### ISSUE THREAD

**Issue by schlueter** [Peltoche/lsd#472]
- os: MacOS
- `lsd --version`: lsd 0.17.0
- `echo $TERM`: screen-256color
- `echo $LS_COLORS`: di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:

## Expected behavior
Inclusion of all files in directory in lsd output.

LS output:
```
/tmp $ \ls 
Icon??                          powerlog
com.apple.launchd.if8QY6X5ph    tmux-501
```

## Actual behavior
```
/tmp $ lsd
   powerlog   tmux-501Y6X5ph   Icon?
```

## Notes
- I can create that file with `touch $'Icon?\r'`. 
- Removing the `$'Icon?\r' file restores normal functionality. 
- Other filenames can cause an issue, for instance: 

      /tmp $ touch $'\r'
      /tmp $ ls
         com.apple.launchd.if8QY6X5ph   powerlog   tmux-501
      /tmp $ touch $'a\r'
      /tmp $ ls
         com.apple.launchd.if8QY6X5ph   powerlog   tmux-501
      /tmp $ touch $'z\r'
      /tmp $ ls
         com.apple.launchd.if8QY6X5ph   powerlog   tmux-501   z
       /tmp $ touch $'m\r'
       /tmp $ ls
         powerlog   tmux-501   z5ph   m

**Comment by meain** [comment]
It should be fixed in the latest version of lsd `0.19.0`. Closing this issue, feel free to reopen if you hit this issue even after updating to the latest version.
