### ISSUE TITLE
Arch Linux package dependency

### ISSUE THREAD

**Issue by OlegKrikun** [Peltoche/lsd#476]
Hi, folks! Thank for a awesome tool!

Arch [package](https://archlinux.org/packages/community/x86_64/lsd/) have dependency `awesome-terminal-fonts`, it is possible to mark it as optional?  =)

**Comment by nogerine** [comment]
See bug report for this: https://bugs.archlinux.org/task/62761

**Comment by meain** [comment]
Thanks @nogerine . Closing this issue as this is arch packaging issue and is not something that is controlled by us.
