### ISSUE TITLE
Tight grid/spacing and icon padding

### ISSUE THREAD

**Issue by adguy360** [Peltoche/lsd#478]
- os: macOS 10.15.7
- terminal: iterm2 (theme solarized dark)
- shell: fish 3.1.2
- `lsd --version`:  `lsd 0.19.0`
- `echo $TERM`:  `xterm-256color`
- `echo $LS_COLORS`: nothing

I may be missing something trivial here, but it seems like when running `lsd` the results grid are extremely tight (spacing/padding - also between rows). This is not only compared to `ls` but also compared to lsd's screenshots and videos I've seen online. The icons being so close to the file names are also an issue here.

![image](https://user-images.githubusercontent.com/53037478/106316079-d9848080-6274-11eb-9cdf-85dfbdeb604f.png)

Same issue for `lsd -l` - extremely tight columns/grid and icons are too close to the file names - IMO this makes the file names very hard to read.

![image](https://user-images.githubusercontent.com/53037478/106316648-bdcdaa00-6275-11eb-8147-0b7b428087f0.png)

As you can see there's also an issue with the colors but I noticed there are already open issues for that.

Would love to know what causes the spacing issues - is it something on my end? or a bug?

Thanks

**Comment by zwpaper** [comment]
this should be related to fonts, and this will be able to be configurated after `0.20.0` related.

you can check more in https://github.com/Peltoche/lsd/issues/363

**Comment by adguy360** [comment]
Thanks @zwpaper but if I'm not mistaken that will take care of the icon spacing only no?

What about the tight spacing between the results grid columns/rows?

I also notice that in `ls` each grid cell width is dictated by the longest entry in all results - equal columns. In `lsd` the columns are skewed - the cell width is dictated by the longest entry in the column. I assume that is by design but I'm wondering if you plan to add an option to control that?

Is there a some place where I can track a release schedule? or am I asking too much? 😅

**Comment by meain** [comment]
@adguy360 
- The grid spacing is set to be that way. From what I can tell, this is how gnu ls handles it.
- Icon spacing (space between the icon and the name) depends on the font that you are using as @zwpaper mentioned and will have a flag to configure that.
- For color issue, you can refer to https://github.com/Peltoche/lsd/issues/365#issuecomment-733095300
- There is no set release schedule, but you can track the releases at https://github.com/Peltoche/lsd/releases
