### ISSUE TITLE
Add a flag to change config file location

### ISSUE THREAD

**Issue by BinaryBen** [Peltoche/lsd#480]
Could we include a flag to point to a custom location for the config.yaml file? Something like the `-f` option in `tmux`.

**Comment by meain** [comment]
Hey, would like know your workflow in which having multiple config files would be useful. Just trying to understand the use case for this.

**Comment by BinaryBen** [comment]
I have my dotfiles in ~/.files and want to reduce the number of symlinks I need to make that work. I'd like to be able to alias `ls` to `lsd -A -f $DOTFILES/lsd/config.yaml` in my bash/zsh files (which will be symlinked)

**Comment by fabricio7p** [comment]
Hey i'm willing to implement this feature if approved the maintainers.
I'm a beginner in Rust and i appreciate if the maintainers could give me this shot as a mentored issue.

**Comment by zwpaper** [comment]
Maybe it is not a bad idea to have an option for the path.
what is your idea about letting @fabricio7p implement this? @meain

**Comment by meain** [comment]
I don't see a strong usecase for this as we are using XDG directory spec, but at the same time, I don't really have any strong opinions against not implementing it.
@fabricio7p feel free to go ahead with implementation. I would love to help you out, but unfortunately, I personally am pretty busy these days to be of much help. Feel free to go through the codebase and ask any question here, one of should be able to help you out in case you run into any major issues.

For starters, https://github.com/Peltoche/lsd/blob/master/src/app.rs is the file that you would be looking into add a new flag. That gets parsed out https://github.com/Peltoche/lsd/tree/master/src/flags. And the actual implementation of config file name is at https://github.com/Peltoche/lsd/blob/9f83b8d2a3c3db847584f5246421abb9c35c576c/src/config_file.rs#L122 as of now.

**Comment by fabricio7p** [comment]
I appreciate it! i'll be posting my results very soon. I'm kinda having a busy week aswell but you can count on me 👍

**Comment by fabricio7p** [comment]
#520 PR here guys

**Comment by zwpaper** [comment]
closing as https://github.com/Peltoche/lsd/pull/520 merged
