### ISSUE TITLE
Add Windows support?

### ISSUE THREAD

**Issue by damaainan** [Peltoche/lsd#49]
Hey, can you help  to add Windows support?
This is an example 
[https://github.com/dtolnay/cargo-llvm-lines/commit/197316feaf283d5397d5e10d688ece63e5314706](https://github.com/dtolnay/cargo-llvm-lines/commit/197316feaf283d5397d5e10d688ece63e5314706).
I'm a beginner for rust,unfortunately i can not do it by myself.
If anyone can do this,thanks very much.

**Comment by Peltoche** [comment]
Hi @damaainan,

The windows support would be so cool indeed, but I's a big project. There will be a lot of custom stuff to do (remove the pipes / the char devices / etc) and for now it's not really a priority (not mine at least).

If someone want to give it a try, the obvious start would be to make it compile.

**Comment by Peltoche** [comment]
#51 created
