### ISSUE TITLE
Is is possible to insert a space between the icons and the text?

### ISSUE THREAD

**Issue by m4l490n** [Peltoche/lsd#491]
I was wondering if it is possible to insert a space between the icon and the text. I ask this because it seems kind of crammed
![image](https://user-images.githubusercontent.com/22749875/109325375-d6ed5a80-7823-11eb-8722-41b10c03dba9.png)

Is there a way of configuring this without changing the font?

**Comment by meain** [comment]
Should be available in the next release as a config option. https://github.com/Peltoche/lsd/pull/469
