### ISSUE TITLE
Defaulting to human readable leaves the user with no way to get the exact byte length

### ISSUE THREAD

**Issue by gbin** [Peltoche/lsd#492]
I run lsd 0.19.0 on Arch with ls aliased to lsd, I unaliased them to show the differences below.

I tried:
```
$ lsd --classic -la   
drwxr-xr-x gbin gbin  70 B  Fri Mar  5 08:29:43 2021 .
drwxr-xr-x gbin gbin 536 B  Fri Mar  5 08:29:41 2021 ..
.rw-r--r-- gbin gbin 128 KB Thu Mar  4 09:00:51 2021 Mac_ROMs
.rw-r--r-- gbin gbin 128 KB Fri Mar  5 08:28:33 2021 Mac_ROMs_sans_magic
.rw-r--r-- gbin gbin 128 KB Thu Mar  4 09:01:27 2021 vMac.ROM
```

I would expect the same behavior as ls:
```
$ ls -la
total 388
drwxr-xr-x 1 gbin gbin     70 Mar  5 08:29 .
drwxr-xr-x 1 gbin gbin    536 Mar  5 08:29 ..
-rw-r--r-- 1 gbin gbin 131076 Mar  4 09:00 Mac_ROMs
-rw-r--r-- 1 gbin gbin 131072 Mar  5 08:28 Mac_ROMs_sans_magic
-rw-r--r-- 1 gbin gbin 131072 Mar  4 09:01 vMac.ROM
```
(this is a real example where the real size does matter! we have a 4 bytes difference).

I thought I could simply add both the "size_value" and size in the config, but no, the size_value is the bare human readable value with no unit (IMHO it makes no sense here neither as size value will never get parsed as it is inconsistent and you cannot get the unit anyway).
```
S lsd -la
drwxr-xr-x gbin gbin 70   70 B  Fri Mar  5 08:29:43 2021  .
drwxr-xr-x gbin gbin 536 536 B  Fri Mar  5 08:29:41 2021  ..
.rw-r--r-- gbin gbin 128 128 KB Thu Mar  4 09:00:51 2021  Mac_ROMs
.rw-r--r-- gbin gbin 128 128 KB Fri Mar  5 08:28:33 2021  Mac_ROMs_sans_magic
.rw-r--r-- gbin gbin 128 128 KB Thu Mar  4 09:01:27 2021  vMac.ROM
```

**Comment by gbin** [comment]
I found this afterwards:
```
lsd --size bytes
```
But I would argue that `--classic` should still revert completely to the standard ls behavior and `size_value` should always stay as bytes and not randomly change unit. What do you think?

**Comment by meain** [comment]
@gbin Makes sense. We can make `--classic` change size to bytes.
