### ISSUE TITLE
error: The argument '--all' cannot be used with '--directory-only'

### ISSUE THREAD

**Issue by gmagno** [Peltoche/lsd#496]
- os: Arch Linux, kernel 5.10.19
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: alacritty

## Expected behavior
```
ls -lad ./*
drwxr-xr-x 2 gm gm 60 Mar  9 12:25 ./foo
```

## Actual behavior
```
lsd -lad ./*
error: The argument '--all' cannot be used with '--directory-only'

USAGE:
    lsd --all --color <color>... --date <date>... --directory-only --group-dirs <group-dirs>... --icon <icon>... --icon-theme <icon-theme>... --ignore-glob <pattern>... --long --size <size>...

For more information try --help
```

Hello, why can't I list all directories in the current directory?

**Comment by meain** [comment]
`--directory-only` is probably a bad name, it is supposed to be similar to `--directory` in gnu ls which is used to display the directory details instead of its contents. As of now, there is not way for you to just list directories.

**Comment by gmagno** [comment]
Hey, thanks for the reply. You closed the issue, was this fixed?

**Comment by meain** [comment]
`--directory-only` is not to list just directories but to list the directory that you mention. That is why I thought I would close is this issue. For example if you specific `ls -d -l Documents` it gives you size, permissions for Documents instead of contents in them.

**Comment by gmagno** [comment]
Got it.
I had the (wrong) idea that `lsd` aimed at working as a drop-in replacement for `ls`, but that doesn't seem to be the case.

**Comment by meain** [comment]
Well, that statement is true for the most part. `lsd` is `ls` plus some stuff when possible keeping as many options similar to `ls`. `-d` has the same behaviour in GNU `ls` and `lsd`.
