### ISSUE TITLE
[Question] How to disable bold font for directories printing?

### ISSUE THREAD

**Issue by kryzar** [Peltoche/lsd#509]
Hi! Title.

Let me know if I can do anything.

**Comment by zwpaper** [comment]
hi @kryzar , as the theme support is not yet done, you could have done this with `LS_COLORS`, for example, notice the prefix `di=`, and folder bold:

![image](https://user-images.githubusercontent.com/3764335/114970285-bc8f3f00-9eac-11eb-8c15-a5c36d213d11.png)

the value I used is 

```shell
LS_COLORS='di=38;5;33:ln=38;5;44:so=38;5;44:pi=38;5;44:bd=38;5;44:or=38;5;124:cd=38;5;172:ex=38;5;40:fi=38;5;184:no=38;5;245'
```

you could export this env var in `.bashrc` or `.zshrc`

**Comment by kryzar** [comment]
Thanks a lot for your answer (can't wait for theme support and config options!). This does not seem to work:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/31312212/115019545-a045cf00-9eb9-11eb-927e-2c9022032126.png">

**Comment by zwpaper** [comment]
could you try to change the `LS_COLORS` to this, let's make sure whether the `LS_COLORS` working as expected:

```
export LS_COLORS='di=34;5;33:ln=38;5;44:so=38;5;44:pi=38;5;44:bd=38;5;44:or=38;5;124:cd=38;5;172:ex=38;5;40:fi=38;5;184:no=38;5;245'
```

it should change the folder color to Orange:

![image](https://user-images.githubusercontent.com/3764335/115327752-0e440c00-a1c2-11eb-830f-aca8e24d8d72.png)

PS, what is those info for your lsd:

- Version:
- OS:
- How you install LSD

**Comment by kryzar** [comment]
This worked:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/31312212/115377256-ba402400-a1cf-11eb-8b5e-9279188dbbdf.png">


- LSD version: 0.20.1
- OS: macOS Catalina 10.15.7
- LSD installed with: `brew install lsd`

At your service!

**Comment by zwpaper** [comment]
I was really confused updating the `LS_COLORS` 🤣

maybe you could try the simplest version:

```shell
export LS_COLORS='di=34:ln=38;5;44:so=38;5;44:pi=38;5;44:bd=38;5;44:or=38;5;124:cd=38;5;172:ex=38;5;40:fi=38;5;184:no=38;5;245'
```

**Comment by kryzar** [comment]
It works! Thanks a lot, I like it a lot. For the future it would be nice to have an 'no-bold' option or something like that.
