### ISSUE TITLE
Make lsd compile with x86_64-pc-windows-gnu as target

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#51]

**Comment by danieldulaney** [comment]
Hi! I'd love to take on Windows support for lsd.

It looks like a basic approach should be fairly doable. By shimming a couple of functions in the `meta` modules, we can get something that works. However, translating Windows permissions into Unix-style permissions is always tricky.

I stubbed out the required functions here: https://github.com/Peltoche/lsd/compare/master...danieldulaney:windows-support. Let me know if you think this is a good approach, and I'll work on implementation.

**Comment by Peltoche** [comment]
Hello @danieldulaney ,

You approach looks all good to me. I hope to see you PR soon :)

**Comment by danieldulaney** [comment]
#116 proposed to close this.
