### ISSUE TITLE
Feature request: Show extended attributes

### ISSUE THREAD

**Issue by arjvik** [Peltoche/lsd#515]
The original `ls -l` command shows a `+` after the permissions string if an Access Control List (ACL) is present on the file. It would be nice if LSD was able to do the same.

Example:
```shell
$ touch nofacl yesfacl
$ command ls -l
total 0
-rw-r--r-- 1 arjvik arjvik 0 Apr 23 10:45 nofacl
-rw-r--r-- 1 arjvik arjvik 0 Apr 23 10:45 yesfacl
$ setfacl -m u:nobody:rwx yesfacl
$ command ls -l
total 0
-rw-r--r--  1 arjvik arjvik 0 Apr 23 10:45 nofacl
-rw-rwxr--+ 1 arjvik arjvik 0 Apr 23 10:45 yesfacl
```
Note the `+` in the last line.

Would this be possible? I'm not familiar enough with Rust or its standard library to know if it is a simple change or if it will require adding a crate to access that data.

**Comment by meain** [comment]
This would be a nice addition.

**Comment by johnchurchill** [comment]
I agree, this would be useful. I was puzzled for a while when the `+` was not appearing on files I knew had an ACL. Then I remembered that `ls` was aliased to `lsd` on that machine and confirmed that with `/bin/ls -l`.

**Comment by arjvik** [comment]
I think it should be pretty easy to add support to this using the [xattr crate](https://docs.rs/xattr/latest/xattr/) ([source](https://docs.rs/xattr/latest/xattr/)), which has no dependencies except `libc=0.2`, which is already a dependency of `lsd`.

I might take a stab at this in a while when I have some free time to learn Rust.

**Comment by arjvik** [comment]
Thank you @mmatous!
