### ISSUE TITLE
Combining `--almost-all` and `--directory-only` yields an error

### ISSUE THREAD

**Issue by LeuschkeTressa** [Peltoche/lsd#516]
- os: MacOS Big Sur M1/arm (Darwin 20.3.0) 
- `lsd --version`: `lsd 0.20.1`
- `echo $TERM`: `xterm-256color`
- `echo $LS_COLORS`: 

## In short

Options such as `-l -A` is often alias-ed to an `ll` user command, both with `ls` and `lsd` as the underlying program.

With `ls`, invoking `ll -d .` (to list the directory itself rather than its contents) then works fine, however, with `lsd`, invoking `ll -d .` will give an error.

The relevant options, from `lsd --help`:

```
    -a, --all               Do not ignore entries starting with .
    -d, --directory-only    Display directories themselves, and not their contents (recursively when used with
                            --tree)
```

Illustration below is done without alias for clarity.

## Example - prepare test

```bash
$ # prepare:
$ mkdir temp && cd temp
$ touch file && mkdir .dot-dir
$
$ # So now we have a directory with one file and one hidde folder:
$ \ls -l -A
drwxr-xr-x@ 2 user  staff  64 Apr 27 13:20 .dot-dir
-rw-r--r--@ 1 user  staff   0 Apr 27 13:20 file
$ #
$ # ...or with lsd:
$ lsd -l -A
drwxr-xr-x user staff 64 B Tue Apr 27 13:20:23 2021  .dot-dir
.rw-r--r-- user staff  0 B Tue Apr 27 13:20:23 2021  file
```

## Example - expected behavior

```bash
$ lsd -l -A -d .   # typically invoked as ll -d .
drwxr-xr-x@ 4 user  staff  128 Apr 27 13:20 .
```

...which is what ls gives:

```bash
$ \ls -l -A -d .   # typically invoked as ll -d .
drwxr-xr-x@ 4 user  staff  128 Apr 27 13:20 .
```

## Example - actual behavior

```bash
$ lsd -l -A -d .   # typically invoked as ll -d .
error: The argument '--almost-all' cannot be used with '--directory-only'
[...]
```

**Comment by meain** [comment]
Even though this does really make much sense as `-d` and `-A` enable two separate things, I think just making `-d` reset any `-A` flags previously would be a good idea. `ll` is probably an alias that a lot of people will have plus gnu ls seems to do this anyways.

**Comment by meain** [comment]
This I believe is now fixed.
