### ISSUE TITLE
Configurable icon size plz

### ISSUE THREAD

**Issue by FlyinCow** [Peltoche/lsd#518]
![image](https://user-images.githubusercontent.com/23637371/117409724-17fc9c00-af44-11eb-9e3f-b61b2c559cd4.png)
Bad icon size for dirs. Env: Alacritty + Archlinux+Xorg+bspwm, with a 2560*1600 display.

**Comment by FlyinCow** [comment]
BTW when use `theme: unicode` the icon size works fine but I just want fancy icons.

**Comment by meain** [comment]
Icon size is not something that lsd can control. This is probably an issue with the font that you are using. Try with a different font and see if this issue is still present.
https://www.nerdfonts.com/font-downloads

**Comment by meain** [comment]
I am closing this issue as icon size is not something that lsd controls. Feel free to reopen this if you think if there is something else.
