### ISSUE TITLE
Support for 32bit linux systems

### ISSUE THREAD

**Issue by shashank-brdj** [Peltoche/lsd#523]
Hello, i really love this project and i use it on two of my linux distros. However i have an old toshiba laptop on which i installed 32bit linux (peppermint) recently. Im trying to find lsd for this laptop and im unable to. The snap version is old and broken. And i cannot install amd64 or x86_64 versions, as mine is 32bit os.
It would be great if there is support for 32bit os. Atleast one release would do.
Since it isnt obsolete, it would help spice up the old pc's and look really great.
Thank you :D

Edit:
I did notice that up till **0.17.0**, the 32bit versions are available. It would be great if a new version was released after that.
I do understand if its not possible.
Just a request.
Good Day

**Comment by zwpaper** [comment]
Hi @shashank-brdj , the `i686` should be the `32 bit` release for what you seeking, maybe you could try it and update the result here

https://github.com/Peltoche/lsd/releases/tag/0.20.1

**Comment by shashank-brdj** [comment]
Thank you for your reply, i apologise for my lack of knowledge, i use i386 peppermint on my old toshiba laptop, i tried to install i686  version and it didnt work. I mistook i686 as 64bit. I understood now, my supported version is till 0.17.0 i386. And its working fine. I tested i686 on my other slightly newer cpu which has i686 ..and its working great. Thank you
Take care
