### ISSUE TITLE
Custom date - expected string format

### ISSUE THREAD

**Issue by robole** [Peltoche/lsd#527]
Hi,

Thank you for your hard work. It is a great app.

I wanted to make a customised date format. It's not clear what I should write:

```
classic: false

# == Date ==.
# Possible values: date, relative, +<date_format>
date: '%d %b %y %X'
```

I was expecting this config to give me a date such as "10 Jun 21 13:01:00".

What am I missing?

**Comment by meain** [comment]
You are missing a `+` in front. We require that for a custom date format.

```yaml
date: '+%d %b %y %X'
```

**Comment by robole** [comment]
hi @meain 

thanks for the feedback. it also required me to update to the latest for this to work. i had installed lsd as a snap which is still at v0.16.0.
