### ISSUE TITLE
TeX icon not visible enough 

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#53]
By @alaymari from #42 

Regarding the icons, I noticed that the TeX file has an icon which is so thin, it is nearly invisible. Can a different icon be set for that; maybe the txt file icon itself would be better than the existing one.

**Comment by alaymari** [comment]
I have made a svg of tex-file-icon (sort of) which is similar to the prescription file icon of font-awesome. 
Can that be used as TeX file icon?

![file-tex](https://user-images.githubusercontent.com/34280138/50006680-8b4c8e80-ffd4-11e8-84c1-4407fc52acf4.png)

**Comment by Peltoche** [comment]
I don't think it's possible to integrate easily icons from an another source than the nerd-font icons.

As this issue is open since a while and nobody have reacted on it it doesn't seems to be an issue so I close it. Don't hesitate to reopen it if needed.
