### ISSUE TITLE
Poor performance because of use of read_link to test for symlinks.

### ISSUE THREAD

**Issue by al45tair** [Peltoche/lsd#538]
- os: macOS
- `lsd --version`: 0.20.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

## The problem
`lsd` can be very slow, particularly on remote directories, because of the code in `meta/mod.rs` that does things like

```rust
let metadata = if read_link(&path).is_ok() {
  path.symlink_metadata()
} else {
  path.metadata()
}
```

The issue is that `read_link` itself is expensive. The irony is that `path.symlink_metadata()` works on non-symlinks, so this code was pointless and might just as well have been `let metadata = path.symlink_metadata()`.

There's a similar bit of code in `from_path()` that needs to be slightly more complicated because of `dereference`, but essentially has the same problem; that code does want to fetch both bits of metadata if it's a symlink, but since `path.symlink_metadata()` will tell you (via `file_type().is_link()`) whether it's a symlink or not, it's easy enough to just call `path.metadata()` as well in that case.

I'd send a PR, but my employer's policies on Open Source make that difficult, so I'm afraid you'll just get a bug report.

**Comment by meain** [comment]
Thanks for the issue @al45tair :)
