### ISSUE TITLE
icon not display well in macOS

### ISSUE THREAD

**Issue by CC2130** [Peltoche/lsd#542]
- os: mac
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

## Expected behavior
when run `lsd -alh` should show the icons

## Actual behavior
like that（something like a framed question mark):
```
 $ lsd -alh
drwxr-xr-x chao wheel 416 B  Wed Aug 18 16:50:11 2021  .
drwxr-xr-x chao wheel 576 B  Wed Aug 18 16:22:06 2021  ..
.rw-r--r-- chao wheel  11 KB Wed Aug 18 16:22:06 2021  app.rs
.rw-r--r-- chao wheel 7.4 KB Wed Aug 18 16:22:06 2021  color.rs
.rw-r--r-- chao wheel  10 KB Wed Aug 18 16:22:06 2021  config_file.rs
.rw-r--r-- chao wheel 4.7 KB Wed Aug 18 16:22:06 2021  core.rs
```

**Comment by jgte** [comment]
I also get this.

**Comment by meain** [comment]
Just make sure you have proper fonts installed. Check to the linked issue.
Ref: https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334
