### ISSUE TITLE
Doesn't present icons

### ISSUE THREAD

**Issue by Rassska** [Peltoche/lsd#543]
- os : `Ubuntu 20.04 LTS` 
- `lsd --version`:  `0.20.1`
- `echo `$TERM: `xterm-256color`
- `echo $LS_COLORS`: 

Hi, there! 
I have no idea about this issue, can someone determine what is the problem here?
![Screenshot from 2021-08-20 13-45-25](https://user-images.githubusercontent.com/73281386/130222514-15508f78-349e-4d77-8fe7-b353179618a9.png)

**Comment by meain** [comment]
Download an install a font from nerd-font (https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md#font-installation) and make sure your terminal emulator is using the font that you installed.
We make use of special glyphs which are only available in certain fonts to show you the icons.

**Comment by Rassska** [comment]
> Download an install a font from nerd-font (https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md#font-installation) and make sure your terminal emulator is using the font that you installed.
> We make use of special glyphs which are only available in certain fonts to show you the icons.

Kudos :D
