### ISSUE TITLE
missing leading dot on directories

### ISSUE THREAD

**Issue by tzimme** [Peltoche/lsd#553]
When showing hidden directories lsd outputs a space instead of a leading dot, including the parent directory entry. 

A dot is shown in front of hidden files though.

![Untitled](https://user-images.githubusercontent.com/16401082/133924933-69a462f7-3aaf-44d1-8d38-7435b3e3325e.png)

**Comment by meain** [comment]
This is most probably an issue with the color or font and not lsd. Could you try doing `lsd -l --color never --icon never` and see if you are still having the issue?

**Comment by just-barcodes** [comment]
I observed the same bug of missing dots and fixed it by fixing my fonts.

It has something to do with uneven sizes of the icons. I checked this by temporarily using this as `config.yaml`:
```
icons:
  separator: " \t"
```

It showed the dots correctly (with some additional space) but it was also obvious that the hidden folders weren't correctly aligned to the rest of the files when listed.
