### ISSUE TITLE
Weird icons

### ISSUE THREAD

**Issue by JakobMiesner** [Peltoche/lsd#564]
- os: Ubuntu 20.04.2 LTS
- `lsd --version`:  lsd 0.20.1
- `echo $TERM`: xterm-256color

## Expected behavior
lsd shows folder icons 

## Actual behavior
lsd shows this character " Desktop", as can be seen in a screenshot (It seems like my chrome can not even display it).
![image](https://user-images.githubusercontent.com/36001913/137222782-6824c7fa-77e2-4368-afff-2cae03ac838f.png)

Other icons seem to be broken too:
![image](https://user-images.githubusercontent.com/36001913/137222912-82b10ffe-847b-4a16-a9c5-0e9085c431b2.png)

**Comment by zwpaper** [comment]
this is always because of the font, make sure you installed a [Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md), [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack) for example
