### ISSUE TITLE
lsd not reading the config file

### ISSUE THREAD

**Issue by greweln** [Peltoche/lsd#566]
Please excuse my ignorance but how can I get lsd to read the config & theme file?
I install it with cargo and I do have a ~/.config/lsd/config.yml  and  ~/.config/lsd/themes/my_theme

thanks

**Comment by meain** [comment]
1) You have to build from `master`. Themes is not yet in a release.
2) Have this is `~/.config/lsd/config.yaml`
```
color:
  when: auto
  theme: mytheme
```
3) Have theme in `~/.config/lsd/themes/mytheme.yaml` (`.yaml` at the end)
