### ISSUE TITLE
If the file name starts with "_" then instead of "_" just a space.

### ISSUE THREAD

**Issue by DaniilS-Portfolio** [Peltoche/lsd#568]
I have a project with sass elements and their names begin with "_". When output through "ls" everything is correct, and through "lsd" instead of "_" - a space.

![изображение](https://user-images.githubusercontent.com/74107094/137353200-a8b576d3-5ca2-4b56-af49-89f21c6ad224.png)

Manjaro KDE
Terminal: Konsole

**Comment by DaniilS-Portfolio** [comment]
* What is the lsd version?
 0.20.1

* Could you try with `lsd --color never --icon never --ignore-config` and see if it is showing?
AND
* bout when you do `lsd --oneline --ignore-config`?
In the screenshot below

![изображение](https://user-images.githubusercontent.com/74107094/137590662-9bab9628-1964-409f-aa40-6236124afe15.png)

---

> Could you also copy paste the output you have in the screenshot here.

When I copied it was when inserting the underscore. Now I think it's about the font. I went to the `tty2` terminal window and entered the `lsd` command in the same directory and there were underscores. If you know, could you tell me why this happens in the kde `Konsole` terminal?

And so the problem is in Konsole, not in this utility.

**Comment by meain** [comment]
I am not entirely sure why this is happening, but your conclusion that it is a font issue is correct. Most probably a bug in how Konsole renders any multi width glyphs. Maybe try changing the font. 
Related: https://github.com/Peltoche/lsd/issues/429
