### ISSUE TITLE
`/srv` Content Not Getting Listed

### ISSUE THREAD

**Issue by cansurmeli** [Peltoche/lsd#577]
- os: CentOS Stream 8
- `lsd --version`: 0.16.0
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:

Hello.

I'm was trying to list the contents of my `/srv` directory with `lsd` and it doesn't list anything at all. When I tried to `mv` or `cp`, they all complained that the files/directories existed but `lsd` showed it empty under `/srv`. I switched back to `ls` and everything is listed as normal.

It's very weird as the content under `/srv` belong to my user. However, `lsd` works fine under my home directory.

I wanted to provide more information for debugging but couldn't figure out besides what I've provided above.

Thanks.

**Comment by zwpaper** [comment]
hi，@cansurmeli, I noticed your lsd version is 0.16, and the newest one is 0.20.1, can you update it and verify if it works for the newest version. 

Also, maybe sharing the output of the GNU ls `ls -l /srv` could give us some clues.

**Comment by cansurmeli** [comment]
@zwpaper 

Hey, sorry, should've mentioned. Since I'm on CentOS, I have installed `lsd` via Snap Store and 0.16.0 is the latest version there. Any chance on an update?

**Comment by meain** [comment]
We were having a lot of issues with Snap and so was discontinued.

**Comment by cansurmeli** [comment]
Alright, on which repo are you available on `dnf`?

**Comment by zwpaper** [comment]
I am not familiar with `dnf`, but we should be available in `fedora`, check https://github.com/Peltoche/lsd#installation

what's more, the simplest way should be download the binary directly here https://github.com/Peltoche/lsd/releases, and `mv lsd /usr/local/bin`:

**Comment by sklages** [comment]
Or build it own your own (in case `dnf` is not an option):
```bash
cargo install lsd
```

**Comment by meain** [comment]
Closing this as this is just a snap issue.
