### ISSUE TITLE
Some file extensions have odd icons (Like npm logo for .c files)

### ISSUE THREAD

**Issue by embeddedpenguin** [Peltoche/lsd#578]
- os: 5.14.16, arch linux
- `lsd --version`: 0.20.1
- `echo $TERM`: alacritty
- `echo $LS_COLORS`: No output

## Expected behavior
Not sure how to define expected behavior because I'm not sure what icons should go with what file extensions. I think this is less of a bug and more of a configuration problem (maybe?).

## Actual behavior
![image](https://user-images.githubusercontent.com/33668314/141540216-c5898355-681c-44be-902c-6615abf8a911.png)
![image](https://user-images.githubusercontent.com/33668314/141540157-fdaa8b96-f78f-43a7-b88e-caf3eb81e390.png)

Is there a way for me to match extensions with expected icons?

**Comment by zwpaper** [comment]
It may be a font problem, could you try to change your nerd font to something like `Hack Nerd Font`

**Comment by embeddedpenguin** [comment]
That fixed it! Sorry for the late response.
