### ISSUE TITLE
color theme file not working

### ISSUE THREAD

**Issue by samEngineering** [Peltoche/lsd#581]
As instructed, I made a .yaml file for the color theme at ~/.config/lsd/themes, but I still get the default theme. I tried changing all colors the same color that I knew should work, but nothing happened. My config file is working, which is at ~/.config/lsd/config.yaml. I tried color:
  when: always
  theme: ~/.config/lsd/themes/AtomOneDark

and Also 

color:
  when: always
  theme: ~/.config/lsd/themes/AtomOneDark.yaml

and also I tried "when: auto" but nothing worked for me :(
Everything else is awesome tho!

**Comment by zwpaper** [comment]
hi @samEngineering, the theme is not yet released, please check https://github.com/Peltoche/lsd/issues/575, I will look into it this weekend if free

**Comment by samEngineering** [comment]
Oh, okay :) No rush, and thanks for the update 👍 looking forward to this
feature!

- Best, SL
