### ISSUE TITLE
Incompatible CLI parameters `--all` and `--directory-only` / Inconsistent behavior w.r.t. original `ls`

### ISSUE THREAD

**Issue by liar666** [Peltoche/lsd#582]
- os: Linux Mint 20.2
- `lsd --version`:  lsd 0.20.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.

If I define `alias ls='ls -ahl --color'` and then use `ls -d *`, this works and lists all the names of the directories in my current dir (even those starting with `.`) but not their contents. This is what is expected from `-a` and `-d` CLI parameters.

I would expect the same behavior from `lsd`

## Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.

When I define `alias ls='lsd -ahl --color auto'`, and I attempt to run `ls -d *`, I get `error: The argument '--all' cannot be used with '--directory-only'`.

Fist of all, this behavior is inconsistent with the behavior of original `ls`.
Second, I don't see why these CLI parameters would be incompatible. Indeed, original `ls` behavior seems reasonable. Thus I would expect `lsd` to consider them compatible too.

**Comment by Gasu16** [comment]
As a beginner user, my theory is that in the file src/app.rs the following piece of code is responsible for this behavior
```
Arg::with_name("directory-only")
                .short("d")
                .long("directory-only")
                .conflicts_with("all")
                .conflicts_with("almost-all")
                .conflicts_with("depth")
                .conflicts_with("recursive")
                .help("Display directories themselves, and not their contents (recursively when used with --tree)"),
```

**Comment by zwpaper** [comment]
hi @Gasu16, yes, you get the point right! and we still need to check if the output behavior matches the `GNU ls`.

a PR is welcome if you could help to check it and validate the output!

also don't forget to add a test after the implementation.

**Comment by Gasu16** [comment]
> hi @Gasu16, yes, you get the point right! and we still need to check if the output behavior matches the `GNU ls`.
> 
> a PR is welcome if you could help to check it and validate the output!
> 
> also don't forget to add a test after the implementation.

Hi!
I am currently working on the implementation to solve this issue, if everything goes fine soon I will send the first PR, trying to make the output behavior matching the `ls` command.

**Comment by Gasu16** [comment]
@zwpaper should I merge it in the master branch?

**Comment by Gasu16** [comment]
Hi @zwpaper I pushed my PR which solves the problem, feel free to check it and let me know if there are any problems with it.

**Comment by zwpaper** [comment]
fixed by https://github.com/Peltoche/lsd/pull/587
