### ISSUE TITLE
Maybe not an issue.

### ISSUE THREAD

**Issue by ljramalho** [Peltoche/lsd#584]
- os: raspbian 
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

I have lsd installed on my raspberry pi / raspbian. I access my Pi using KiTTY 0.76.0.1 (a PuTTY clone) for windows. On windows I have installed Hack Nerd font.

There are 4 file types for the Hack font, and depending on the one I have installed (mono or variable-pitch), and while the glyph letters are the same, the glyphs for the icons (like the "open folder"  echo $'\uf115'), is either to small to be seen correctly:

Hack_Regular_Nerd_Font_Complete_Mono_Windows_Compatible.ttf (mono)
![image](https://user-images.githubusercontent.com/10247779/142341857-b053bc81-75bd-4344-853b-f7e4fc5abf15.png)

 or with the required size but cut on both sides, as if the glyph is to large and then is only showed partially in the reserved "mono"/fixed spaced.

Hack_Regular_Nerd_Font_Complete_Windows_Compatible.ttf (variable-pitch).
![image](https://user-images.githubusercontent.com/10247779/142341407-891827d9-8b23-4257-bdbe-d689854e0c39.png)

Watching the example image from the lsd main page...
![image](https://user-images.githubusercontent.com/10247779/142342154-3de2a160-74e0-4210-b09e-b5b6425cb389.png)

It seems you are not using the Hack nerd font (the zero in your image is slashed).
It seems you are using the font size 10, while I'm using font size 11 (but if I use font size 10 result is the same).
It seems your terminal displays the icon glyphs using the space of two characters (by watching the folder glyph under the lsd text.

Question;
1- What terminal emulator were you using when took the image? is it for windows, Linux or MacOS?
2- What font were you using when took the image?

3- Is there any solution for the icons problem in my system?

Thanks and sorry my lousy English

**Comment by zwpaper** [comment]
hi @ljramalho, thanks for trying lsd on raspbian, how the icon shown is not lsd can handle currently, so most of the display questions you mentioned should be some OS configuration questions.

for your questions, I can show you my screenshot:

![image](https://user-images.githubusercontent.com/3764335/142347859-ae528864-0dfc-4f1a-b13d-19df2a9d76ce.png)

1. iTerm2 on macOS
2. Hack Nerd Font
3. Can you try using another terminal emulator? maybe there is something wrong related to KiTTY https://github.com/kovidgoyal/kitty/issues/527

**Comment by ljramalho** [comment]
Thank you zwpaper for the quick reply.

It seems there is a problem on KiTTY / PuTTY terminal. There is an option to allow for variable pitch fonts selection, but they are rendered as monospaced, compressing or cutting the large width glyphs (like the "m") and showing a bigger space in narrow glyphs (like "l").

I asked in the "lsd" issues, if there is some option (hidden option) to render variable-pitch fonts. In  fact it seems the letter glyphs in Hack nerd fonts (variable pitch variant) are monospaced anyway except for the added powerline glyphs, so if KiTTY / PuTTY could render variable pitch fonts correctly the letter characters should look good and the extra Powerline glyphs when used correctly should look like in your image example.

Thank you

**Comment by meain** [comment]
Rendering is something that is fully handed by the terminal emulator. Nothing can be done by lsd there.
Also take a look at this issue: https://github.com/Peltoche/lsd/issues/331

**Comment by meain** [comment]
Closing this as this is a terminal emulator specific issue.
