### ISSUE TITLE
Some directory name are not showed entirely

### ISSUE THREAD

**Issue by astrale-sharp** [Peltoche/lsd#586]
- os: 
```bash
❯ screenfetch 

 ██████████████████  ████████     astrale@zz
 ██████████████████  ████████     OS: Manjaro 21.1.6 Pahvo
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.70-1-MANJARO
 ██████████████████  ████████     Uptime: 1d 2h 16m
 ████████            ████████     Packages: 1394
 ████████  ████████  ████████     Shell: fish 3.3.1
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.87.0 / Plasma 5.22.5
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breath2
 ████████  ████████  ████████     Disk: 285G / 361G (83%)
 ████████  ████████  ████████     CPU: AMD Ryzen 7 4800H with Radeon Graphics @ 16x 2.9GHz
 ████████  ████████  ████████     GPU: AMD RENOIR (DRM 3.40.0, 5.10.70-1-MANJARO, LLVM 12.0.1)
                                  RAM: 5271MiB / 15463MiB
```
- `lsd --version`: 
```bash
❯ lsd --version
lsd 0.20.1
```
  - `echo $TERM`:
  xterm-256color 
- `echo $LS_COLORS`: 
```bash
❯ echo $LS_COLORS

```
## Expected behavior && Actual behavior
Show all directory even short ones that starts with a number : let's compare with ls
```bash
❯ lsd
    6   66ee   e
```

```bash
❯ ls
5  66  66ee  6e
```

Notice that some characters (numbers that starts the directory name) do not appear (although when you copy them from the terminal they are here!)

**Comment by zwpaper** [comment]
hi @astrale-sharp, this is always a `font` or `terminal` problem, could your try to change your font to `Hack Nerd Font` or use another terminal emulator.

Fonts rendering is not something could be handled by `lsd`

there are some related issues:

- https://github.com/Peltoche/lsd/issues/553#issuecomment-922462347
- https://github.com/Peltoche/lsd/issues/568
- https://github.com/Peltoche/lsd/issues/429

**Comment by Gasu16** [comment]
Hi @astrale-sharp 
If I remember correctly I had the same issue in my distro (Arch Linux) and solved installing awesome-terminal-fonts package.
