### ISSUE TITLE
Some icons are missing or rendering wrong

### ISSUE THREAD

**Issue by isak102** [Peltoche/lsd#588]
- os: linux
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: xterm-kitty

Some icons dont show up, for example icons that have the .sh and .hs extension. I have nerd fonts and fontawesome installed. As you can see, the majority of icons are showing up properly but not all. Is there a way to manually add extra icons in a config file? 
![image](https://user-images.githubusercontent.com/90389894/143031835-907207ac-7c8a-4f49-a6c3-8b2c09549744.png)

**Comment by zwpaper** [comment]
this is always because of the font, make sure you installed a [Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md), [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack) for example

**Comment by isak102** [comment]
> this is always because of the font, make sure you installed a [Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md), [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack) for example

I have Hack Nerd Font installed and those same icons are still missing :/

**Comment by zwpaper** [comment]
both icon size and icon content is controlled by fonts or terminal emulator too, so your solution is still to update the fonts or terminal config.
