### ISSUE TITLE
Fixing -t option according to the GNU ls behaviour

### ISSUE THREAD

**Issue by Gasu16** [Peltoche/lsd#590]
- os: Arch Linux
- `lsd --version`: lsd 0.20.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

Not really an issue, sounds more like a suggestion, feel free to consider it or no.

## Expected behavior
When I run the `lsd -t` command, according to the original `ls -t` behaviour, I expect to list the files in one single column, one file per line (like the `-1` option) since the GNU `ls -t` command already does it by default.

## Actual behavior
Depending on the amount of files to be listed, it can split the list in two columns, this however does not respect the original GNU `ls -t` behaviour as described above.

**Comment by zwpaper** [comment]
I have checked the manpage and found:

> -t     sort by time, newest first; see --time

ref: https://man7.org/linux/man-pages/man1/ls.1.html

Did I get you wrong?

**Comment by Gasu16** [comment]
Yes, the output is correct, nothing is wrong; what I mean is that it is displayed in a different way, the GNU `ls -t` shows all in one column, on the other hand the `lsd -t` command displays the output in two different columns (if, of course, the amount of entries to display is big enough to trigger a second column to appear).

**Comment by zwpaper** [comment]
could you paste some examples?

it seems in a grid view when I tested locally

![image](https://user-images.githubusercontent.com/3764335/143842938-3bdde834-b958-4041-8f07-e6b5141954f0.png)

**Comment by Gasu16** [comment]
Sure, this is what I mean
### With GNU ls 
```
[matt@archlinux test]$ ls -t
 Dir1
 Dir2
 Dir3
 Dir4
 Dir5
 Dir6
 Dir7
 Dir8
 Dir9
 Dir10
 Dir11
 Dir12
 Dir13
 Dir14
 Dir15
 Dir16
[matt@archlinux test]$
``` 
### With lsd
 ```
[matt@archlinux test]$ lsd -t
 Dir1                                    Dir11
 Dir2                                    Dir12
 Dir3                                    Dir13
 Dir4                                    Dir14
 Dir5                                    Dir15
 Dir6                                    Dir16
 Dir7
 Dir8
 Dir9
 Dir10
[matt@archlinux test]$
```

**Comment by zwpaper** [comment]
what's your GNU ls version?

it is strange that my `GNU ls` arrange the result in grid mode:

```console
root@235be0e82ad0:/# ls --version
ls (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
root@235be0e82ad0:/# ls -t
dev  proc  sys  etc  lsd  tmp  go  root  bin  sbin  lib  lib64  run  var  media  mnt  opt  srv  usr  boot  home
```

**Comment by Gasu16** [comment]
Your output is the same as mine, my usecase triggers only when GNU ls should list an huge amount of files and dirs.
BTW mine is 9.0
```
[matt@archlinux ~]$ ls --version
ls (GNU coreutils) 9.0
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
[matt@archlinux ~]$
```

**Comment by zwpaper** [comment]
Hmmm, let me try to explain myself more precisely, how can I reproduce the difference between `lsd -t` and `ls -t`?

can you show me an example so that I can let `ls -t` list output in a one-column style?
