### ISSUE TITLE
Add a --count option

### ISSUE THREAD

**Issue by Gasu16** [Peltoche/lsd#593]
So basically what I want to do is to implement a flag `lsd --count` which displays the current number of files and directories in a given path.
If this usecase is acceptable for the maintainers, I will proceed to implement it and open a new PR for it.

**Comment by meain** [comment]
I don't really see a good usecase for this to be frank. This is probably something that is better served by piping the output of lsd to something like wc.

There was however some discussion around adding a --summary flag to mimic lscolors functionality but nothing solid has been decided yet.

**Comment by Gasu16** [comment]
Happy to give my contribute in any possible way. 
However I seize the opportunity to ask how I should implement such a function of a new flag.
I know I should add the flag inside the src/app.rs file, but where should I write its own implementation?

**Comment by meain** [comment]
https://github.com/Peltoche/lsd/issues/112#issuecomment-460040371 is the item that I was mentioning. We still have to decide on what gets displayed and where.

@Gasu16 I would like to understand what your usecase is. Just to understand what you are expecting this feature to do, so that we can have a clearer understanding on what should go in there.

**Comment by Gasu16** [comment]
You got me wrong, what I meant is to understand better how the code works, and asked how to add the implementation for a new functionality (flag), not for my usecase in particular, but generically.

**Comment by meain** [comment]
I understood you. It is just that we don't have a solid idea on what the feature should provide. Since you requested a similar feature I thought I would ask you what your usecase is so that we can probably better understand what needs to be build.

**Comment by Gasu16** [comment]
Well, I'm glad if I could give any help on the feature you previously mentioned (--summary), or anything else.

**Comment by zwpaper** [comment]
Hi @Gasu16, we do not have the guide you mentioned, you could check the code directly, it is not that difficult and is always update-to-date.

as a quick start:

main logic:

1. main starting here https://github.com/Peltoche/lsd/blob/master/src/main.rs#L91
2. flags are parsed here https://github.com/Peltoche/lsd/blob/master/src/main.rs#L116
3. `core` is called here https://github.com/Peltoche/lsd/blob/master/src/main.rs#L119 and impl here https://github.com/Peltoche/lsd/blob/master/src/core.rs#L77
4. flags will be used in `fetch` here https://github.com/Peltoche/lsd/blob/master/src/core.rs#L84 and `display` here https://github.com/Peltoche/lsd/blob/master/src/core.rs#L137

flags are types defined here https://github.com/Peltoche/lsd/blob/master/src/flags.rs and here https://github.com/Peltoche/lsd/tree/master/src/flags

**Comment by zwpaper** [comment]
as this issue is not valid anymore, closing, feel free to open it if there are any other problems.

**Comment by zwpaper** [comment]
also, if you want to find something to start, `good first issue` is always your friend https://github.com/Peltoche/lsd/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22
