### ISSUE TITLE
--icon-theme unicode showing only questionmarks

### ISSUE THREAD

**Issue by Mellbourn** [Peltoche/lsd#595]
Hi, thanks for a great tool!

`lsd` is working well for me with Nerd Fonts set up.

However, it might be even prettier if it actually used the colorful unicode icons, e.g. 📁.

I would have guessed that `lsd --icon-theme unicode` would achieve that, but it only shows question marks for me:

![image](https://user-images.githubusercontent.com/1785727/145389483-908baf8c-9932-4f72-846e-874c532ec83e.png)

This is `lsd` 0.20.1 installed using `brew` on macOS Big Sur 11.6.1 (running on an m1 MacBook) running inside iTerm2 3.4.12 (but it behaves the same in Terminal 2.11).

I am able to display unicode icons using `echo`
![image](https://user-images.githubusercontent.com/1785727/145390411-3398ae54-cbbe-40b8-8058-743f4b6a4324.png)

Is this a bug, or is there some configuration I need to do?

**Comment by zwpaper** [comment]
did some investigation, looks like a bug, `unicode` has fewer use cases, maybe need some check and updates.

**Comment by mcaubrey** [comment]
Also came here to report this. In both iTerm and Kitty I'm using a font called Ricty Diminished with Fira Code, it is basically a Fira Code offshoot that supports Japanese text.

In iTerm, for whatever reason its all question marks.
In Kitty, it sometimes ends up appearing as Chinese/Japanese characters.

Here's some screenshots from iTerm.
<img width="1219" alt="Screen Shot 2021-12-15 at 10 13 19" src="https://user-images.githubusercontent.com/14105176/146104843-f9944794-5550-49cf-84d8-e17435ff0ed8.png">
<img width="897" alt="Screen Shot 2021-12-15 at 10 14 03" src="https://user-images.githubusercontent.com/14105176/146104859-de65aef8-e572-4204-9125-e42b7acfb2a1.png">

Here's some screenshots from Kitty.
<img width="824" alt="Screen Shot 2021-12-15 at 10 13 37" src="https://user-images.githubusercontent.com/14105176/146104879-5a65374f-12a3-4893-a1c3-6e9a7f9d53a9.png">
<img width="652" alt="Screen Shot 2021-12-15 at 10 13 48" src="https://user-images.githubusercontent.com/14105176/146104896-1fd3095a-bd21-45fa-afb7-738eeb3a9530.png">

I'm on a 2019 Intel Macbook Pro running Macos Monterey. lsd was installed using brew.

**Comment by zwpaper** [comment]
Hi @mcaubrey, thanks for the report, but It seems that you were facing a different problem with the font, lsd have to use a patched font with emoji support, please check https://github.com/Peltoche/lsd#prerequisites.

**Comment by mcaubrey** [comment]
Thanks! I'll check that out.

**Comment by mcaubrey** [comment]
@zwpaper 
I'm just reporting back to say you were right, the steps suggested on https://github.com/Peltoche/lsd#prerequisites have worked perfectly for me.

<img width="1066" alt="Screen Shot 2021-12-16 at 14 27 34" src="https://user-images.githubusercontent.com/14105176/146313613-a5c4cc3e-4227-40c5-acf6-e5b5f122d97d.png">

**Comment by Mellbourn** [comment]
Just gentle reminder that the original issue was actually _not_ the same as that of @mcaubrey and the fix for his problem did not fix the original problem.

**Comment by zwpaper** [comment]
Hi @Mellbourn, sorry for the later reply, I finally found out that the Unicode we used in lsd is version 7.0, and it may have some render problems.

I can reproduce it on my mac, but not yet figured out how to render the 7.0 unicode.

for example:

- we used the folder [1F5C0](https://www.compart.com/en/unicode/U+1F5C0) it also does not render well in my browser
- I try to use a previous version one [1F4C1](https://www.compart.com/en/unicode/U+1F4C1), it works as expected.

BUT! please notice, unicode icon theme is not well implemented, we only have the file and folder icons.

@meain how about we change the default Unicode back to version 6, it may add much more compatibility to lsd.

also, BTW, I am trying to work on the icon theme, I may leave a seat for unicode theme, then it will have a chance to create a custom unicode icon theme.

**Comment by meain** [comment]
Just a personal opinion, switching to `1f4c1` drops the "terminally" feeling as it looks more like an emoji.

**Comment by zwpaper** [comment]
although I am not one of the target users, the Unicode option is designed to act like that with colorful glyphs?

check [starship](https://starship.rs/presets/#no-runtime-versions) for example

<img width="441" alt="image" src="https://user-images.githubusercontent.com/3764335/180953014-d98e2648-df62-4279-af8c-fbc5e72c109c.png">

**Comment by meain** [comment]
I think if we can stick to non color glyphs, it would be better. But since `unicode` is more of a fallback (at least in my mind), if there is no other good option, we can switch to color glyphs.

**Comment by zwpaper** [comment]
IMHO, Unicode is act more like another option according to the `--icon-theme` option.

the real problem like this issue is that we are now offering a non-functional feature `--icon-theme unicode`, it may not work on most OSes, that is why I think we should use a more compatible default code.

**Comment by meain** [comment]
I see your point, but I am still not yet fully convinced that adding color glyphs is the best approach (Apart from changing the looks, I have seen quite a few terminal emulators having issues with rendering multi-color emojis, but I guess those will just render monochrome versions). Let me take another look into this in the coming days and we can finalize one something.

**Comment by meain** [comment]
I think we will leave the unicode icons as is. The original issue was around being able to use emojis (colorful unicode icons) as icons in lsd. That I think would be covered once we have https://github.com/Peltoche/lsd/pull/707 .
