### ISSUE TITLE
Permission denied (os error 13) for drwx------ folders

### ISSUE THREAD

**Issue by mizzunet** [Peltoche/lsd#597]
- os: 
- `lsd --version`: 0.20.1
- `echo $TERM`: xterm-kitty
- `echo $LS_COLORS`: N/A

## Expected behavior
```
 /v/log  /usr/bin/ls 
audit		 btmp	  lastlog  pacman.log	snapper.log
auto-cpufreq.log  journal  old	   private	wtmp
```

## Actual behavior
```
lsd: ./audit: Permission denied (os error 13).

lsd: ./private: Permission denied (os error 13).

 audit              btmp      lastlog   pacman.log   snapper.log
 auto-cpufreq.log   journal   old       private      wtmp
```

Here, I'm having this ` Permission denied (os error 13).` for folder having `drwx------`, if the current directoy has it or even shows for subfolders,
```
 ~/.local  lsd
...
...
lsd: ./share/waydroid/data/user_de/0/com.google.android.tts: Permission denied (os error 13).

lsd: ./share/waydroid/data/media: Permission denied (os error 13).

lsd: ./share/waydroid/data/cache/lost+found: Permission denied (os error 13).

lsd: ./share/waydroid/data/adb: Permission denied (os error 13).

lsd: ./share/waydroid/data/adbroot: Permission denied (os error 13).

lsd: ./share/waydroid/data/gsi: Permission denied (os error 13).

lsd: ./share/waydroid/data/ssh: Permission denied (os error 13).

 AppImages   ChromiumWebStore   fonts   medium   share
 bin         fontconfig         lib     opt      state
```

I haven't enabled `recursion`, so `lsd` shouldn't be looking for the recursive folders, right? But it seems does. I think that's why this error shows up

My config: https://0x0.st/-FSV.yaml

**Comment by Zeioth** [comment]
Same thing happen to me with the option 'total-size'.

**Comment by zwpaper** [comment]
hi @Zeioth @mizzunet thanks for reporting this, and thanks to @Zeioth's report, I noticed that both of you have `total-size` enabled, `total-size` need to recursively walk into the dirs calculating the dir size, so that the error occurred, this seems worked as expected.

I am closing this issue, feel free to open it if there is still any questions.
