### ISSUE TITLE
alias ls in linux its posible to set lsd -l command to normal ls not to lsd

### ISSUE THREAD

**Issue by mikebgrep** [Peltoche/lsd#598]
I just installed lsd but I want when I type ls -l with with alias ls='lsd' its show lsd version I want the classic linux version.It can be done someway.

**Comment by meain** [comment]
You can always do `\ls -l` (with a backslash) and that will resort back to the original ls. But if you want to do it more transparently, you will have to probably create a function. Something like:

```sh
function ls() { [ -z "$1" ] && lsd || command ls $* }
```

**Comment by mikebgrep** [comment]
Where I need to place the function in .bashrc I try and it faills

**Comment by meain** [comment]
Yeah, bashrc should do. Make sure to remove the alias line. Also, what do you mean by fail. Are you getting any error, could you drop the logs here.

**Comment by mikebgrep** [comment]
`.bashrc: line 120: syntax error: unexpected end of file`
This is the error I remove alias for ls.
This is when I open terminal I am in Ubuntu

**Comment by meain** [comment]
```sh
unalias ls
function ls() {
        if [ -z "$1" ]; then
                lsd
        else
                command ls $*
        fi
}
```

My bad, the previous one did not work in `bash`. I use `zsh` and forgot to check if the script actually worked in `bash`. This should work though.

**Comment by mikebgrep** [comment]
Working perfect thank you.
