### ISSUE TITLE
Improvement: total-size

### ISSUE THREAD

**Issue by Zeioth** [Peltoche/lsd#603]
Better defaults:

* **Silence permission errors** → We should just hide directory sizes where it's not possible to display it.

New options:

* **directory-size-cache [true/false]** → This should be precise enough in most cases of use. And more realistic than having to wait several seconds for ls.

**Comment by zwpaper** [comment]
hi @Zeioth, thanks for raising this discussion, better behavior for `total-size` without permission is a good idea, but silencing the errors may lead to a mistaken understanding of the real dir size.

for the second option, `lsd` is a tool without states, caching something seems not that suit `lsd`

**Comment by meain** [comment]
Neither of them sounds like a good fit for lsd and so I'm closing the issue.
