### ISSUE TITLE
Theme: TokyoNight

### ISSUE THREAD

**Issue by Zeioth** [Peltoche/lsd#604]
Some changes over the base theme that go well with TokyoNight.

![screenshot_2021-12-26_10-46-51_123516709](https://user-images.githubusercontent.com/3357792/147418675-b2d94f3c-fc29-4211-873f-fafb0c284194.png)

Theme
```bash
user: 130
group: 130
permission:
  read: dark_green
  write: dark_yellow
  exec: dark_red
  exec-sticky: 5
  no-access: 245
date:
  hour-old: 40
  day-old: 4
  older: 8
size:
  none: 2
  small: 2
  medium: 22
  large: 1
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
```

**Comment by zwpaper** [comment]
related https://github.com/Peltoche/lsd/issues/602
