### ISSUE TITLE
Print name of tree root

### ISSUE THREAD

**Issue by alex-pat** [Peltoche/lsd#61]
Current behavior is a little bit confusing when printing tree of several dirs:
```
$ target/release/lsd --tree ~/dir*
├── subdir11
│  ├── file111
│  └── file112
└── subdir12
│  ├── file121
│  └── file122
├── subdir21
│  ├── file211
│  └── file212
└── subdir22
│  ├── file221
│  └── file222
```
For comparison:
```
$ exa -T ~/dir*
/home/user/dir1
├── subdir11
│  ├── file111
│  └── file112
└── subdir12
   ├── file121
   └── file122
/home/user/dir2
├── subdir21
│  ├── file211
│  └── file212
└── subdir22
   ├── file221
   └── file222
```
And can say that printing `│` at the beginning of line after last dir entry makes it even more confusing.

**Comment by Peltoche** [comment]
Hi @alex-pat,

Thanks for the issue. The `--tree` option need a lot of improvements indeed. It also need a big refactoring but it a big piece of work. I will work on it soon.
