### ISSUE TITLE
how do i change icons?

### ISSUE THREAD

**Issue by makerio90** [Peltoche/lsd#612]
i don't like the default icons and want to use my own, like  and  . how do i do this? i cant find it in the readme.

**Comment by meain** [comment]
You can't change icons as of now. Related: https://github.com/Peltoche/lsd/issues/343.

**Comment by jubgjf** [comment]
I'm using lsd version 0.23.1 and it should already have the feature to change icons. But in the `config.yaml` the `icons` option only accepts two values: `fancy` or `unicode`. How do I make it read the `icons.yaml`?

**Comment by meain** [comment]
This feature has not yet been released. You can however get this if you build from `master`. If you have built a binary from master, you can just create a file called `icons.yaml` in `$XDG_CONFIG_DIR/lsd/icons.yaml` and lsd should pick it up automatically.
