### ISSUE TITLE
Short options for --tree and --depth?

### ISSUE THREAD

**Issue by tasonosenshi** [Peltoche/lsd#616]
- os: Ubuntu on WSL2
- `lsd --version`: lsd 0.21.0
- `echo $TERM`: screen-256color
- `echo $LS_COLORS`: 

## Expected behavior
Have short options for --tree and --depth.
ex. `lsd -TD2 ../foo` would be equivalent to `lsd --tree --depth 2 ../foo`

**Comment by meain** [comment]
Both `-T` and `-D` is something that gnu ls uses already. Even though we might most probably not implement those features, I think it would be better to reserve them just in case we want to implement those later. Even if we were to pick something else, I am also not sure what a good candidate would be for these.

**Comment by tasonosenshi** [comment]
Hmmm, fair. I just started using lsd, trying it out as a more easily configurable alternative to exa. I hadn't yet realized lsd was trying to maintain that level of parity with the gnu ls cli.

In that case, you are right, there aren't any real good options for short flags for tree and depth.

**Comment by meain** [comment]
We try not to break things if possible, but hopefully with better defaults. Short options for `--tree` and `--depth` does not warrant breaking comparability to me ATM. Glad you found `lsd` useful. Closing this issue for now.
