### ISSUE TITLE
Is there a discord or somewhere that devs & users can talk?

### ISSUE THREAD

**Issue by MrPilotMan** [Peltoche/lsd#618]
Where do discussions take place without inappropriately opening GitHub issues?

**Comment by meain** [comment]
As of now, there is nothing like that. IMO, I don't think we have enough traffic to need a chat channel for communication. We can maybe enable [Github Discussions](https://docs.github.com/en/discussions) for questions that are not really "issues".

**Comment by meain** [comment]
I'm closing this. As of now we are not looking into opening anything of that sort. Feel free to open issues if you have any trouble/questoins with `lsd`. We can look into opening up discussions if there is an influx of non issue type items.
