### ISSUE TITLE
Add support for hyperlinks

### ISSUE THREAD

**Issue by mrzv** [Peltoche/lsd#619]
[Terminal hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) are quite useful. They are supported by regular `ls`, e.g., `ls --hyperlink=auto`. It would be great if `lsd` had this support too.

**Comment by zwpaper** [comment]
hi @mrzv, thanks for mentioning this, it seems that `hyperlinks` is a missing feature for `lsd`, we could try to support this.

but I personally was not using this feature, could you explain it to us?

I found a [Feature Request](https://lists.gnu.org/archive/html/coreutils/2017-05/msg00001.html) and the [manpage](https://man7.org/linux/man-pages/man1/ls.1.html) for the GNU ls, but did not really get the difference between `always` and `auto`.

**Comment by mrzv** [comment]
I don't know what the difference between `always` and `auto` is. I stumbled onto hyperlinks because [kitty](https://sw.kovidgoyal.net/kitty/) has [excellent support](https://sw.kovidgoyal.net/kitty/open_actions/) for them, including for [remote files](https://sw.kovidgoyal.net/kitty/kittens/remote_file/).

**Comment by kovidgoyal** [comment]
The difference between always and auto is auto turns on hyperlinks when STDOUT has isatty() true always always turns on hyperlinks.

**Comment by meain** [comment]
We actually had someone give it a shot at https://github.com/Peltoche/lsd/pull/354, but it was unfortunately not competed at that point. We could start from where we left off there. Also, there is a duplicate issue. I am closing this in favor of that. 

ref: https://github.com/Peltoche/lsd/issues/192
