### ISSUE TITLE
🪟 lsd does not show blocks from config

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Peltoche/lsd#621]
- os: Windows 10
- `lsd --version`: 0.21.0
- `echo $TERM`: Windows Terminal PowerShell v5.1.19041.1023

## Expected behavior
blocks in config.yaml are not used
```yaml
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
```

## Actual behavior
lsd shows no blocks at all

**Comment by meain** [comment]
The blocks only show up when you have `-l` flag or enabled long display mode in config.

**Comment by sschneider-ihre-pvs** [comment]
ok cool thanks for the info.

**Comment by navakelvin** [comment]
How can I enable long display?

I've done this:
```yaml
display: length
```
And I get in the terminal:
```
lsd: Configuration file /home/kelvin/.config/lsd/config.yaml format error, display: unknown variant `long`, expected one of `all`, `almost-all`, `directory-only`, `visible- only` at line 11 column 10.
```

> The blocks only show up when you have `-l` flag or enabled long display mode in config.

**Comment by meain** [comment]
My bad, we don't have a option to default to "long", but if you want lsd to always display full info, I would suggest adding an alias with `-l` included.

```
alias ls=`lsd -l`
```

**Comment by navakelvin** [comment]
> My bad, we don't have a option to default to "long", but if you want lsd to always display full info, I would suggest adding an alias with `-l` included.
> 
> ```
> alias ls=`lsd -l`
> ```

Okay, ty sir!
