### ISSUE TITLE
Block Headers

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Peltoche/lsd#622]
Is there a way to have block headers?
![image](https://user-images.githubusercontent.com/86342787/153562615-d3c78c7e-9ba5-4d60-8301-5e3b4f2c73eb.png)

**Comment by meain** [comment]
Not at the moment, but this would be a good feature to add in.

**Comment by MichaelAug** [comment]
Hi, I'll try to implement this :)
How should the headers look like? Like the screenshot above or something different?
Is flag "-h, --header" ok for this?

**Comment by meain** [comment]
Thanks @MichaelAug for looking into this. Something like the screenshot would be a good start. One possible improvement that I can think of is that the underline could span the entire block width. Also, maybe we could center the header.

`--header` as the flag for this sounds good. I don't think we need a short flag for this.
