### ISSUE TITLE
can't locate config file on macos

### ISSUE THREAD

**Issue by trashyms** [Peltoche/lsd#625]
- os: macos 12.1 
- `lsd --version`: lsd 0.21.0
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: empty string

## Expected behavior
find config file at    ~/.config/lsd/config.yaml

## Actual behavior
~/.config/lsd 
folder does not exist when trying to print its content

![SCR-20220219-f12](https://user-images.githubusercontent.com/783204/154795932-60ccb9d7-654e-41fd-8b8d-8c3c15958b30.png)

**Comment by meain** [comment]
The folder will not exist by default. You will have to create the folder and add the file in manually. Once the file is available, `lsd` will pick it up and use it.

**Comment by trashyms** [comment]
Thanks for the rapid answer.
