### ISSUE TITLE
Feature request: use  for .torrent files

### ISSUE THREAD

**Issue by Kara-Zor-El** [Peltoche/lsd#628]
I feel as though adding that icon would really make it better since having a default icon there is not favourable and the  icon kinda seems like it would be used for security and privacy ~~as well as nefarious activities at times~~ and I think it would overall be a good fit for the the file

**Comment by zwpaper** [comment]
Hi @Kara-Zor-El, welcome to submit a PR adding the icon, it is easy and interesting, https://github.com/Peltoche/lsd/pull/624/files this may help if you want to.

as for the icon part, I can not see the icon you posted in this issue, maybe you can post the Hex code for it.

**Comment by meain** [comment]
You can use https://www.nerdfonts.com/cheat-sheet as your reference for icons available.

**Comment by Kara-Zor-El** [comment]
Thank you both so much. I will do that. thank you both
