### ISSUE TITLE
Option to show permissions in Octal

### ISSUE THREAD

**Issue by pbowyer** [Peltoche/lsd#630]
For all the reasons given on https://github.com/ogham/exa/issues/996 and https://news.ycombinator.com/item?id=29617182 it would be really nice if `lsd` had an option to display the `permission` column in octal rather than the traditional text format.

**Comment by meain** [comment]
That sounds like a pretty useful addition. The flag could be something like `--premission <type>` as we have things like `--date <type>`.

**Comment by meain** [comment]
I was looking into the exa implementation. As of now, they are adding it as a separate block. My initial thought was to replace how we display the permissions right now and change them to octal. I have feeling that doing it this way might not look right though as there is both prefix(filetype) and suffix(things like exec sticy) tacked onto permissions.

**Comment by meain** [comment]
I as thinking of implementing it as an alternate for the current rwx format in that it will essentially take the place of current permissions section. One issue with this might be that it might look kinda odd when we have the file type marker to the left of it. 

Not that bad, but mentioning it here in case someone has any opinions on it.
![2022-02-27-23-59-05](https://user-images.githubusercontent.com/14259816/155894949-c1bb87b6-95da-4657-9586-3c14cc5ad454.png)


*FYI, `exa` implements it as another block*

**Comment by pbowyer** [comment]
Thanks for looking at this! I like the flag your propose, and I'd thought of it taking the place of the current permissions section, and not an extra block.

However the file type marker... I hadn't considered that (I always look at the icon when using `lsd` rather than the marker) and I do find it hard to read, particularly the ones with `l` in front (brain says: "Is that a 1?"). 

Would adding a space between them be enough? We are adding something non-standard with octal formatting and scripts aren't going to parse this output, so it could be okay. It does change the number of columns for `awk` though, which could be annoying - except I never awk this listing as the date/time breaks into so many bits...

**Comment by meain** [comment]
> However the file type marker... I hadn't considered that (I always look at the icon when using `lsd` rather than the marker) and I do find it hard to read, particularly the ones with `l` in front (brain says: "Is that a 1?").

There will be a lot of people who don't use icons or colors and this is useful for them. Actually it is not that bad when I use my personal theme whcih is a lot more subtle.

![2022-02-28-10-15-23](https://user-images.githubusercontent.com/14259816/155925600-7fb2ded7-4dd8-4843-a481-5fe8291270c8.png)

> Would adding a space between them be enough? We are adding something non-standard with octal formatting and scripts aren't going to parse this output, so it could be okay. It does change the number of columns for `awk` though, which could be annoying - except I never awk this listing as the date/time breaks into so many bits... sorry, not helpful. Maybe another column?

I am not really concerned about awk or any scripting stuff there, but at the same time "permissions" `block` gets split into two if we put a space there which might be weird (maybe?). One possible option is to both provide an option to convert the default permissions to octal and an option to add it as a separate block (they can just use that and disable the normal permissions block if they want something cleaner).

> On the display, it would be wonderful if a non-zero setuid/setgid bit could be coloured.

I am not fully sold on this yet, but not a bad idea. I'm thinking maybe some kind of orange? Also taking recommendations for what the name of that color in the theme file should be.

**Comment by zwpaper** [comment]
@meain may I ask why some items show `3777` or `2775` instead of starting with `0`?

btw I would also vote for keeping it like `d0775` as the `0` is acting as the separator, it is weird if there is a space inside the permissions block.

**Comment by meain** [comment]
The first number (`3` in `3777` or `0` in `0775`) is to denote the `setuid`, `setgid` or `sticky` bit.

ref: https://github.com/meain/lsd/blob/f26dc1ea9201c13bd890b1c245e65b7decab3c16/src/meta/permissions.rs#L102

**Comment by pbowyer** [comment]
Thank you!
