### ISSUE TITLE
Not working with ZSH but works with Bash

### ISSUE THREAD

**Issue by fummymint** [Peltoche/lsd#632]
OS: Arch Linux 5.16.11-zen1
KDE
Terminal: Konsole
System Font/Terminal Font: Hack Nerd

**Comment by fummymint** [comment]
temporary solution. Use colorls.

**Comment by meain** [comment]
What exactly is not working? Is there any error messages? What version of `lsd` are you on?

**Comment by fummymint** [comment]
> 
No Icons. Arguments not working. 0.21.0-1

**Comment by meain** [comment]
It is highly unlikely that `lsd` is not taking args. Are you sure you are running `lsd`? What is the output of `lsd --version` and `lsd --icon always`?

**Comment by fummymint** [comment]
> It is highly unlikely that `lsd` is not taking args. Are you sure you are running `lsd`? What is the output of `lsd --version` and `lsd --icon always`?

```
$ lsd --version
ls (GNU coreutils) 9.0
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
```
```
$ lsd --icon
ls: unrecognized option '--icon'
Try 'ls --help' for more information.
```
Yeah looks like it's bugged. It's showing as regular LS. I don't have any alias for LS.

**Comment by zwpaper** [comment]
@fummymint try `which lsd` to check where the lsd command came from

**Comment by meain** [comment]
Looks like you might have aliased `lsd` to classic `ls`.

**Comment by fummymint** [comment]
> @fummymint try `which lsd` to check where the lsd command came from

Thank you! this solved it! for some reason, my lsd is aliased to ls -d

**Comment by fummymint** [comment]
> Looks like you might have aliased `lsd` to classic `ls`.

thank you. that fixed it!

**Comment by zwpaper** [comment]
I am closing this issue, free feel to open a new one if any question.
