### ISSUE TITLE
lsd of file timezone is wrong

### ISSUE THREAD

**Issue by hntee** [Peltoche/lsd#633]
- os: CentOS 7
- `lsd --version`: 0.21.0 
- `echo $TERM`: screen-256color
- `echo $LS_COLORS`: default

## Expected behavior
`ls -l` can get the correct time of the listed files.
My location is in GMT+8, and `lsd` only shows the GMT time.

**Comment by zwpaper** [comment]
what is the output of `ls -l /etc/localtime`

**Comment by hntee** [comment]
> what is the output of `ls -l /etc/localtime`

Hi, the output is `/etc/localtime ⇒ ../usr/share/zoneinfo/Asia/Shanghai`

**Comment by zwpaper** [comment]
could you try to update the soft link to the absolute path by 

```sh
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
```

just to make sure it is not related to the related path

**Comment by hntee** [comment]
> ```shell
> /usr/share/zoneinfo/Asia/Shanghai
> ```

have done this step, but the output of lsd is the same

**Comment by hntee** [comment]
`$ timedatectl`
``` 
     Local time:
 Mon 2022-03-14 12:19:13 CST
  Universal time: Mon 2022-03-14 04:19:13 UTC
        RTC time: Mon 2022-03-14 04:19:13
       Time zone: Asia/Shanghai (CST, +0800)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a
```
Another interesting thing is that the time shown in terminal prompt is also wrong (which is UTC but not local time).
I don't know which setting causes this issue.

**Comment by hntee** [comment]
Problem solved. 
```
export TZ=Asia/Shanghai
```
would work.
