### ISSUE TITLE
Example config file in README with default values throws an error message in lsd

### ISSUE THREAD

**Issue by thingsiplay** [Peltoche/lsd#643]
- os: Manjaro
- `lsd --version`: 0.21.0-2
- `echo $TERM`: xterm-kitty
- `echo $LS_COLORS`: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:`

I am new to **lsd** and just installed it a few hours back from official repo in Manjaro.

```
OS: Manjaro Linux [x86_64]
Kernel: 5.16.14-1-MANJARO
Uptime: 3 days, 13 hours, 7 mins
Packages: 1896 (pacman)[stable], 1 (flatpak)
Shell: zsh 5.8.1
Resolution: 2560x1440 @ 144Hz
DE: KDE Plasma 5.24.3
WM: Qtile 0.20.1.dev69+g52ac53bf
Theme: breeze (GruvboxColors) [Plasma], Klaus [GTK2/3/4]
Icons: breeze [Plasma], Gruvbox [GTK2/3/4]
Font: Noto Sans (12pt) [Plasma], Noto Sans (12pt) [GTK2/3/4]
Cursor: default (24px)
Terminal: kitty
CPU: Intel Xeon E3-1230 v3 (8) @ 3.7GHz
GPU: Nvidia GeForce GTX 1070
Memory: 3356MiB / 15947MiB (21%)
Disk (/): 94GB / 219GB (42%)
Locale: de_DE.UTF-8
```

```
$ pamac info lsd
Name                      : lsd
Version                   : 0.21.0-2
Beschreibung              : Modern ls with a lot of pretty colors and awesome icons
URL                       : https://github.com/Peltoche/lsd
Lizenzen                  : Apache
Paketquelle               : community
Installierte Größe        : 2,8 MB
Gruppen                   : --
Hängt ab von              : gcc-libs ttf-nerd-fonts-symbols
Optionale Abhängigkeiten  : --
Benötigt von              : --
Optional für              : --
Stellt bereit             : --
Ersetzt                   : --
Konflikt mit              : --
Packer                    : Mark Wagie <mark@manjaro.org>
Erstelldatum              : So 16 Jan 2022 17:25:39 CET
Installiert am            : Sa 26 Mär 2022 23:10:10 CET
Installationsgrund        : Ausdrücklich installiert
Validated By              : Signature
Dateisicherungen          : --

```

## Expected behavior
Using the suggested default config file at [README: Config file content](https://github.com/Peltoche/lsd#config-file-content=) I expected the program to work like it would have no config file. Because these are default values.

## Actual behavior
I get error message output when using default configuration file copied from [README: Config file content](https://github.com/Peltoche/lsd#config-file-content=):
```
$ lsd
lsd: Configuration file /home/tuncay/.config/lsd/config.yaml format error, unknown field `permission`, expected one of `classic`, `blocks`, `color`, `date`, `dereference`, `display`, `icons`, `ignore-globs`, `indicators`, `layout`, `recursion`, `size`, `sorting`, `no-symlink`, `total-size`, `symlink-arrow` at line 99 column 1.
```
followed by normal listing of files.
`RUST_BACKTRACE=1 lsd` has same output.

Removing the config file will result in no error message and normal listing of files.

**Comment by meain** [comment]
`permission` is a new feature and is not yet available in a release. If  you want to have the permission feature, you will have to install from master as of now.

**Comment by thingsiplay** [comment]
Okay, just commenting it out works for now. I don't plan on installing from source yet. Maybe it is a good idea to add a comment to indicate minimum version of lsd. Because many people will install it from official repos and if the official suggested default config causes an error, then this could throw off some people.

**Comment by meain** [comment]
I have been thinking about adding just a warning like `warn: unknown key 'permission'` but reading the rest of the config in case of invalid items, just never got around to it; but adding a comment in the readme saying something is unreleased could be a good idea.
