### ISSUE TITLE
Cant patch down to lsd version 0.20.1

### ISSUE THREAD

**Issue by AlbertMakdissi** [Peltoche/lsd#645]
Downloaded the version for windows from here: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd-0.20.1-i686-pc-windows-gnu.zip. Unzipped it on desktop and ran the binary in the powershell like this:
![grafik](https://user-images.githubusercontent.com/96504290/160656467-ff40c9aa-f21a-4f14-a234-fa13a75c1e28.png)
Looked like it worked but when checking the version, its not downgraded:
![grafik](https://user-images.githubusercontent.com/96504290/160656557-5e9f8e3f-6a2e-4d5f-8457-7abd16f2ec35.png)

Thanks in advance.

**Comment by meain** [comment]
I don't know how windows works, but in the first pick you are running the downloaded file(which is not installed) and in the second one you are running the global installation. Both are different. You might wanna look up how to "install" a binary on Windows.

**Comment by AlbertMakdissi** [comment]
Okay did that. So for everyone using windows, who might also need to do that. These are the steps: 

1. Download the lsd version u need from https://github.com/Peltoche/lsd/releases 
2.  unzip the file to ur primary drive-->In my case its C: 
3. Copy the path to the unzipped folder 
4.  Open your Systemvariables Configuration Settings -> advanced ->path variables -> click path and than new button and paste the path of the folder u copied there. Press Ok. Make sure that the systemvariable PATHEXT has the suffix .exe in it
![grafik](https://user-images.githubusercontent.com/96504290/160809198-3c0d5c12-0bba-4acc-bc30-5de077f24afb.png)
5. Now in my case I had to delete the previous version via `scoop uininstall lsd` and than the lsd version that I wanted is active.

**Comment by meain** [comment]
Just out of curiosity, why did you want to downgrade the version?

**Comment by AlbertMakdissi** [comment]
Git bash cant handle the 256 color scheme thats introduced in lsd version 0.21.
