### ISSUE TITLE
Provide a Flag to Hide Icons

### ISSUE THREAD

**Issue by mitnk** [Peltoche/lsd#65]
Icons can be a problem when interactive with pipes, to be more compatible with `ls`. For example:
```
$ lsd | grep 'foo.txt' | xargs rm  # not work
$ ls | grep 'foo.txt' | xargs rm  # works
```

PS. Is it a bug for `lsd` to print an extra line?
i.e. `lsd | wc -l` (always) == `ls | wc -l` + 1

**Comment by Peltoche** [comment]
Hi @mitnk ,

Thanks for the report. It's known that in its current state lsd doesn't work as expected with the pipes. A flag need to be added in order to make the icons optional when using pipes.

This will be fixed soon

**Comment by Peltoche** [comment]
The feature request #70 could probably help you too.

**Comment by mitnk** [comment]
Thanks, look forward to it!
