### ISSUE TITLE
Color output is broken in some combinations on Windows + MSYS2

### ISSUE THREAD

**Issue by martinlindhe** [Peltoche/lsd#657]
- os: windows
- `lsd --version`:  0.21.0
- `echo $TERM`:  xterm-256color
- `echo $LS_COLORS`:  <unset>

## Expected behavior
Seeing colors.

## Actual behavior

With windows terminal, launcing bash using msys2:
![image](https://user-images.githubusercontent.com/181531/168126084-e8b48f8e-739b-4a43-8308-3ed98b48348b.png)

wezterm, launching zsh using msys2:
![image](https://user-images.githubusercontent.com/181531/168126566-703f110f-6100-481e-ab19-47a37fb4dfb3.png)

See colored prompt and colored cargo output is working. Only "lsd" command output has codes showing `←[38;5;4m←[1m  bin←[0m  ←[38;5;4m←[1m  pkg←[0m`.

The same "lsd.exe" correctly shows colors in powershell and cmd.exe, and also when run thru stand-alone msys2.

**Comment by martinlindhe** [comment]
Update:

I have done some investigation and the issue seems to have been resolved in 2019 but the code has since been refactored so the fix was lost.

PR https://github.com/Peltoche/lsd/pull/195 resolved this in 2019 but the code path is no longer in master.

What disappeared is the call to `ansi_term::enable_ansi_support()`, or similar.

**Comment by martinlindhe** [comment]
Update 2:

You might not want to accept my open PR to fix this issue, as I am attempting to fix the root cause in crossterm over at https://github.com/crossterm-rs/crossterm/issues/666


A work-around for the moment to get lsd colors working on MSYS2 is something like this:

```bash
alias ls="TERM=dumb lsd"
``` 

because TERM=dumb short-circuits crossterm's broken terminal check.

**Comment by martinlindhe** [comment]
Update 3: crossterm merged a fix for this in https://github.com/crossterm-rs/crossterm/commit/35d58ccc305caff043340668949eadd936659210

When a new release of crossterm is out, we can update the dependency for lsd and this issue should be resolved.

**Comment by martinlindhe** [comment]
This issue has been resolved in crossterm 0.24

> Fix escape codes on Git-Bash + Windows Terminal / Alacritty / WezTerm.

https://github.com/crossterm-rs/crossterm/releases/tag/0.24

**Comment by meain** [comment]
I am guessing https://github.com/Peltoche/lsd/issues/675 is related.

**Comment by martinlindhe** [comment]
@meain Yes, that is the same issue for sure.

**Comment by meain** [comment]
@martinlindhe Would you be able to check if https://github.com/Peltoche/lsd/pull/688 fixes the issue? I have bumped the `crossterm` version.

**Comment by martinlindhe** [comment]
@meain Confirmed working with x86-64-msvc artifact from your #688.
![Capture](https://user-images.githubusercontent.com/181531/177264392-826765bd-9a41-4f5d-a09c-0567d590233e.JPG)

The second command is lsd 0.22.0
