### ISSUE TITLE
Issues with config file entries "permission" and "hyperlink" and theme file

### ISSUE THREAD

**Issue by jjarava** [Peltoche/lsd#662]
- os: 
> ProductName:	macOS
> ProductVersion:	12.1
> BuildVersion:	21C52
- `lsd --version`: `lsd 0.21.0`
- `echo $TERM`: `xterm-256color`
- `echo $LS_COLORS`: (empty)

## Expected behavior
Running lsd displays the listing of files 

## Actual behavior
I got an error message like:

```
lsd: Configuration file /Users/jjarava/.config/lsd/config.yaml format error, unknown field `permission`, expected one of `classic`, `blocks`, `color`, `date`, `dereference`, `display`, `icons`, `ignore-globs`, `indicators`, `layout`, `recursion`, `size`, `sorting`, `no-symlink`, `total-size`, `symlink-arrow` at line 99 column 1.
```

I commented out the `permission` file in config.yaml, and then I got another error:

> lsd: Configuration file /Users/jjarava/.config/lsd/config.yaml format error, unknown field `hyperlink`, expected one of `classic`, `blocks`, `color`, `date`, `dereference`, `display`, `icons`, `ignore-globs`, `indicators`, `layout`, `recursion`, `size`, `sorting`, `no-symlink`, `total-size`, `symlink-arrow` at line 127 column 1.

Once I got the config file to parse, I _also_ got errors on the format of the theme file; I had to end up commenting out `octal`, `acl` and `context` to get the config I had set to work

**Comment by dadav** [comment]
Same. I'm also using **v0.21.0**

**Comment by zwpaper** [comment]
maybe duplicated with https://github.com/Peltoche/lsd/issues/643

**Comment by meain** [comment]
Update to the latest version and you should be good to go.
