### ISSUE TITLE
lsd cannot display some directories

### ISSUE THREAD

**Issue by misiektoja** [Peltoche/lsd#664]
- os: CentOS 7.8.2003
- `lsd --version`: lsd 0.16.0
- `echo $TERM`: xterm
- `echo $LS_COLORS`: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.pkg=01;31:*.dmg=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.ico=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:*.pem=35:*.der=35:*.p12=35:*.crt=35:*.p7b=35:*.cer=35:*.pub=35:*.prv=35:*.pfx=35:*.crl=35:*.key=35:*.csr=35:*.log=38;5;039:*.txt=38;5;220:*.csv=38;5;220:*.md=38;5;220:*.pdf=38;5;220:*.docx=38;5;220:*.xlsx=38;5;220:*.vsd=38;5;220:*.asc=38;5;220:*.pptx=38;5;220:*.conf=38;5;222:*.cfg=38;5;222:*.py=38;5;132:*.go=38;5;132:*.c=38;5;132:*.cpp=38;5;132:*.sql=38;5;132:*.scm=38;5;132:*.pl=38;5;132:*.asm=38;5;132:*.yaml=38;5;132:*.yml=38;5;132:*.sh=38;5;132:*.json=38;5;132:*.xml=38;5;132:*.bash=38;5;132:*.zsh=38;5;132:*.html=38;5;132:*.htm=38;5;132:*.js=38;5;132:*.java=38;5;132:

## Expected behavior

Commands run as root.

» ls -al /itemhistory
total 4
drwx------   3 postgres postgres   30 Nov 21  2019 .
dr-xr-xr-x. 20 root     root     4096 Mar 20 23:53 ..
drwx------   3 postgres postgres   19 Nov 21  2019 PG_9.4_201409291

» ls -al /var/lib/pgsql/9.4-bdr
total 8
drwx------  4 postgres postgres   51 Mar 12  2018 .
drwx------  7 postgres postgres  226 May 26 19:52 ..
drwx------  2 postgres postgres    6 Mar 12  2018 backups
drwx------ 20 postgres postgres 4096 May 26 19:48 data
-rw-------  1 postgres postgres 1401 Oct 31  2017 initdb.log

## Actual behavior

Commands run as root. Dirs belong to postgres.postgres and lsd has some issues displaying it.

» lsd -al /itemhistory
cannot access '/itemhistory': No such file or directory (os error 2)

» lsd -al /var/lib/pgsql/9.4-bdr
cannot access '/var/lib/pgsql/9.4-bdr': No such file or directory (os error 2)

**Comment by misiektoja** [comment]
Also root-owned files are affected. I have no clue what is going on.

[20:48:23] root::nclm ➜ /var/cache/yum » lsd -al
d--x--x--x root root   6 B Fri Mar 11 10:20:59 2022   .
drwxr-xr-x root root 267 B Thu May 26 20:04:19 2022   ..                                                                    /0.0s

[20:48:28] root::nclm ➜ /var/cache/yum » ls -al
total 0
drwxr-xr-x.  3 root root  20 Apr  2  2020 .
drwxr-xr-x. 15 root root 185 Mar 20 23:53 ..
drwxr-xr-x.  3 root root  15 Oct  3  2017 x86_64                                                                             /0.0s
[20:48:43] root::nclm ➜ /var/cache/yum »

**Comment by zwpaper** [comment]
hi @misiektoja , we have released the v0.21.0, please check the newest version and see if there is still problems
