### ISSUE TITLE
--ignore-glob does not work on windows.

### ISSUE THREAD

**Issue by 3ri4nG0ld** [Peltoche/lsd#665]
- os: Windows 11 Pro 21H2 (22000.708)
- `lsd --version`:   0.21.0
- `echo $TERM`: 
- `echo $LS_COLORS`: 

## Expected behavior
Currently on linux if I run the command  `lsd --ignore-glob NTUSER.DAT\* --ignore-glob ntuser.dat\*` the result is as expected

![image](https://user-images.githubusercontent.com/24411137/171002051-0970a7f7-984d-44c5-848b-ca0e15dc64e4.png)

## Actual behavior
But if I use the same command from windows , it does not apply.

![image](https://user-images.githubusercontent.com/24411137/171001806-477484fa-6229-4b1f-b514-03543ea6b438.png)

**Comment by zwpaper** [comment]
closing this one in favor of #693 has more details
