### ISSUE TITLE
Disabling background color for directories with 777 permissions?

### ISSUE THREAD

**Issue by xfzv** [Peltoche/lsd#671]
After updating to 0.22.0, directories with 777 permissions are displayed with a background color:

![image](https://user-images.githubusercontent.com/78810647/173253546-f81e525c-dc8d-4a6b-923d-1cc50f64e74f.png)

How can I disable this? `--ignore-config` doesn't make any difference and I cannot seem to find the correct value in the [Theme file content](https://github.com/Peltoche/lsd#theme-file-content).

PS: I'm not using [LS_COLORS](https://github.com/trapd00r/LS_COLORS).

Thanks.

**Comment by meain** [comment]
> PS: I'm not using [LS_COLORS](https://github.com/trapd00r/LS_COLORS).

What you need to use is `LS_COLORS` to update the colors of files/folders.

ref:
- https://unix.stackexchange.com/questions/241726/fix-ls-colors-for-directories-with-777-permission
- https://unix.stackexchange.com/questions/94498/what-causes-this-green-background-in-ls-output
