### ISSUE TITLE
Incorrect display of file names in Windows 10

### ISSUE THREAD

**Issue by MeShootIn** [Peltoche/lsd#675]
- os: Microsoft Windows [Version 10.0.19044.1706]
- `lsd --version`: lsd 0.22.0
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;4
4:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=
01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=
01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:
*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjp
eg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01
;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;3
5:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.fl
v=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:
*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xsp
f=00;36:

## Additional info:
- My terminal emulator: [Alacritty](https://github.com/alacritty/alacritty) with `Hack NF` font.
- Alacritty config: https://gist.github.com/MeShootIn/288a06e700582cdc993708968a49814c

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.
Сolored correct file names with indents and line breaks should be displayed.

## Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.
In `Alacritty`:
![image](https://user-images.githubusercontent.com/47987074/174324100-72680db3-ddb3-4ec7-bfb0-df713ac670a0.png)
In `cmd` (colored, but without icons (because of uninstalled font for `cmd`)):
![image](https://user-images.githubusercontent.com/47987074/174324501-6dea3d05-4350-4eb8-a3f7-d929c0737c45.png)

**Comment by meain** [comment]
This looks odd, it looks like the ansi escape codes are not working properly. Could you double check the `TERM` value set in alacrity.

**Comment by MeShootIn** [comment]
> This looks odd, it looks like the ansi escape codes are not working properly. Could you double check the `TERM` value set in alacrity.

![image](https://user-images.githubusercontent.com/47987074/174355922-47908d98-ffdd-47e2-ad41-cb19d4da2cfc.png)

**Comment by meain** [comment]
![2022-06-18-15-49-08](https://user-images.githubusercontent.com/14259816/174433461-c71dc334-59e0-4382-b725-649316101500.png)

Could you try if `echo -e "\x1b[38;5;4mfolder-test\x1b[0m"` gives you the same output. If not, it is probably some issue with the terminal, terminfo or `$TERM`.

**Comment by meain** [comment]
The reason why `ls` is displaying colors but `lsd` is not is because `ls` uses 16 colors and `lsd` uses 256 by default.

**Comment by MeShootIn** [comment]
> ![2022-06-18-15-49-08](https://user-images.githubusercontent.com/14259816/174433461-c71dc334-59e0-4382-b725-649316101500.png)
> 
> Could you try if `echo -e "\x1b[38;5;4mfolder-test\x1b[0m"` gives you the same output. If not, it is probably some issue with the terminal, terminfo or `$TERM`.

![image](https://user-images.githubusercontent.com/47987074/174433733-1e16a3e1-8d19-414e-b067-4cf01a3bbc91.png)

**Comment by meain** [comment]
How about any of `'\x1B[38;5;4m\x1B[1mdev\x1B[0m'` or `'\033[38;5;4m\033[1mdev\033[0m'` or `'\033[38;5;4m\033[1mdev\033[0m'`.  If I am not mistaken the first one is gonna cause problems.

In any case, I found related issues in alacritty (https://github.com/alacritty/alacritty/issues/4794)

**Comment by MeShootIn** [comment]
These two lines below are the same:
> `'\033[38;5;4m\033[1mdev\033[0m'` or `'\033[38;5;4m\033[1mdev\033[0m'`
However, both examples print correctly:
![image](https://user-images.githubusercontent.com/47987074/174434920-47ac0eb2-a791-4c68-9558-fd92ad43870e.png)

**Comment by meain** [comment]
My bad, the last one was supposed to be `\e[38;5;4m\e[1mdev\e[0m`, but I guess that should work. `lsd` actually uses the first one mentioned there, but if that own its own is working  I am not entirely sure what is going on. Could you try `lsd --icon never` and see if that is still causing issues?

**Comment by MeShootIn** [comment]
> My bad, the last one was supposed to be `\e[38;5;4m\e[1mdev\e[0m`, but I guess that should work. `lsd` actually uses the first one mentioned there, but if that own its own is working I am not entirely sure what is going on. Could you try `lsd --icon never` and see if that is still causing issues?

![image](https://user-images.githubusercontent.com/47987074/174475542-a5c2b9db-c409-4652-ba4a-b92478ed72f5.png)

**Comment by meain** [comment]
I don't think this is an `lsd` issue as it works in other terminal emulators and the ansi escape codes is pretty much standard. I am starting to believe this is more related to the `alacritty` issue that I linked before. In any case, maybe give it a shot with `TERM=screen`, `TERM=""`(empty), `TERM=screen-256color`.
