### ISSUE TITLE
Glyphs are different sizes?

### ISSUE THREAD

**Issue by dacobi** [Peltoche/lsd#678]
I just installed lsd and nerd fonts hack and I get glyphs for most file types but they are different and wrong sizes:

![Screenshot from 2022-06-22 16-58-23](https://user-images.githubusercontent.com/7037472/175062613-55a0a115-95fc-4b51-8aa9-aeeb67602ef3.png)

I didn't know if I should post here or on the nerd fonts page but since colorls behaves differently and had the folder glyphs in the right size I'm writing here.

I haven't installed a custom font since XFree86 had a font server so don't really know what I'm doing.

Installed fonts-hack-ttf on Pop OS! 22.04 and have also installed nerd fonts hack from their git repo in .local/share/fonts/NerdFonts/

It seems that that was the only way to get all glyphs working.

I've tried lsd in gnome terminal and guake and it looks the same.

**Comment by meain** [comment]
c icon based on the c language logo. They are explicitly meant to have different icons.
- c: https://github.com/Peltoche/lsd/blob/2ffb59cc9eab759d1eea23c217f19ac93ff0971f/src/icon.rs#L245
- h: https://github.com/Peltoche/lsd/blob/2ffb59cc9eab759d1eea23c217f19ac93ff0971f/src/icon.rs#L313

**Comment by dacobi** [comment]
That wasn't my question. If you look at the screenshot you'll see that the
icon for cpp is a "chinese" symbol.

**Comment by meain** [comment]
The font you are using does not have nerd font glyphs patched in properly and is instead having some other glyph at the location where we are expecting to have a cpp logo glyph. Ideally if you have a properly patched font, this would not happen.

**Comment by dacobi** [comment]
I have it working now by selecting the font in the terminal app preferences.
Don't know why only some or any icons were present when it was set to
system font. Before I installed nerd fonts or font awesome there were no
icons, when set to system font.
