### ISSUE TITLE
`-I` option does not function properly when used with a *

### ISSUE THREAD

**Issue by OldWorldOrdr** [Peltoche/lsd#693]
- os: Windows 11
- `lsd --version`: lsd 0.22.0
- `echo $TERM`: idk its powershell
- `echo $LS_COLORS`: idk its powershell

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.
```
PS C:\Users\Joey> C:\Users\Joey\scoop\shims\ls -I NTUSER.DAT\* -I ntuser.dat\* -I ntuser.ini
3D Objects  Application Data  Desktop    Downloads  Links           Music         NetHood   PrintHood  Saved Games  SendTo      Templates  ansel  scoop
AppData     Cookies           Documents  Favorites  Local Settings  My Documents  Pictures  Recent     Searches     Start Menu  Videos     bin
```
## Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.
```
PS C:\Users\Joey> C:\Users\Joey\scoop\shims\lsd --classic -I NTUSER.DAT\* -I ntuser.dat\* -I ntuser.ini
3D Objects        ntuser.dat.LOG2                                                                               NTUSER.DAT{c4d50919-e5bf-11ec-b868-744ca1d2e972}.TMContainer00000000000000000001.regtrans-ms
ansel             NTUSER.DAT{1c2b59c6-c5f5-11eb-bacb-000d3a96488e}.TM.blf                                       NTUSER.DAT{c4d50919-e5bf-11ec-b868-744ca1d2e972}.TMContainer00000000000000000002.regtrans-ms
AppData           NTUSER.DAT{1c2b59c6-c5f5-11eb-bacb-000d3a96488e}.TMContainer00000000000000000001.regtrans-ms  NTUSER.DAT{cdf21bf9-e01f-11ec-b863-744ca1d2e972}.TM.blf
Application Data  NTUSER.DAT{1c2b59c6-c5f5-11eb-bacb-000d3a96488e}.TMContainer00000000000000000002.regtrans-ms  NTUSER.DAT{cdf21bf9-e01f-11ec-b863-744ca1d2e972}.TMContainer00000000000000000001.regtrans-ms
bin               NTUSER.DAT{32f35d22-c36f-11ec-b852-744ca1d2e972}.TM.blf                                       NTUSER.DAT{cdf21bf9-e01f-11ec-b863-744ca1d2e972}.TMContainer00000000000000000002.regtrans-ms
Cookies           NTUSER.DAT{32f35d22-c36f-11ec-b852-744ca1d2e972}.TMContainer00000000000000000001.regtrans-ms  Pictures
Desktop           NTUSER.DAT{32f35d22-c36f-11ec-b852-744ca1d2e972}.TMContainer00000000000000000002.regtrans-ms  PrintHood
Documents         NTUSER.DAT{4d67d512-ca76-11ec-b857-744ca1d2e972}.TM.blf                                       Recent
Downloads         NTUSER.DAT{4d67d512-ca76-11ec-b857-744ca1d2e972}.TMContainer00000000000000000001.regtrans-ms  Saved Games
Favorites         NTUSER.DAT{4d67d512-ca76-11ec-b857-744ca1d2e972}.TMContainer00000000000000000002.regtrans-ms  scoop
Links             NTUSER.DAT{626b5672-b70f-11ec-b845-744ca1d2e972}.TM.blf                                       Searches
Local Settings    NTUSER.DAT{626b5672-b70f-11ec-b845-744ca1d2e972}.TMContainer00000000000000000001.regtrans-ms  SendTo
Music             NTUSER.DAT{626b5672-b70f-11ec-b845-744ca1d2e972}.TMContainer00000000000000000002.regtrans-ms  Start Menu
My Documents      NTUSER.DAT{ab838e4d-b3a2-11ec-b841-744ca1d2e972}.TM.blf                                       Templates
NetHood           NTUSER.DAT{ab838e4d-b3a2-11ec-b841-744ca1d2e972}.TMContainer00000000000000000001.regtrans-ms  Videos
NTUSER.DAT        NTUSER.DAT{ab838e4d-b3a2-11ec-b841-744ca1d2e972}.TMContainer00000000000000000002.regtrans-ms
ntuser.dat.LOG1   NTUSER.DAT{c4d50919-e5bf-11ec-b868-744ca1d2e972}.TM.blf
```

**Comment by meain** [comment]
Hmm, somehow I am not able to reproduce this on my end. @zwpaper are you able to reproduce this?

**Comment by zwpaper** [comment]
sorry for the late reply, I did not have a windows machine, so I can only confirm that I also can NOT reproduce this on my mac.

maybe we need some more windows tests

**Comment by zwpaper** [comment]
BTW I also noticed that there is two path indicator on the command lines, is this an copy/paste mistake?

**Comment by OldWorldOrdr** [comment]
@zwpaper the second paths are the paths to the ls and lsd executables

**Comment by zwpaper** [comment]
Oops, sorry for the silly mistake.

let me try to create a debug version for us to find the problem/

**Comment by zwpaper** [comment]
happened to find a related issue, but also has no more clue, only to confirm this may be a bug https://github.com/Peltoche/lsd/issues/665

**Comment by OldWorldOrdr** [comment]
#665 is inaccurate as it does work if you don't use a *

**Comment by TeamTamoad** [comment]
@OldWorldOrdr After some research and experiment, here is some workaround. (I tested on Window 10 with `lsd` version 0.22.0)

### Powershell
wrap the pattern around `` `" `` for example
![image](https://user-images.githubusercontent.com/43115371/183262671-f9d1484a-ebc1-46d3-b16d-37bf032784d5.png)

### Command Prompt
wrap the pattern around `"` for example
![image](https://user-images.githubusercontent.com/43115371/183262758-17eb0a77-eb30-49fc-822c-dc7d72b6e94f.png)

I hope this help.

### Note
- https://stackoverflow.com/questions/42265416/cant-get-powershell-to-read-the-character

**Comment by OldWorldOrdr** [comment]
@TeamTamoad that worked! thanks!

**Comment by WantToLearnJapanese** [comment]
The trick works on legacy Powershell but not the new one (PS7).
