### ISSUE TITLE
small icons

### ISSUE THREAD

**Issue by Radius112** [Peltoche/lsd#697]
icons are small when i type lsd 
![image](https://user-images.githubusercontent.com/98346472/178120799-e92cc07b-b851-450b-9754-c0add19bcc13.png)
how can i make them bigger?

**Comment by meain** [comment]
The size of the icons is not something controlled by `lsd`. It is dependent on the font. Try changed your font to a different one from https://www.nerdfonts.com/font-downloads

**Comment by Zesko** [comment]
I confirmed the issue, that is related to the package `ttf-isovevka-nerd` from the Arch repos.

Just remove `ttf-isovevka-nerd`  and install `ttf-nerd-fonts-symbols-2048-em` to solve this issue.
