### ISSUE TITLE
Add a --classic flag

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#70]
This flag should override all the other flag and make the output similar to the classic ls command

It would be useful for the people like me which set the `--color=always` into the flags but sometime need the "classic" output in order to work with pipes.

### Example 
```sh
ls --color=always --classic | xargs rm # should work
```

**Comment by mitnk** [comment]
`--classic` may not needed explicitly to users.

When lsd is found being redirected into pipes, it should make itself remove colors, hide icons, etc. (just like classic `ls` do with `--color=auto`).

But an extra `--no-icons` would be nice to have.

To have an `--classic` may not be good - since how do you make lsd show icons but not colors, or show colors but not icons?

**Comment by mitnk** [comment]
Just for curiosity, in what situation you need `always`, while `auto` doesn't do the job?

**Comment by Peltoche** [comment]
The `--no-icons` is already planned with the same logic than `--color` (#69) and it can solve many most of the your usecases.

Based on my experience I think the `--classic` could useful because most of the time when I pipe ls I use `less` behind for the pagination (`ls --tree | less` for example). With the default `--color` (and soon the default `--icon`) flag value to `auto` I loose the colors (and soon icons) so in order to solve this my alias looks like  `alias ls='lsd --color=always --icon=always` and my less output is pretty again.

This solution works fine with most of my daily needs but sometimes I want to use the ls output for other stuff than `less`. In those few cases I am currently blocked due to my alias. It's in this case that the `--classic` can help. By explicitly use this flag (`ls --classic | xargs rm`) I override all my configurations set into my alias and remove all the icons and the colors and xargs is happy again.
