### ISSUE TITLE
Request: lsd snap for arm64, updated amd64 snap

### ISSUE THREAD

**Issue by thediveo** [Peltoche/lsd#701]
Please update the amd64 snap which is from 2019.

And please additionally provide an arm64 version for Raspberry Pi Ubuntu.

Thank you very much!

**Comment by meain** [comment]
We do not manage snap versions anymore [ref](https://github.com/Peltoche/lsd/issues/79). You should however be able to download version from our GitHub [releases page](https://github.com/Peltoche/lsd/releases/latest).
