### ISSUE TITLE
1 Minute load time on Windows 10 - Powershell

### ISSUE THREAD

**Issue by WalterWoshid** [Peltoche/lsd#704]
- os: Windows 10
- Terminal: Powershell
- Installed with: choco
- `lsd --version`: 0.22.0
- `echo $TERM`: 
- `echo $LS_COLORS`: 

## Expected behavior
Not taking so long

## Actual behavior
Takes 1 minute and 8 seconds to display the output

![image](https://user-images.githubusercontent.com/36635504/179218894-2dac1e2a-e860-4d05-ae3a-7e38fc2bb2c4.png)

**Comment by meain** [comment]
Related: https://github.com/Peltoche/lsd/issues/200

**Comment by zwpaper** [comment]
please check update on https://github.com/Peltoche/lsd/issues/200
