### ISSUE TITLE
Adding new file types

### ISSUE THREAD

**Issue by bearcatsandor** [Peltoche/lsd#706]
Is there a process for users to add file types that aren't recognised.  For instance, I work with  wavpack and dsd files and it would be great to have them recognised as audio file types.

**Comment by meain** [comment]
If those are common enough extensions, feel free to just add those into `lsd`. You can do that by adding them in https://github.com/Peltoche/lsd/blob/946f2430661e57e0eda641a3f70601d4b46a3b71/src/icon.rs#L225

**Comment by meain** [comment]
We also have #707 in the pipeline for enabling custom icons.

**Comment by dreamerlzl** [comment]
Sorry for asking in a closed channel, but is "justfile" legit to be a common extension?

**Comment by meain** [comment]
Sure, feel free to add an icon if that is what you are going for.
