### ISSUE TITLE
Stop lsd on windows from showing every regular file as green

### ISSUE THREAD

**Issue by OldWorldOrdr** [Peltoche/lsd#712]
- os: Windows 11
- `lsd --version`: lsd 0.22.0
- `echo $TERM`: N/A
- `echo $LS_COLORS`: N/A

Windows NTFS doesnt have POSIX file permissions, so they need to be emulated.  This results in all files being marked as executable, which is necessary but annoying, since every regular file is shown in green.  Is there a way to make executable files white?

**Comment by daniejstriata** [comment]
Can one not create a new theme and select unique colours based on the file extension? 
![image](https://user-images.githubusercontent.com/13314239/187677026-4a533dfd-7008-4e76-9eb5-6ea32e1f3454.png)
Note that the  NTUSER.DAT* files are supposed to be hidden

![image](https://user-images.githubusercontent.com/13314239/187677217-8168718b-416f-41e3-90a9-11bd728b32e2.png)
![image](https://user-images.githubusercontent.com/13314239/187677415-baf7b858-2f8b-46a7-b913-d3e033abdc60.png)

**Comment by meain** [comment]
You can change the color of items by using [LS_COLORS](https://gist.github.com/thomd/7667642), but the problem here is that the executable flag overrides the colors set based on extension.

**Comment by daniejstriata** [comment]
> You can change the color of items by using [LS_COLORS](https://gist.github.com/thomd/7667642), but the problem here is that the executable flag overrides the colors set based on extension.

Is `lsd `ignoring the hidden flag by default?

**Comment by meain** [comment]
What do you mean by hidden flag?

**Comment by daniejstriata** [comment]
In Windows you can set a file to be Hidden.

**Comment by meain** [comment]
Oh, I was not aware of it. I don't think we are handling that as of now.

**Comment by Terraphice** [comment]
Genuinely reconsider please. Ignoring hidden files/folders would make a world of difference for Windows or WSL users. 90% of apps/programs on Windows don't use '.' or '*_*' for hidden files/folders like they would on *Nix, and instead rely on Windows default hidden flag. I know it's a hassle, but such is life for supporting Windows.

If exa implements this before lsd, it'd be a big enough deal for me to switch despite needing to self-compile exa.

**Comment by meain** [comment]
Thanks @TeamTamoad for linking to rg and fd issues. I think it makes sense to have lsd respect hidden files in windows when not using `-a` or `-A`. That said, I thin this is different from the original issue which was about file permissions. I'll create a separate issue (https://github.com/Peltoche/lsd/issues/752) for respecting hidden flag in windows.

PS: No pressure on your to pick it up btw. Just thought I would get your thoughts on this as I have seen you comment on Windows related issues. :D.

**Comment by meain** [comment]
While we are on the topic, my understanding is that there is no such thing as "executable" flag on windows, or is there a flag we can query which `lsd` is not already doing? If there is no such thing as a executable, although we can override the color of executable using `LS_COLORS`, I don't might changing the it so that `lsd` does not treat every file as executable.

**Comment by OldWorldOrdr** [comment]
windows does not have an executable flag, but we could make files with an executable extention like .exe, .bat, .cmd, .ps1, etc show as green.

**Comment by meain** [comment]
I think in that case the quickest option would be to just use the option suggested by https://github.com/Peltoche/lsd/issues/712#issuecomment-1232868513 .

**Comment by OldWorldOrdr** [comment]
Oh by the way, windows has 2 different kinds of hidden files.  There's normal hidden files and Operating system protected files.  Those NTUSER.dat files are the second kind.  The user almost never has to interact with OS protected files, I've never done so once in my 10 years or so of using Windows.  I would suggest making a dedicated command line flag to show OS protected files, and normal hidden files can be shown with just -a or -A.

**Comment by daniejstriata** [comment]
> Oh by the way, windows has 2 different kinds of hidden files. There's normal hidden files and operating system protected files. Those NTUSER.dat files are the second kind. The user almost never has to interact with OS protected files, I've never done so once in my 10 years or so of using Windows. I would suggest making a dedicated command line flag to show OS protected files, and normal hidden files can be shown with just -a or -A.

You are right. I like your suggestion.
