### ISSUE TITLE
LSD doesn't follow symlink on Windows

### ISSUE THREAD

**Issue by barvirm** [Peltoche/lsd#723]
- os: Windows
- `lsd --version`:  0.22.0

## Structure on FS
test_dir/real_dir/file.txt
test_dir/link_dir

Link created via:
cd test_dir;
mklink read_dir link_dir

## Test command
`lsd -al test_dir/link_dir`

## Expected behavior
![image](https://user-images.githubusercontent.com/15948420/184709514-7981c8d0-7ba3-443a-9e55-0f8c7ad2d658.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/15948420/184709448-d925a3bb-f40c-42aa-a45b-fc97f25c936f.png)

## Draft of solution
src/meta/mod.rs:65
This if is responsible for Actual behavior, after removing I got Expected behavior.

**Comment by zwpaper** [comment]
@TeamTamoad could you help have a look at this windows problems?

**Comment by TeamTamoad** [comment]
Sure, I'll take a look at it.

**Comment by TeamTamoad** [comment]
I've run the test command on the WSL. The current behavior matches the GNU `ls` command. So, I don't think this is a bug.
![image](https://user-images.githubusercontent.com/43115371/185159471-113c229f-b9e9-4681-9267-7e0f8feb104c.png)

**Comment by zwpaper** [comment]
thanks @TeamTamoad!

@barvirm I am closing this issue, if you have any more question, feel free to open again

**Comment by meain** [comment]
Related: https://github.com/Peltoche/lsd/pull/403
