### ISSUE TITLE
Flags should be able to Accept Multiple Times

### ISSUE THREAD

**Issue by mitnk** [Peltoche/lsd#73]
.. with the last value counted.

I aliased `lsd` with `lsd=lsd --icon=never`, then I want icons to print, but:

```
$ lsd --icon=auto
error: The argument '--icon <icon>' was provided more than once, but cannot be used multiple times
```

which is not expected. Consider to adopt this same behaviour as `ls`?

**Comment by Peltoche** [comment]
Hi @mitnk,

It's a good idea indeed. I'm on it.

**Comment by mitnk** [comment]
Thanks, awesome!
