### ISSUE TITLE
Update clap to v3.2.16

### ISSUE THREAD

**Issue by tyhdefu** [Peltoche/lsd#730]
Hi, im trying to package lsd for debian, but currently debian has clap `3.2.16` packaged in experimental, which is incompatible with the version lsd uses `2.33.*` - I would prefer to try to upstream these updates if possible.

I am happy to implement this in a PR - I will likely do so soon unless there are objections to this. (Not sure if you want issues before PRs, so I've opened an issue just incase)

This update could also streamline the argument parsing and reduce the amount of code required to parse the arguments.
However - this could require some testing.

#351 could also be fixed, since clap uses structopt (afaik) in v3

**Comment by meain** [comment]
First of all, a huge thanks for working on the deb packaging. It has been a huge gap in lsd for a long time. About the version bump, feel free to submit a PR.  :D
