### ISSUE TITLE
change date behaviour on Windows

### ISSUE THREAD

**Issue by daniejstriata** [Peltoche/lsd#734]
- os: 
- `0.22.0`

## Expected behavior
I use lsd as a replacement for `dir` on  Windows 11 inside Windows Terminal 1.14. When I try to update the data format I keep getting errors that the date value I use is invalid. I'm either not using the correct format or Windows is not fully supported to have a configurable date format.

```
C:\Users\danie>lsd --date+"%Y.%m.%d-%H.%M"
C:\Users\danie>lsd --date+'%Y.%m.%d-%H.%M'
C:\Users\danie>lsd --date+%Y.%m.%d-%H.%M
```
```
error: Invalid value for '--date <date>...': possible values: date, relative, +date-time-format
```
I would like to user a shorter date format as is used by `dir`.

`2022/07/28  15:23`

**Comment by TeamTamoad** [comment]
Try this `lsd -l --date +%Y.%m.%d-%H.%M` 
I've tested it. It should work.
**Note**: use `-l` to make it show date

**Comment by daniejstriata** [comment]
I see what I did wrong. Thanks. Also, in the config I made the line look like
`date: date '+%Y.%m.%d-%H.%M'`
which did not work but I've now seen what needs to be done. The second `date` was not needed.
Thanks for the assistance.
