### ISSUE TITLE
[ Suggestion ] Prioritize home folder icons over symlink icons, while keeping the symlink color.

### ISSUE THREAD

**Issue by YoNoSoyVictor** [Peltoche/lsd#736]
Many people like me have some of their home folders linked to external storage. The problem is that all of them show the same symlink icon. It would be nice if they all showed their distinctive home icons while keeping the hue of a symlink. Here is an example:

![](https://i.redd.it/ci2i2qtxowk91.png)

It would be nice if they showed the cyan color whilst keeping the home icons.

**Comment by meain** [comment]
I think what you are looking for is `-L` which dereferences the symlink to the file that it is pointing to.
