### ISSUE TITLE
Respect hidden flag in Windows

### ISSUE THREAD

**Issue by meain** [Peltoche/lsd#752]
Unlike *nix systems, windows uses a separate flag to mark a file as hidden. We can make `lsd` ignore them when not using `-a` or `-A`.

Previous discussion in https://github.com/Peltoche/lsd/issues/712

**Comment by zwpaper** [comment]
Ref: https://github.com/BurntSushi/winapi-util/commit/16385cb76d859815e5ba531092caf8448f4c4435

**Comment by zwpaper** [comment]
Oh by the way, windows has 2 different kinds of hidden files.  There's normal hidden files and operating system protected files.  Those NTUSER.dat files are the second kind.  The user almost never has to interact with OS protected files, I've never done so once in my 10 years or so of using Windows.  I would suggest making a dedicated command line flag to show OS protected files, and normal hidden files can be shown with just -a or -A.

_Originally posted by @OldWorldOrdr in https://github.com/Peltoche/lsd/issues/712#issuecomment-1279290651_
