### ISSUE TITLE
Better executable file icon (#765 and #764)

### ISSUE THREAD

**Issue by TruncatedDinosour** [Peltoche/lsd#767]
I tried to improve the executable file icon in #765 and #764 but failed, I can't find a good icon for executable files

Currently the icon sucks (``), it makes *all* executable files look like shellscripts, when in all reality -- they're not

I think this should be improved and fixed

**Comment by meain** [comment]
I feel like the current one is pretty good(plus I don't think changing such an frequently used icon would be a good idea). I'll leave this open for a while though just in case others have any opinions.

**Comment by TruncatedDinosour** [comment]
> I feel like the current one is pretty good(plus I don't think changing such an frequently used icon would be a good idea). I'll leave this open for a while though just in case others have any opinions.

the current one looks like a shellscript though

**Comment by meain** [comment]
I'm closing this issue for now. We can reopen if there is serious interest in changing this.
