### ISSUE TITLE
Question on customizing colors for file-types

### ISSUE THREAD

**Issue by rsaeks** [Peltoche/lsd#770]
- os: macOS 12.6
- `lsd --version`:  lsd 0.23.1 
- `echo $TERM`:  xterm-256color
- `echo $LS_COLORS`:  <blank return)

More of a question than a bug report. Right now certain file types appear in different colors (example - images are purple, zip files are red) If I wanted to change the color that appears for pdf files (the icons are all theming correctly) how can that be done? I'm sure it is an easy one that I'm just missing.

Thank you!

**Comment by meain** [comment]
File colors are controlled by `LS_COLORS`.
References:
- https://gist.github.com/thomd/7667642
- https://github.com/trapd00r/LS_COLORS
- https://github.com/sharkdp/lscolors
