### ISSUE TITLE
lsd uses many deprecated features of clap

### ISSUE THREAD

**Issue by sudame** [Peltoche/lsd#786]
- os: --
- `lsd --version`: lsd 0.23.1
- `echo $TERM`: --
- `echo $LS_COLORS`: --

lsd uses version clap v3.2.17 to parse command line arguments, but it also uses some deprecated features of clap. Many of these deprecated features have already been removed in the latest version of clap, v4. I suggest avoiding the use of these deprecated features for future security risks and ease of maintenance.

I have already written code that does not use any deprecated features, but I have found that there have been more changes than I expected (24 changed files with 339 additions and 302 deletions). If there are no problems, I will submit a pull request.

**Comment by zwpaper** [comment]
Hi @sudame, thanks for the investment, please feel free to open a PR, it would always be welcomed
