### ISSUE TITLE
Add a column: ’unique_size' = 'size' / 'inode_count'

### ISSUE THREAD

**Issue by eugenesvk** [Peltoche/lsd#797]
To indicate that you don't need to worry about these dozens of mb files, it's the same single git file :)

**Comment by meain** [comment]
Not sure if this is a good addition to the  feature set of lsd. Besides, if we take unique_size, wouldn't we be reporting incorrect sizes of files? What is the the other hard link is outside the git directory?

**Comment by eugenesvk** [comment]
> Besides, if we take unique_size, wouldn't we be reporting incorrect sizes of files?

No, they're correct for this use case of deduping size info, you can still have your other column with the "correct" size

> What is the the other hard link is outside the git directory?

That's fine
