### ISSUE TITLE
Dot-align size for cleaner differentiation (and customizable size labels)

### ISSUE THREAD

**Issue by eugenesvk** [Peltoche/lsd#798]
Currently it's a bit hard to differentiate between numbers due to the following issues with right-alignment within a column

```
160B ← smallest number taking a lot of space
3.8M
 13M ← why does this appear smaller than 3.5?
3.5K
 23K
2.0K
2.4M
 96B
2.4M
1.1G
```

Instead, if you dot-align a column, you could get this much cleaner output
(the custom labels are better implemented separately)
```
   160  ← no 'b', it's a size column, so bytes are obvious from the context
 3.8  m ← lower case 'm' as it's not big enough for a cap :)
13    m ← now 13 looks bigger than 3
 3.5    ← the size alone is enough to know it's thousands, it's positioned to the left of 160
23    
 2.0  
 2.4  m
 1.1  G ← now a huge number deserves a capitalized label
```

**Comment by meain** [comment]
While it might solve your original problem, I feel like this is only gonna make it harder to parse sizes. Just as a side note, lowercase and uppercase can have different meanings, once can mean bits and the other bytes. Also, if you look into it, 1.1G is bigger than 13m, but in this view, it might look the other way at a quick glance.

**Comment by zwpaper** [comment]
as for the format part, maybe a fixed float number format could help.

for example:

```
160.0B
  3.8M
 13.0M 
  3.5K
 23.0K
  2.0K
  2.4M
 96.0B
  2.4M
  1.1G
```

**Comment by eugenesvk** [comment]
> While it might solve your original problem, I feel like this is only gonna make it harder to parse sizes. 

No, there is no way better structure makes it harder to parse, quite the opposite (though there is always an option to keep the current "easier" alignment)

> Just as a side note, lowercase and uppercase can have different meanings, once can mean bits and the other bytes.

Nope, all the file sizing utils show bytes, so the context precludes any confusion with bits. Also, the confused can continue to use the default labels

> Also, if you look into it, 1.1G is bigger than 13m, but in this view, it might look the other way at a quick glance.

- `G` is bigger and more visible
- So how is this different from the current view? And if so, how is it an argument against?
- You can add an option to have separate size and labels (currently you only have size) and put labels to the left, so reading left to right you'll always see `G` first

> Besides, we do have the option to use colors to distinguish higher sizes

That only helps with `G` vs `m`, it doesn't help with misaligned numbers within the same category

**Comment by eugenesvk** [comment]
> as for the format part, maybe a fixed float number format could help.

Bytes can't have decimals, and again you're making the smallest numbers look huge `160.0B`; also, if your number is precisely `13`, then `13.0M` might mislead you into thinking there is something else behind the decimal, so you lose precision for no benefit

**Comment by zwpaper** [comment]
```
   160  ← no 'b', it's a size column, so bytes are obvious from the context
 3.8  m ← lower case 'm' as it's not big enough for a cap :)
13    m ← now 13 looks bigger than 3
 3.5    ← the size alone is enough to know it's thousands, it's positioned to the left of 160
23    
 2.0  
 2.4  m
 1.1  G ← now a huge number deserves a capitalized label
```

this really looks odd to me...

maybe you need 2 columns for size, one with `B/M/G` and one stuck to `B`, so that you can notice the real size by length and read the human-friendly one

**Comment by eugenesvk** [comment]
> maybe you need 2 columns for size, one with B/M/G and one stuck to B, so that you can notice the real size by length and read the human-friendly one

Not sure I understand, can you paste an example? Do you mean `--size 'bytes'` that `lsd` already has because that's definitely worse as there is way too many useless numbers, and it's easier to get the order from `G` than it is from trying to count all those numbers?


> this really looks odd to me...

Could you be more specific? Is it the extra space before the label or the lack of `k`? You could have it like so as I've seen in some other tools, and the default will have `k` anyway, labels would be configurable
```
   160
 3.8 m
13   m
 3.5 k
23   k
 1.1 G
```

**Comment by meain** [comment]
I don't think we should use both upper and lower case because of the bits vs bytes problem that I mentioned. With that in mind, I like what @zwpaper came up with where you pad with `0`.

```
  2.0K
  2.4M
  1.1G
```
... but even in this, unless you are reading right to left anyways, the numbers can be misleading. We can probably add a space between the numbers and letter, but then that is more or less what we are doing with the default format anyways.

**Comment by eugenesvk** [comment]
> I don't think we should use both upper and lower case because of the bits vs bytes problem that I mentioned

I've already addressed that: if you believe this is an issue, just use the default upper case, changing labels is **optional**

> With that in mind, I like what @zwpaper came up with where you pad with `0`.

You've skipped the worst part of that solution: `96.0B`, and mandatory floats lose precision of `2` vs `2.04`

> ... but even in this, unless you are reading right to left anyways, the numbers can be misleading.

For these cases you have two solutions:
  - add a new column with labels only that you can put before the numbers, like you currently have a column of numbers without labels `size_value` (although this column is currently wrongly left-aligned)
  - even better: you can add an option to place labels to the left side, then you would save 1 space if you need to vs. a separate column

> We can probably add a space between the numbers and letter,

It's best to the the user handle it, space can be part of customizable labels, you can have ` K` or `K`

**Comment by zwpaper** [comment]
I don't really get the point to add the tailing space after numbers.

I am unsubscribing from this issue and maybe leaving it to wait for more people's inputs

**Comment by meain** [comment]
> like you currently have a column of numbers without labels `size_value`
This is not something users have access to right now, I think it mistakenly ended up in the sample config. I'll drop it from there.

> - you can add an option to place labels to the left side, then you would save 1 space if you need to vs. a separate column
> - It's best to the the user handle it, space can be part of customizable labels, you can have  K or K
I don't think we should be adding these. Don't get me wrong, they might end up being useful to a few people, but not enough to warrant addition of new flags and code changes to accommodate customization options. I am not against reconsidering if there is more interest in this issue.

To be frank, the FR looks useful on the surface, but I don't see the advantage that it provides over the default size formatting when trying to parse size values.

**Comment by eugenesvk** [comment]
> I'll drop it from there

Oh, no, why are you removing the useful functionality? It doesn't need to be dropped, it needs to be properly aligned!

> I don't think we should be adding these. Don't get me wrong, they might end up being useful to a few people, but not enough to warrant addition of new flags and code changes to accommodate customization options. I am not against reconsidering if there is more interest in this issue.

Well, just drop the flags, that's anyway not a proper tool for complex config, that's what config files are for
Also, with a general regex text substitution you wouldn't need to add special handling for this request, but instead close many formatting FRs at once

> To be frank, the FR looks useful on the surface, but I don't see the advantage that it provides over the default size formatting when trying to parse size values

Yeah, that's weird. Just out of curiousity, have you worked with spreadsheets much (as these are very basic number layout issues?)

**Comment by meain** [comment]
> Oh, no, why are you removing the useful functionality? It doesn't need to be dropped, it needs to be properly aligned!

It was not meant to be exposed to the user.
```
error: "size_value" isn't a valid value for '--blocks <blocks>...'
        [possible values: permission, user, group, context, size, date, name, inode, links]

        Did you mean "size"?

For more information try --help
```
Also, how is it useful without the label to show what power of bytes it is in?

> Well, just drop the flags, that's anyway not a proper tool for complex config, that's what config files are for
Also, with a general regex text substitution you wouldn't need to add special handling for this request, but instead close many formatting FRs at once

I don't think we are going to add custom text substitutions to lsd.

> as these are very basic number layout issues

I have not really worked a whole lot with spreadsheets, but I've had to work a bit with pandas and other data processing tools. The problem here is that there are not just numbers. Some cannot have decimal places(like bytes), some while they can be decimal should ideally not display decimal places(if 0), and they all have labels attached to them that denotes the power of the value.

I'm closing this issue. I don't think this has a valid usecase. We'll reconsider opening this issue if there is enough interest in this issue later.

**Comment by eugenesvk** [comment]
> Also, how is it useful without the label to show what power of bytes it is in?

That would be the next step to complete the picture!

> I have not really worked a whole lot with spreadsheets, but I've had to work a bit with pandas and other data processing tools.

So not on the relevant part to this issue — data layout and display

> The problem here is that there are not just numbers. Some cannot have decimal places(like bytes),

They don't have decimals in this proposal, so what exactly is the problem?
aligning them is still better
```
960
  1.5
↑ better; ↓ worse
960
1.5

```

> some while they can be decimal should ideally not display decimal places(if 0)

Also perfectly fine:
```
1.2
3
↑ better; ↓ worse
1.2
  3
3.0
```

> , and they all have labels attached to them that denotes the power of the value.

Also fine, this proposal allows you to adjust labels however you want to not have them glued to the number without any separator etc

> We'll reconsider opening this issue if there is enough interest in this issue later

You can't really gather enough interest if you close the issue since it becomes practically invisible! That's what opened issues are for.

> I don't think this has a valid usecase. 

So what's invalid about the extremly common usecase of having proper number alignment in a table of numbers???
You keep saying this here and in other issues, but without any explanation the lack of validity.
