### ISSUE TITLE
Please update Readme to indicate that improvements over ls are out of scope

### ISSUE THREAD

**Issue by eugenesvk** [Peltoche/lsd#803]
At the top of this project's Readme you write that adding features to `ls` is in scope:

> This project is a rewrite of GNU ls with **lots of added features** like colors, icons, tree-view, more **formatting options** etc.

Yet a lot of my feature suggestions (all about user-chosen **optional** things that don't break any default compatibility with `ls`), including a lot about **formatting options** were closed with a canned

> We are mimicking gnu ls behavior here. The idea is to stick to it as much as we can.

or 

> This is done to keep the output consistent with gnu ls.

Which implies that many improvements over `ls` are actually not in scope?

Would you please update the Readme to indicate that so people don't waste time with suggestions?

**Comment by meain** [comment]
We are not against adding features on top of gnu ls. These comments on https://github.com/Peltoche/lsd/issues/802 and https://github.com/Peltoche/lsd/issues/795 were diversions from the behavior that people might be used to.

**Comment by eugenesvk** [comment]
> We are not against adding features on top of gnu ls. These comments on #802 and #795 were diversions from the behavior that people might be used to.

But how can you divert people from the behavior they're used to if **people explicitly opt into** the new behavior?

**Comment by meain** [comment]
I hear you. I guess I prematurely closed #795 , let me reopen that.
