### ISSUE TITLE
Make lsd compile with ARM as target

### ISSUE THREAD

**Issue by emk2203** [Peltoche/lsd#81]
## Expected behavior
On small SBC systems, `lsd` would be extra useful since a lot of interaction happens via `ssh` and the console on these systems. An ARM target would be helpful to ease the install.

## Actual behavior
No ARM target is available, `lsd` needs to be build from source, probable issues present

**Comment by Peltoche** [comment]
Hi @emk2203,

I should be possible to add a target, I'm on it.
