### ISSUE TITLE
Color choice makes output unreadable

### ISSUE THREAD

**Issue by biergit** [Peltoche/lsd#812]
- os: 6.1.10-arch1-1
- `lsd --version`: lsd 0.23.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: 

## Expected behavior
Output is readable

## Actual behavior
![unreadable-lsd](https://user-images.githubusercontent.com/1071968/218205913-c0da55a1-732c-451e-81d1-b1280cd430a0.png)

**Comment by zwpaper** [comment]
it is terminal related, you can change the colors by terminal configuration, LSCOLORS or lsd theme

**Comment by biergit** [comment]
Shouldn't the default be more readable though?

**Comment by zwpaper** [comment]
it is mainly related to the terminal and its color theme, the default color theme works well in most of the terminals by default, and we can not ensure it suits all.
