### ISSUE TITLE
Theme is ignored for color of links (symlinks)

### ISSUE THREAD

**Issue by brainsik** [Peltoche/lsd#813]
- os: macOS 13.2
- `lsd --version`: lsd v0.23.1 (and current master)
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: (unset)

## Expected behavior

I expect the color of valid and invalid symlinks to be ones configured in the theme.

## Actual behavior

The theme colors are ignored.

Ensured I'm using the latest (master) in case it was fixed since last release and unset LS_COLORS:

```sh
$ cargo install --list
lsd v0.23.1 (https://github.com/Peltoche/lsd.git?branch=master#ea56a7c3):
    lsd
$ unset LS_COLORS # to be sure this isn't causing problems
```

Configured theme to make it obvious it was working or not:

```yaml
links:
  valid: [255, 121, 198] # Pink
  invalid: [255, 121, 198] # Pink
```

Output:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/162998/218285053-17152fef-ace0-4109-bb08-6e543f312f0b.png">

**Comment by meowcoder** [comment]
These color settings are for the hard link count, you can enable it like this:

    lsd --blocks name,links

**Comment by brainsik** [comment]
Oh, I see. Thanks for the clarification!

**Comment by kakulukia** [comment]
But how can i color a broken symlink?
