### ISSUE TITLE
Very bad performance on windows located

### ISSUE THREAD

**Issue by cdecompilador** [Peltoche/lsd#817]
This program has a severe performance problem on **windows** when the number of files to read is large (30+), it blocks almost 100ms untill it starts to render with `Core::display`, I dug on the issue and its located on the Win32 call to `GetEffectiveRightsFromAclW`, I don't know why is so expensive.

Proposed solutions:
   1) Figure out why that function call is so expensive (maybe we can't solve it)
   2) Be more inaccurate on windows about the permissions of the user and group (since its not very relevant on windows systems), for example the libcxx of llvm obtains the permissions of a file assuming its read only and then just checking if the property FILE_ATTRIBUTE_READONLY is set or not, assume that everything is executable and similar "inaccurate stuff"
   3) Change the creation of the `Meta` struct to only retrieve the owner/group permissions if its really needed to display
   
Hope this helps

**Comment by zwpaper** [comment]
hi @cdecompilador, thanks for the analysis, we have an issue discussing performance on windows before, I am closing this one and we can discuss it there
