### ISSUE TITLE
LSD fails with the error 'failed to get the group name'

### ISSUE THREAD

**Issue by ls12styler** [Peltoche/lsd#87]
When attached to my company's LAN, LSD works as per the "Expected behaviour". However, when attached to my home network, LSD fails as per the "Actual behaviour". 

I can see that this is is related to: https://github.com/Peltoche/lsd/issues/48 which is now closed. 

I'm suspecting this is down to the fact that when I'm not on the office LAN, my "group" shows up as a number, rather than an actual name, so no name exists.

Is it possible to request that this fails gracefully?

## Expected behaviour
Office LAN
```
➜  ~ ls -l
drwx--x---  myusername  MYCOMPANY\Users       -   Thu Sep 27 12:24:30 2018    Applications
```
Home LAN
```
➜  ~ ls -l
drwx--x---  myusername  123456       -   Thu Sep 27 12:24:30 2018    Applications
```

## Actual behaviour
Office LAN behaves as expected.

Home LAN
```
➜  ~ RUST_BACKTRACE=1 ls -l
thread 'main' panicked at 'failed to get the group name', libcore/option.rs:1008:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
```

**Comment by vercas** [comment]
For me, it sometimes fails to get the user name instead.  
Doesn't matter what user it's running at, sometimes it works, sometimes it doesn't, and it either works or breaks a few hours later.

**Comment by Peltoche** [comment]
Hi @vercas,

For now all the metadata are parsed even without the `-l` flag, so the this (bad) behavior is expected.
