### ISSUE TITLE
Use terminal color scheme

### ISSUE THREAD

**Issue by chmln** [Peltoche/lsd#90]
## Expected behavior
`lsd` uses colors from my terminal color scheme, being consistent with all the other command line tools.

## Actual behavior
It appears `lsd` uses hard-coded colors, instead of the terminal color scheme. The hard coded colors don't look as nice. See screenshot below.

![image](https://user-images.githubusercontent.com/11352152/50466643-c94e9880-096c-11e9-9fcc-e25da2cedd26.png)

My terminal colors:
![image](https://user-images.githubusercontent.com/11352152/50466783-6f9a9e00-096d-11e9-8ccf-0f6253358d02.png)

**Comment by Peltoche** [comment]
Hello @chmln,

As everyone has its own color theme it will be very difficult to make everyone happy. There is a currently a PR (#84) which aim to integrate the `LS_COLOR` variable to lsd. I think it could solve you issue as you will be able to customize your colors as much as you want. I hope we will be able to merge it soon. 

This is sound as a solution to your problem?

**Comment by chmln** [comment]
Hey, thanks for responding so fast!

While `LS_COLORS` is one solution, the easiest way to keep everyone happy is to use built-in terminal colors. This would remove the need for every user to customize via `LS_COLORS` to get readable colors.

Fixed colors make more sense for webpages, but not so much for terminals where the background colors can vary a lot. Powershell, for instance, has a dark blue background by default. I use dark gray. In both cases, contrast suffers. Support for built-in colors would be a huge usability win.

Its rather easy to implement proper color support. It would entail just using e.g. `ansi_term::Colour::Blue` instead `Color::Fixed(33) // DodgerBlue1`. If you're open to the idea, I can submit a PR :)

**Comment by Peltoche** [comment]
I fear the will be not enough colors with the basic ANSI colors. Most of the peoples expects to find the same result than the README but there color theme would change it and it could be deceptive. 

There is another possible solution: as proposed into #92, it could be a good idea to propose a configuration file with a custom theme.

**Comment by Peltoche** [comment]
As we will not directly implement the proposed solution I set this issue as close

**Comment by thekashifmalik** [comment]
Would you be open to using terminal color scheme behind a flag?

It really does seem like expected behavior; CLI tools usually respect terminal colors.

**Comment by Peltoche** [comment]
It seems that a lot of people want this feature so I reopen this issue in order to find a solution.

I see three solutions:
- Move every existing colors to ANSI colors. This will break the output for many peoples.
- Add a flag to choose between hardcoded colors vs AINSI colors.

The first solution seems to be the most standard one, that why I would tend to choose this one but it include a big fat change for current users and that's not good...

Any suggestions?

**Comment by evrimoztamur** [comment]
I don't think that it'll be so destructive to the existing users. See how `exa` handles it at https://github.com/ogham/exa/blob/master/src/style/colours.rs

**Comment by thekashifmalik** [comment]
> It seems that a lot of people want this feature so I reopen this issue in order to find a solution.
> 
> I see three solutions:
> 
> * Move every existing colors to ANSI colors. This will break the output for many peoples.
> * Add a flag to choose between hardcoded colors vs AINSI colors.
> 
> The first solution seems to be the most standard one, that why I would tend to choose this one but it include a big fat change for current users and that's not good...
> 
> Any suggestions?

I like the first option too. We could also add custom colors behind a flag in the future. You are correct that it would change existing colors for users so perhaps we could bump the semver version to indicate that.

That being said, maybe color changes are not breaking functional changes.

What do you think?

**Comment by jbergstroem** [comment]
My vote would be to default to ansi similar to exa then introduce theme support (#92) for people that want to fully customize colors.

**Comment by AndydeCleyre** [comment]
Just agreeing here that exa does a very nice job of using a user's already-chosen colors:

![image](https://user-images.githubusercontent.com/1787385/58200289-79b49480-7ca0-11e9-9b17-145a85fab82b.png)

**Comment by Peltoche** [comment]
I'm sorry I don't have much time in the next few days so I hope that someone would like to make a PR. I should be a easy one because there is not logic changes.

**Comment by thekashifmalik** [comment]
I can take a look.

**Comment by meain** [comment]
@thekashifmalik That would be awesome, I can help you if you need any help with navigating the codebase.

**Comment by Kevin-Mok** [comment]
I seem to have accidentally come across a workaround for this in the fish shell. I noticed that if do `ls` in a terminal, all the following calls to `lsd` in that same terminal use the terminal colors.

![screenshot-2019-08-06_23:52:01](https://user-images.githubusercontent.com/25857736/62594994-92e5de00-b8aa-11e9-955d-d41f70f89553.png)

I am using version 0.15.1 and have tested this in urxvt and st. So to make this automatically happen for all my terminals, I added `ls > /dev/null` to my `config.fish` file. I'd assume this would work in bash and zsh as well, but I have not tested it.

**Comment by Kevin-Mok** [comment]
It seems to use the terminal colors for me if I just call `ls` first in fish.
![screenshot-2019-08-06_23:52:01](https://user-images.githubusercontent.com/25857736/62595189-5cf52980-b8ab-11e9-806c-2ccd276acda3.png)
Not sure why this works for me, but I am using version 0.15.1 and have tested this in `urxvt` and `st`. :thinking: So to make this automatically happen for all my terminals, I added `ls > /dev/null` to my `config.fish` file, and now it just uses the terminal colors even for my first call to `lsd` in a terminal.

**Comment by meain** [comment]
@Kevin-Mok From what I can understand from [here](https://github.com/fish-shell/fish-shell/blob/c2970f96183bd0bb16f8431d5e1c86db04311b7d/share/functions/ls.fish), this happens because fish sets the `LS_COLORS` variable when you call ls. `lsd` does use `LS_COLORS` to figure out the user colors.

@Peltoche A simple fix would be completely let [lscolors](https://github.com/sharkdp/lscolors) take care of colors.

**Comment by erlanger** [comment]
> @Peltoche A simple fix would be completely let lscolors take care of colors.

This would be the best solution.

**Comment by curliq** [comment]
Doesn't seem to apply to the metadata (`lsd -l`)
<img width="596" alt="Image" src="https://github.com/user-attachments/assets/1621b4b9-f13a-4063-9abf-c4140efb7f84" />
