### ISSUE TITLE
Feature request: Choose blocks to display in long format

### ISSUE THREAD

**Issue by meain** [Peltoche/lsd#96]
Add a feature which would let users choose the blocks to be displayed. The blocks could be a comma separated list.

Maybe something like:

```sh
lsd --blocks permission,size,name
```

This would just show these blocks. Maybe even show them in that specific order as well.

**Comment by Peltoche** [comment]
Hi @meain,

I like the idea! By default it put nothing and the `-l` option is just an alias for `--blocks permission,size,name,...`. It could bring a lot of flexibility. For the option format I think we should just let `clap` handle it the way it want.

Should I assign this contrib to you?

**Comment by meain** [comment]
That sounds good. My initial idea was `--blocks` will be only use with `-l`, but this sounds better.

I might get a bit busy the new few weeks. So, if anyone wants to take it up, that's cool. If no one has already picked it up by then, I will work on it.
